// Code generated by aicoded. DO NOT EDIT.

package n_id

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "f30ef2bd"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Due     string
	Invoice Invoice
	Paid    string
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/invoices/n_id")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"*"}} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:3
	due := s.RouteData.Due
	_ = due
//line index.html:2
	invoice := s.RouteData.Invoice
	_ = invoice
//line index.html:4
	paid := s.RouteData.Paid
	_ = paid
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:5
	if err := render.Text(w, invoice.Customer); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:6
	if err := render.Text(w, invoice.Viewer); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
//line index.html:7
	for _, l := range invoice.Lines {
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
//line index.html:7
		if err := render.Text(w, l.Item); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html4); err != nil {
			return err
		}
//line index.html:7
		if err := render.Text(w, l.Amount); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html5); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html6); err != nil {
		return err
	}
//line index.html:8
	if err := render.Text(w, due); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html7); err != nil {
		return err
	}
//line index.html:9
	if err := render.Text(w, paid); err != nil {
		return err
	}
//line route_gen.go:127
	if _, err := io.WriteString(w, _html8); err != nil {
		return err
	}
	return nil
}

const (
	_html0 = "<h1 id=\"customer\">"
	_html1 = "</h1> <p id=\"viewer\">"
	_html2 = "</p> <ul id=\"lines\">"
	_html3 = "<li>"
	_html4 = ": "
	_html5 = "</li>"
	_html6 = "</ul> <p id=\"due\">"
	_html7 = "</p> <p id=\"paid\">"
	_html8 = "</p>"
)
