// Code generated by aicoded. DO NOT EDIT.

package users

import (
	"context"
	"io"
	"sync"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/reactive"
	"aicoded.dev/framework/web/render"
)

const routeKey = "954dac29"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	CanAdd    bool
	Current   string
	UserCount int
	Users     []User
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	DefaultRoute(ctx context.Context, r *web.Request) (string, error)
	// Subscribe runs while the page is open and must return when ctx is done.
	Subscribe(ctx context.Context, r *web.Request, state *ReactiveState) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/users")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"staff"}} }

func (rt *route) Layout() bool { return true }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/aicoded/reactive-ZRZHG67R.css\">", "<script defer src=\"/_aicoded/assets/aicoded/reactive-MTQXR3MF.js\"></script>", "<link rel=\"stylesheet\" href=\"/_aicoded/assets/pages/users/index-BTHWXM3R.css\">"})
	return s
}

type state struct {
	web.Frame
	mu        sync.Mutex
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(ctx context.Context, r *web.Request) (string, error) {
	return s.dp.DefaultRoute(ctx, r)
}

func (s *state) RouteKey() string { return routeKey }

func (s *state) Snapshot(ctx context.Context) map[string]reactive.Binding {
	s.mu.Lock()
	defer s.mu.Unlock()
	return map[string]reactive.Binding{
		routeKey + ".userCount": renderBlock_userCount(ctx, &s.RouteData),
	}
}

func (s *state) Subscribe(ctx context.Context, r *web.Request, conn *reactive.Conn) error {
	return s.dp.Subscribe(ctx, r, &ReactiveState{ctx: ctx, s: s, conn: conn})
}

func (s *state) HandleWrite(ctx context.Context, r *web.Request, conn *reactive.Conn, msg reactive.WriteMsg) {
	conn.Reject(ctx, msg, "unknown variable", reactive.CodeValidation)
}

// ReactiveState sends new values of the page's live variables to one open page. Its Set
// methods may be called from any goroutine.
type ReactiveState struct {
	ctx  context.Context
	s    *state
	conn *reactive.Conn
}

// SetUserCount stores v as userCount and sends the parts of the page that show it.
func (rs *ReactiveState) SetUserCount(v int) {
	rs.s.mu.Lock()
	defer rs.s.mu.Unlock()
	rs.s.RouteData.UserCount = v
	rs.conn.Enqueue(routeKey+".userCount", renderBlock_userCount(rs.ctx, &rs.s.RouteData))
}

func (s *state) Write(w io.Writer) error {
//line index.html:4
	canAdd := s.RouteData.CanAdd
	_ = canAdd
//line index.html:3
	current := s.RouteData.Current
	_ = current
//line index.html:5
	userCount := s.RouteData.UserCount
	_ = userCount
//line index.html:2
	users := s.RouteData.Users
	_ = users
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:9
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
	if err := render.Text(w, userCount); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
//line index.html:10
	if canAdd {
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
//line index.html:12
	for _, u := range users {
		if _, err := io.WriteString(w, _html5); err != nil {
			return err
		}
//line index.html:12
		if err := render.Attr(w, render.If(u.Login == current, "active", "")); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html6); err != nil {
			return err
		}
//line index.html:12
		if err := render.URLPart(w, u.Login); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html7); err != nil {
			return err
		}
//line index.html:12
		if err := render.Text(w, u.Name); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html8); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html9); err != nil {
		return err
	}
	if err := s.WriteChild(w); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html10); err != nil {
		return err
	}
	return nil
}

func renderBlock_userCount(_ context.Context, data *RouteData) reactive.Binding {
	return reactive.TextBinding(render.Format(data.UserCount))
}

const (
	_html0  = "<div class=\"users\"> <aside> <h2>Users</h2> <p class=\"muted\"><span id=\"user-count\">"
	_html1  = "<span data-ssr-bind=\"954dac29.userCount\">"
	_html2  = "</span></span> people</p> "
	_html3  = "<a id=\"add-user\" href=\"/users/add\">Add a user</a>"
	_html4  = " <ul id=\"user-list\"> "
	_html5  = "<li><a class=\""
	_html6  = "\" href=\"/users/"
	_html7  = "\">"
	_html8  = "</a></li>"
	_html9  = " </ul> </aside> <section> "
	_html10 = " </section> </div>"
)
