package generate

import (
	"bytes"
	"errors"
	"io/fs"
	"maps"
	"os"
	"path"
	"path/filepath"
	"slices"

	"aicoded.dev/framework/cmd/aicoded/internal/rpcschema"
	"aicoded.dev/framework/manifest"
)

// Generate turns the app in dir into generated code: its pages/ folder into Go code and assets,
// its rpc/ package into the method table and codec the app serves other apps with, pinning the
// field numbers in .aicoded/rpc.json, and the snapshots in .aicoded/services/ into the clients of
// the apps it calls. It writes the access and services sections of the app's permission list,
// aicoded.yaml, when the app has one. It writes nothing unless every step succeeds and the
// permission list can take the sections. It is Run with the apps next to dir as the workspace.
func Generate(dir string) error {
	_, err := Run(dir, Options{})
	return err
}

// WriteFile writes data at name, a slash-separated path in the app folder dir, the way Generate
// writes a snapshot: atomically, with mode 0644, creating missing folders with mode 0755, and
// never following a symbolic link out of dir.
func WriteFile(dir, name string, data []byte) error {
	root, err := os.OpenRoot(dir)
	if err != nil {
		return err
	}
	defer root.Close()
	rel := filepath.FromSlash(name)
	if err := mkdirs(root, filepath.Dir(rel)); err != nil {
		return err
	}
	return swap(root, rel, data, 0o644)
}

// sections keeps the permission list with its generated sections in g.manifest when the app has
// one and a section changed: access from the pages, access: {} without them, and services from
// what the app calls and serves. The services section is written when it says something or was
// there before.
func (g *gen) sections(routes []*Route, services manifest.Services) error {
	root, err := os.OpenRoot(g.app.Dir)
	if err != nil {
		return err
	}
	defer root.Close()
	data, err := root.ReadFile(manifestFile)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	access, err := accessSection(accessMap(routes))
	if err != nil {
		return err
	}
	out, err := withAccess(data, access)
	if err != nil {
		return err
	}
	before, _, err := parseManifest(data)
	if err != nil {
		return err
	}
	if _, had := before["services"]; had || len(services.Calls) > 0 || len(services.Serves) > 0 {
		section, err := servicesSection(services)
		if err != nil {
			return err
		}
		if out, err = withSection(out, "services", servicesMarker, section); err != nil {
			return err
		}
	}
	if !bytes.Equal(out, data) {
		g.manifest = out
	}
	return nil
}

// gen holds the output of one run until every page has generated.
type gen struct {
	app App
	// files maps the path of every generated file, relative to the app, to its content.
	files map[string][]byte
	// stubs maps the path of the data provider of every route to the stub written where there
	// is none.
	stubs map[string][]byte
	// assets holds the built scripts, styles and images.
	assets *assets
	// routes holds the routes being generated by path.
	routes map[string]*Route
	// manifest is the permission list to write, or nil when it stays as it is.
	manifest []byte
	// snapshots maps the path of every schema snapshot that changed, relative to the app, to its
	// content. They are written atomically, since the field numbers they pin must never be lost.
	snapshots map[string][]byte
	// stale holds the paths, relative to the app, of the generated files outside pages/ that
	// write removes.
	stale []string
	// emptied holds the paths, relative to the app, of the folders that write removes after the
	// stale files when they are left empty, each before the folder that holds it.
	emptied []string
	// schema is the numbered schema of the functions the app serves, or nil without rpc/.
	schema *rpcschema.Schema
}

func newGen(app App) *gen {
	return &gen{
		app:       app,
		files:     map[string][]byte{},
		stubs:     map[string][]byte{},
		assets:    newAssets(app),
		routes:    map[string]*Route{},
		snapshots: map[string][]byte{},
	}
}

// assetTags returns the script and style tags of the route at routePath.
func (g *gen) assetTags(routePath string) []string {
	if tags := g.assets.tags[routePath]; tags != nil {
		return tags
	}
	return []string{}
}

// live reports whether the route at routePath has live variables or calls, which travel over
// the page's live connection.
func (g *gen) live(routePath string) bool {
	r := g.routes[routePath]
	return r != nil && (r.live != nil || len(r.Template.Calls()) > 0)
}

// build generates the code of every route, the types of the live connection of every route with
// live variables or calls, the pages handler, the scripts, styles and images of the pages, the
// live-page runtime, which comes first on every such route, and the file that embeds them.
func (g *gen) build(routes []*Route) error {
	for _, r := range routes {
		g.routes[r.Path] = r
	}
	for _, r := range routes {
		if g.live(r.Path) {
			ts, err := liveTS(r)
			if err != nil {
				return err
			}
			g.files[path.Join(folder(r.Path), "reactive_gen.ts")] = ts
		}
	}
	if err := g.assets.build(routes, g.files); err != nil {
		return err
	}
	if slices.ContainsFunc(routes, func(r *Route) bool { return g.live(r.Path) }) {
		runtime, err := g.assets.runtime()
		if err != nil {
			return err
		}
		for _, r := range routes {
			if g.live(r.Path) {
				g.assets.tags[r.Path] = append(slices.Clone(runtime), g.assets.tags[r.Path]...)
			}
		}
	}
	if err := g.checkDocuments(routes); err != nil {
		return err
	}
	if err := g.checkAssets(routes); err != nil {
		return err
	}
	for _, r := range routes {
		code, err := g.route(r)
		if err != nil {
			return err
		}
		g.files[path.Join(folder(r.Path), routeFile)] = code
		stub, err := g.stub(r)
		if err != nil {
			return err
		}
		g.stubs[path.Join(folder(r.Path), "dataprovider.go")] = stub
	}
	handler, err := g.handler(routes)
	if err != nil {
		return err
	}
	g.files["pages/handler_gen.go"] = handler
	code := assetsCode
	if len(g.assets.files) > 0 {
		code = embedCode
	}
	g.files["pages/assets_gen.go"] = []byte(code)
	return nil
}

// generatedNames are the per-route files write removes when their route is gone.
var generatedNames = map[string]bool{routeFile: true, "reactive_gen.ts": true}

// write removes the generated files of routes that are gone, the other stale generated files and
// the folders they leave empty, writes the generated files, replaces pages/assets_gen with the
// built assets, writes a data provider stub where a route has none, then the schema snapshots and
// the permission list. It works inside the app's folder only: it never follows a symbolic link
// out of it, and never writes through one.
func (g *gen) write() error {
	root, err := os.OpenRoot(g.app.Dir)
	if err != nil {
		return err
	}
	defer root.Close()
	out := path.Join("pages", assetsDir)
	if err := root.RemoveAll(filepath.FromSlash(out)); err != nil {
		return err
	}
	if _, err := root.Stat("pages"); err == nil {
		err = fs.WalkDir(root.FS(), "pages", func(p string, d fs.DirEntry, err error) error {
			switch {
			case err != nil:
				return err
			case d.IsDir() || !generatedNames[d.Name()]:
				return nil
			}
			if _, ok := g.files[p]; ok {
				return nil
			}
			return root.Remove(filepath.FromSlash(p))
		})
		if err != nil {
			return err
		}
	}
	for _, rel := range g.stale {
		if err := root.Remove(filepath.FromSlash(rel)); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
	}
	for _, rel := range g.emptied {
		if err := removeEmpty(root, rel); err != nil {
			return err
		}
	}
	for _, rel := range slices.Sorted(maps.Keys(g.files)) {
		name := filepath.FromSlash(rel)
		if err := mkdirs(root, filepath.Dir(name)); err != nil {
			return err
		}
		if err := root.Remove(name); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
		if err := create(root, name, g.files[rel]); err != nil {
			return err
		}
	}
	for _, rel := range slices.Sorted(maps.Keys(g.assets.files)) {
		name := filepath.Join(filepath.FromSlash(out), filepath.FromSlash(rel))
		if err := mkdirs(root, filepath.Dir(name)); err != nil {
			return err
		}
		if err := create(root, name, g.assets.files[rel]); err != nil {
			return err
		}
	}
	for _, rel := range slices.Sorted(maps.Keys(g.stubs)) {
		err := create(root, filepath.FromSlash(rel), g.stubs[rel])
		if err != nil && !errors.Is(err, fs.ErrExist) {
			return err
		}
	}
	for _, rel := range slices.Sorted(maps.Keys(g.snapshots)) {
		name := filepath.FromSlash(rel)
		if err := mkdirs(root, filepath.Dir(name)); err != nil {
			return err
		}
		if err := swap(root, name, g.snapshots[rel], 0o644); err != nil {
			return err
		}
	}
	if g.manifest != nil {
		return replace(root, manifestFile, g.manifest)
	}
	return nil
}

// mkdirs creates the missing folders of dir in root, each with mode 0755.
func mkdirs(root *os.Root, dir string) error {
	if dir == "." {
		return nil
	}
	if err := mkdirs(root, filepath.Dir(dir)); err != nil {
		return err
	}
	err := root.Mkdir(dir, 0o755)
	if errors.Is(err, fs.ErrExist) {
		return nil
	}
	if err != nil {
		return err
	}
	return root.Chmod(dir, 0o755)
}

// removeEmpty removes the folder dir, a slash-separated path in root, when it is empty.
func removeEmpty(root *os.Root, dir string) error {
	entries, err := fs.ReadDir(root.FS(), dir)
	if errors.Is(err, fs.ErrNotExist) || err == nil && len(entries) > 0 {
		return nil
	}
	if err != nil {
		return err
	}
	return root.Remove(filepath.FromSlash(dir))
}

// create writes a new file with mode 0644 at name in root. It fails with fs.ErrExist when
// anything is there, a symbolic link included.
func create(root *os.Root, name string, data []byte) error {
	f, err := root.OpenFile(name, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return err
	}
	if err := f.Chmod(0o644); err != nil {
		_ = f.Close()
		return err
	}
	_, err = f.Write(data)
	return errors.Join(err, f.Close())
}

// replace writes data over the file at name in root as swap does, keeping the file's mode.
func replace(root *os.Root, name string, data []byte) error {
	st, err := root.Stat(name)
	if err != nil {
		return err
	}
	return swap(root, name, data, st.Mode().Perm())
}

// swap writes data with mode at name in root through a new temporary file that it renames over
// name, so name always holds the old or the new data in full. Whatever was at name, a symbolic
// link included, is replaced.
func swap(root *os.Root, name string, data []byte, mode fs.FileMode) error {
	tmp := name + ".aicoded-tmp"
	if err := root.Remove(tmp); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	f, err := root.OpenFile(tmp, os.O_WRONLY|os.O_CREATE|os.O_EXCL, mode)
	if err != nil {
		return err
	}
	err = f.Chmod(mode)
	if err == nil {
		_, err = f.Write(data)
	}
	if err == nil {
		err = f.Sync()
	}
	if err = errors.Join(err, f.Close()); err == nil {
		err = root.Rename(tmp, name)
	}
	if err != nil {
		_ = root.Remove(tmp)
	}
	return err
}
