package generate

import (
	"fmt"
	"maps"
	"slices"
	"strings"

	"aicoded.dev/framework/cmd/aicoded/internal/generate/template"
)

// liveTS returns the reactive_gen.ts of a route with live variables or calls: the types of its
// live variables and calls, and the page's typed handle on its live connection.
func liveTS(r *Route) ([]byte, error) {
	registry := map[string]string{}
	calls, err := callsTS(r, registry)
	if err != nil {
		return nil, err
	}
	var vars, writable []template.Variable
	if r.live != nil {
		vars, writable = r.live.vars, r.live.writable
	}
	inProgress := map[string]bool{}
	types := map[string]string{}
	var read strings.Builder
	for _, v := range vars {
		ts, warning := goTypeToTSType(v.Type, registry, inProgress)
		types[v.Name] = ts
		if warning != "" {
			read.WriteString("  // " + warning + "\n")
		}
		read.WriteString("  " + v.Name + ": " + ts + ";\n")
	}
	var write strings.Builder
	for _, v := range writable {
		write.WriteString("  " + v.Name + ": " + types[v.Name] + ";\n")
	}

	var b strings.Builder
	b.WriteString("// Code generated by aicoded. DO NOT EDIT.\n")
	b.WriteString("// Live variables and calls of the page " + r.Path + ".\n\n")
	for _, name := range slices.Sorted(maps.Keys(registry)) {
		b.WriteString(registry[name] + "\n\n")
	}
	b.WriteString("export type ReadVars = " + tsObject(read.String()) + ";\n\n")
	b.WriteString("export type WriteVars = " + tsObject(write.String()) + ";\n\n")
	b.WriteString(calls)
	b.WriteString(`
export interface CallError {
  status: number;
  message: string;
}

type CallMap = Record<string, { in: unknown; out: unknown }>;

export interface Route<R, W, C extends CallMap> {
  get<K extends keyof R & string>(name: K): string | undefined;
  set<K extends keyof W & string>(name: K, value: W[K]): void;
  on<K extends keyof R & string>(name: K, callback: (value: string) => void): () => void;
  onError(callback: (name: string, message: string) => void): () => void;
  onConnect(callback: () => void): () => void;
  onDisconnect(callback: (code: number) => void): () => void;
  // call runs one of the page's <ssr:call> functions; it rejects with a CallError.
  call<K extends keyof C & string>(name: K, args: C[K]["in"]): Promise<C[K]["out"]>;
}

export const ssr = (globalThis as unknown as { aicodedReactive: { route<R, W, C extends CallMap>(key: string): Route<R, W, C> } })
  .aicodedReactive.route<ReadVars, WriteVars, Calls>("` + routeKey(r.Path) + `");
`)
	return []byte(b.String()), nil
}

// tsObject returns an object type with the property lines props, or {} when there are none.
func tsObject(props string) string {
	if props == "" {
		return "{}"
	}
	return "{\n" + props + "}"
}

// goTypeToTSType maps a Go type to a TypeScript type. A named type becomes an opaque interface,
// which it adds to structRegistry by name; inProgress holds the named types being mapped, so a
// cycle becomes unknown. The warning says what could not be mapped exactly. As encoding/json
// writes them, a nil pointer, slice or map is null and a []byte is a base64 string. The only
// unions are " | null", so an element type ending in one is put in parentheses.
func goTypeToTSType(goType string, structRegistry map[string]string, inProgress map[string]bool) (tsType string, warning string) {
	goType = strings.TrimSpace(goType)

	if strings.HasPrefix(goType, "*") {
		inner, w := goTypeToTSType(goType[1:], structRegistry, inProgress)
		return nullable(inner), w
	}

	if goType == "[]byte" || goType == "[]uint8" {
		return "string | null", ""
	}

	if strings.HasPrefix(goType, "[]") {
		elemType, w := goTypeToTSType(goType[2:], structRegistry, inProgress)
		if strings.HasSuffix(elemType, " | null") {
			elemType = "(" + elemType + ")"
		}
		return elemType + "[] | null", w
	}

	if strings.HasPrefix(goType, "map[") {
		rest := goType[4:]
		bracketDepth := 0
		keyEnd := -1
		for i, c := range rest {
			if c == '[' {
				bracketDepth++
			} else if c == ']' {
				if bracketDepth == 0 {
					keyEnd = i
					break
				}
				bracketDepth--
			}
		}
		if keyEnd < 0 {
			return "Record<string, unknown> | null", "go type " + goType + ": malformed map type"
		}
		keyType := rest[:keyEnd]
		valType := rest[keyEnd+1:]
		intKey := predeclaredTS(keyType) == "number" && !strings.HasPrefix(keyType, "float")
		if keyType != "string" && !intKey {
			return "Record<string, unknown> | null", fmt.Sprintf("map key type %q is not a string or an integer. Falling back to Record<string, unknown>.", keyType)
		}
		valTSType, w := goTypeToTSType(valType, structRegistry, inProgress)
		return "Record<string, " + valTSType + "> | null", w
	}

	if goType == "time.Time" {
		return "string", ""
	}

	switch goType {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr", "byte", "rune", "float32", "float64":
		return "number", ""
	case "complex64", "complex128":
		return "unknown", ""
	case "string":
		return "string", ""
	case "bool":
		return "boolean", ""
	}

	if isSimpleIdentifier(goType) {
		if !tsDeclarable(goType) {
			return "unknown", fmt.Sprintf("type %q is unknown in TypeScript, because reactive_gen.ts cannot declare that name", goType)
		}
		if inProgress[goType] {
			return "unknown", fmt.Sprintf("cyclic type %q substituted with unknown in TypeScript interface", goType)
		}
		if _, ok := structRegistry[goType]; ok {
			return goType, ""
		}
		inProgress[goType] = true
		structRegistry[goType] = fmt.Sprintf("// %s: opaque struct type. Add a module augmentation for field-level typing.\nexport interface %s {\n  [key: string]: unknown;\n}", goType, goType)
		delete(inProgress, goType)
		return goType, ""
	}

	return "unknown", ""
}

// isSimpleIdentifier reports whether s is an ASCII identifier: letters, digits and _, not
// starting with a digit.
func isSimpleIdentifier(s string) bool {
	if len(s) == 0 {
		return false
	}
	for i, c := range s {
		if i == 0 {
			if !isLetter(c) {
				return false
			}
		} else if !isLetter(c) && !isDigit(c) {
			return false
		}
	}
	return true
}

func isLetter(c rune) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_'
}

func isDigit(c rune) bool {
	return c >= '0' && c <= '9'
}
