// Code generated by aicoded. DO NOT EDIT.

package n_id

import (
	"context"
	"encoding/json"
	"io"
	"net/http"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/form"
	"aicoded.dev/framework/web/render"
)

const routeKey = "d959c49d"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Note Note
}

// FormGiveValues holds the fields of the form give.
type FormGiveValues struct {
	form.BaseFormValues
	To form.Input[string]
}

// FormRenameValues holds the fields of the form rename.
type FormRenameValues struct {
	form.BaseFormValues
	Title form.Input[string]
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Guard(ctx context.Context, r *web.Request) error
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	InitGive(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormGiveValues) error
	ProcessGive(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormGiveValues) error
	InitRename(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormRenameValues) error
	ProcessRename(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormRenameValues) error
	CallStar(ctx context.Context, r *web.Request, in StarIn) (StarOut, error)
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route { return &route{dp: dp} }

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"*"}} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/aicoded/reactive-ZRZHG67R.css\">", "<script defer src=\"/_aicoded/assets/aicoded/reactive-MTQXR3MF.js\"></script>", "<script defer src=\"/_aicoded/assets/pages/notes/n_id/index-RRRN6CE3.js\"></script>"})
	s.FormGive.SetElements([]form.Element{&s.FormGive.To})
	s.FormRename.SetElements([]form.Element{&s.FormRename.Title})
	return s
}

type state struct {
	web.Frame
	dp         RouteDataProvider
	RouteData  RouteData
	FormGive   FormGiveValues
	FormRename FormRenameValues
}

func (s *state) Guard(ctx context.Context, r *web.Request) error { return s.dp.Guard(ctx, r) }

func (s *state) InitForms(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	s.FormGive.Prepare(routeKey+".give", r.CSRFToken())
	if err := s.dp.InitGive(ctx, r, w, &s.FormGive); err != nil {
		return err
	}
	s.FormRename.Prepare(routeKey+".rename", r.CSRFToken())
	if err := s.dp.InitRename(ctx, r, w, &s.FormRename); err != nil {
		return err
	}
	return nil
}

func (s *state) SubmitForm(ctx context.Context, r *web.Request, w web.ResponseWriter, id string) (bool, error) {
	switch id {
	case routeKey + ".give":
		if form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormGive.To.Process(r.Request, "to", false, true)
		s.FormGive.MarkValidated()
		if s.FormGive.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessGive(ctx, r, w, &s.FormGive)
	case routeKey + ".rename":
		if form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormRename.Title.Process(r.Request, "title", false, true)
		s.FormRename.MarkValidated()
		if s.FormRename.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessRename(ctx, r, w, &s.FormRename)
	}
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) RouteKey() string { return routeKey }

func (s *state) Call(ctx context.Context, r *web.Request, name string, args json.RawMessage) (any, error) {
	switch name {
	case "star":
		var in StarIn
		if err := web.DecodeArgs(args, &in); err != nil {
			return nil, err
		}
		return s.dp.CallStar(ctx, r, in)
	}
	return nil, web.Error(http.StatusNotFound, "This call is not on this page.")
}

func (s *state) Write(w io.Writer) error {
//line index.html:2
	note := s.RouteData.Note
	_ = note
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:4
	if err := render.Text(w, note.Title); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
	{
		form := s.FormRename
		_ = form
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html4); err != nil {
			return err
		}
		{
//line index.html:8
			input := form.Title
			_ = input
			if _, err := io.WriteString(w, _html5); err != nil {
				return err
			}
			if input.IsNotNull() {
				if _, err := io.WriteString(w, _html6); err != nil {
					return err
				}
				v := any(input.GetValue())
				if input.HasError() {
					v = input.GetFormValue()
				}
				if err := render.Attr(w, v); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html7); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html10); err != nil {
		return err
	}
	{
		form := s.FormGive
		_ = form
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html4); err != nil {
			return err
		}
		{
//line index.html:12
			input := form.To
			_ = input
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
			if input.IsNotNull() {
				if _, err := io.WriteString(w, _html6); err != nil {
					return err
				}
				v := any(input.GetValue())
				if input.HasError() {
					v = input.GetFormValue()
				}
				if err := render.Attr(w, v); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html7); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
	}
	return nil
}

const (
	_html0  = "<h1 id=\"title\">"
	_html1  = "</h1> <button id=\"star\" type=\"button\">Star</button> <p id=\"star-result\"></p> "
	_html2  = "<form method=\"post\" enctype=\"application/x-www-form-urlencoded\"><input type=\"hidden\" name=\"_aicoded_form\" value=\""
	_html3  = "\"><input type=\"hidden\" name=\"_aicoded_csrf\" value=\""
	_html4  = "\"> "
	_html5  = "<input name=\"title\" type=\"text\""
	_html6  = " value=\""
	_html7  = "\""
	_html8  = " required>"
	_html9  = " <button type=\"submit\">Save</button> </form>"
	_html10 = " "
	_html11 = "<input name=\"to\" type=\"text\""
	_html12 = " <button type=\"submit\">Give</button> </form>"
)
