// Code generated by aicoded. DO NOT EDIT.

package admin

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
)

const routeKey = "84a04c24"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct{}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	DefaultRoute(ctx context.Context, r *web.Request) (string, error)
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/admin")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"admin"}} }

func (rt *route) Layout() bool { return true }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(ctx context.Context, r *web.Request) (string, error) {
	return s.dp.DefaultRoute(ctx, r)
}

func (s *state) Write(w io.Writer) error {
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
	if err := s.WriteChild(w); err != nil {
		return err
	}
//line route_gen.go:71
	return nil
}

const (
	_html0 = "<nav><a href=\"/admin/live\">Live</a> <a href=\"/admin/settings\">Settings</a></nav> "
)
