// Code generated by aicoded. DO NOT EDIT.

package n_id

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "ee853556"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	CanEdit      bool
	CanSetStatus bool
	Ticket       Ticket
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Guard(ctx context.Context, r *web.Request) error
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route { return &route{dp: dp} }

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"staff"}} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(ctx context.Context, r *web.Request) error { return s.dp.Guard(ctx, r) }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:3
	canEdit := s.RouteData.CanEdit
	_ = canEdit
//line index.html:4
	canSetStatus := s.RouteData.CanSetStatus
	_ = canSetStatus
//line index.html:2
	ticket := s.RouteData.Ticket
	_ = ticket
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:6
	if err := render.Text(w, ticket.Title); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:9
	if err := render.Text(w, ticket.Room); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
//line index.html:11
	if err := render.Attr(w, ticket.Status); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html3); err != nil {
		return err
	}
//line index.html:11
	if err := render.Text(w, ticket.Status.Label()); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
//line index.html:13
	if err := render.Text(w, ticket.Author); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html5); err != nil {
		return err
	}
//line index.html:15
	if err := render.Text(w, ticket.Created.Format("2006-01-02 15:04 UTC")); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html6); err != nil {
		return err
	}
//line index.html:17
	if err := render.Text(w, ticket.Updated.Format("2006-01-02 15:04 UTC")); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html7); err != nil {
		return err
	}
//line index.html:19
	if err := render.Text(w, ticket.Details); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html8); err != nil {
		return err
	}
//line index.html:21
	if canEdit {
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
//line index.html:21
		if err := render.URLPart(w, ticket.ID); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html10); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html11); err != nil {
		return err
	}
//line index.html:22
	if canSetStatus {
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
//line index.html:22
		if err := render.URLPart(w, ticket.ID); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html13); err != nil {
			return err
		}
	}
//line route_gen.go:162
	if _, err := io.WriteString(w, _html14); err != nil {
		return err
	}
	return nil
}

const (
	_html0  = "<article class=\"card\"> <h1 id=\"ticket-title\">"
	_html1  = "</h1> <dl> <dt>Room</dt> <dd id=\"ticket-room\">"
	_html2  = "</dd> <dt>Status</dt> <dd id=\"ticket-status\" class=\"status "
	_html3  = "\">"
	_html4  = "</dd> <dt>Reported by</dt> <dd id=\"ticket-author\">"
	_html5  = "</dd> <dt>Reported</dt> <dd>"
	_html6  = "</dd> <dt>Updated</dt> <dd>"
	_html7  = "</dd> </dl> <p id=\"ticket-details\" class=\"details\">"
	_html8  = "</p> <p class=\"actions\"> "
	_html9  = "<a id=\"edit\" href=\"/tickets/"
	_html10 = "/edit\">Edit</a>"
	_html11 = " "
	_html12 = "<a id=\"set-status\" href=\"/tickets/"
	_html13 = "/status\">Change the status</a>"
	_html14 = " </p> </article>"
)
