// Code generated by aicoded. DO NOT EDIT.
// Live variables and calls of the page /admin/live.

export type ReadVars = {
  message: string;
  ticks: number;
};

export type WriteVars = {
  message: string;
};

export type Calls = Record<string, never>;

export interface CallError {
  status: number;
  message: string;
}

type CallMap = Record<string, { in: unknown; out: unknown }>;

export interface Route<R, W, C extends CallMap> {
  get<K extends keyof R & string>(name: K): string | undefined;
  set<K extends keyof W & string>(name: K, value: W[K]): void;
  on<K extends keyof R & string>(name: K, callback: (value: string) => void): () => void;
  onError(callback: (name: string, message: string) => void): () => void;
  onConnect(callback: () => void): () => void;
  onDisconnect(callback: (code: number) => void): () => void;
  // call runs one of the page's <ssr:call> functions; it rejects with a CallError.
  call<K extends keyof C & string>(name: K, args: C[K]["in"]): Promise<C[K]["out"]>;
}

export const ssr = (globalThis as unknown as { aicodedReactive: { route<R, W, C extends CallMap>(key: string): Route<R, W, C> } })
  .aicodedReactive.route<ReadVars, WriteVars, Calls>("ace08953");
