// Code generated by aicoded. DO NOT EDIT.

package live

import (
	"context"
	"errors"
	"io"
	"strings"
	"sync"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/reactive"
	"aicoded.dev/framework/web/render"
)

const routeKey = "ace08953"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Message string
	Ticks   int
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	// Subscribe runs while the page is open and must return when ctx is done.
	Subscribe(ctx context.Context, r *web.Request, state *ReactiveState) error
	ValidateMessage(ctx context.Context, r *web.Request, val string) (string, error)
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/admin/live")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/aicoded/reactive-ZRZHG67R.css\">", "<script defer src=\"/_aicoded/assets/aicoded/reactive-MTQXR3MF.js\"></script>", "<script defer src=\"/_aicoded/assets/pages/admin/live/index-TRADWDPA.js\"></script>"})
	return s
}

type state struct {
	web.Frame
	mu        sync.Mutex
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) RouteKey() string { return routeKey }

func (s *state) Snapshot(ctx context.Context) map[string]reactive.Binding {
	s.mu.Lock()
	defer s.mu.Unlock()
	return map[string]reactive.Binding{
		routeKey + ".12059da99926ebad": renderBlock_12059da99926ebad(ctx, &s.RouteData),
		routeKey + ".message":          renderBlock_message(ctx, &s.RouteData),
		routeKey + ".ticks":            renderBlock_ticks(ctx, &s.RouteData),
	}
}

func (s *state) Subscribe(ctx context.Context, r *web.Request, conn *reactive.Conn) error {
	return s.dp.Subscribe(ctx, r, &ReactiveState{ctx: ctx, s: s, conn: conn})
}

func (s *state) HandleWrite(ctx context.Context, r *web.Request, conn *reactive.Conn, msg reactive.WriteMsg) {
	switch msg.Var {
	case "message":
		v, err := reactive.Decode[string](msg.Value)
		if err != nil {
			conn.Reject(ctx, msg, "The value has the wrong type.", reactive.CodeDecode)
			return
		}
		if v, err = s.dp.ValidateMessage(ctx, r, v); err != nil {
			s.refuseWrite(ctx, conn, msg, "message", err)
			return
		}
		(&ReactiveState{ctx: ctx, s: s, conn: conn}).SetMessage(v)
		conn.Ack(ctx, msg)
	default:
		conn.Reject(ctx, msg, "unknown variable", reactive.CodeValidation)
	}
}

// refuseWrite answers a write that a Validate hook refused. The page shows the message of a
// web.Error; any other error is logged and the page gets a general message.
func (s *state) refuseWrite(ctx context.Context, conn *reactive.Conn, msg reactive.WriteMsg, name string, err error) {
	var he *web.HTTPError
	if errors.As(err, &he) {
		conn.Reject(ctx, msg, he.Message, reactive.CodeValidation)
		return
	}
	web.LogError(ctx, "live value refused", err, "route", routeKey, "var", name)
	conn.Reject(ctx, msg, "The value was not accepted.", reactive.CodeValidation)
}

// ReactiveState sends new values of the page's live variables to one open page. Its Set
// methods may be called from any goroutine.
type ReactiveState struct {
	ctx  context.Context
	s    *state
	conn *reactive.Conn
}

// SetMessage stores v as message and sends the parts of the page that show it.
func (rs *ReactiveState) SetMessage(v string) {
	rs.s.mu.Lock()
	defer rs.s.mu.Unlock()
	rs.s.RouteData.Message = v
	rs.conn.Enqueue(routeKey+".12059da99926ebad", renderBlock_12059da99926ebad(rs.ctx, &rs.s.RouteData))
	rs.conn.Enqueue(routeKey+".message", renderBlock_message(rs.ctx, &rs.s.RouteData))
}

// SetTicks stores v as ticks and sends the parts of the page that show it.
func (rs *ReactiveState) SetTicks(v int) {
	rs.s.mu.Lock()
	defer rs.s.mu.Unlock()
	rs.s.RouteData.Ticks = v
	rs.conn.Enqueue(routeKey+".12059da99926ebad", renderBlock_12059da99926ebad(rs.ctx, &rs.s.RouteData))
	rs.conn.Enqueue(routeKey+".ticks", renderBlock_ticks(rs.ctx, &rs.s.RouteData))
}

func (s *state) Write(w io.Writer) error {
//line index.html:1
	message := s.RouteData.Message
	_ = message
//line index.html:2
	ticks := s.RouteData.Ticks
	_ = ticks
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:4
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
	if err := render.Text(w, message); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
//line index.html:5
	if _, err := io.WriteString(w, _html3); err != nil {
		return err
	}
	if err := render.Text(w, ticks); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
//line index.html:6
	if _, err := io.WriteString(w, _html5); err != nil {
		return err
	}
	if ticks > 0 {
		if _, err := io.WriteString(w, _html6); err != nil {
			return err
		}
//line index.html:6
		if err := render.Text(w, message); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html7); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html8); err != nil {
		return err
	}
	return nil
}

func renderBlock_12059da99926ebad(ctx context.Context, data *RouteData) reactive.Binding {
	var b strings.Builder
	if err := func(w io.Writer) error {
//line index.html:1
		message := data.Message
//line index.html:2
		ticks := data.Ticks
//line index.html:6
		if ticks > 0 {
			if _, err := io.WriteString(w, _html6); err != nil {
				return err
			}
//line index.html:6
			if err := render.Text(w, message); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html7); err != nil {
				return err
			}
		}
		return nil
	}(&b); err != nil {
		web.LogError(ctx, "live block not rendered", err, "route", routeKey, "block", "12059da99926ebad")
		return reactive.HTMLBinding("")
	}
	return reactive.HTMLBinding(b.String())
}

func renderBlock_message(_ context.Context, data *RouteData) reactive.Binding {
	return reactive.TextBinding(render.Format(data.Message))
}

func renderBlock_ticks(_ context.Context, data *RouteData) reactive.Binding {
	return reactive.TextBinding(render.Format(data.Ticks))
}

const (
	_html0 = "<input id=\"message-input\" data-ssr-bind=\"ace08953.message\" data-ssr-write> <p id=\"message\">"
	_html1 = "<span data-ssr-bind=\"ace08953.message\">"
	_html2 = "</span></p> <p id=\"ticks\">"
	_html3 = "<span data-ssr-bind=\"ace08953.ticks\">"
	_html4 = "</span></p> "
	_html5 = "<ssr-block data-ssr-bind=\"ace08953.12059da99926ebad\">"
	_html6 = "<ul id=\"echo-list\"><li>"
	_html7 = "</li></ul>"
	_html8 = "</ssr-block> <p id=\"error\"></p>"
)
