// Code generated by aicoded. DO NOT EDIT.

package pages

import (
	"net/http"

	"aicoded.dev/framework/web"
)

// NewHandler returns the handler for the app's pages.
func NewHandler() http.Handler {
	return web.New(map[string]web.Route{
		"/": NewRoute(NewDP()),
	}, web.Options{Assets: assets})
}
