// Code generated by aicoded. DO NOT EDIT.

package pages

import (
	"context"
	"log/slog"

	"aicoded.dev/framework/auth"
	"aicoded.dev/framework/web"
)

// LogViewer logs the viewer from a generated file, which E-LINT-008 checks as it checks a
// hand-written one.
func LogViewer(ctx context.Context) {
	slog.InfoContext(ctx, "viewer", "subject", auth.Viewer(ctx).Subject) // leak: the viewer's identity reaches slog.InfoContext
}

// NewState returns the state of one request, as a generated page makes it for each request. The
// data providers, which the framework keeps between requests, do not share what it holds:
// flows.ShowDP records what flows.KeepDP kept, not the request read here.
func NewState() any { return &state{} }

type state struct{ q string }

// Data keeps a value of the request in the state of the request.
func (s *state) Data(_ context.Context, r *web.Request) error {
	s.q = r.FormValue("q")
	return nil
}
