// Code generated by aicoded. DO NOT EDIT.

// Package billing calls the functions of the app billing through the runner.
package billing

import (
	"context"
	"time"

	"google.golang.org/protobuf/encoding/protowire"

	frameworkrpc "aicoded.dev/framework/rpc"
	"aicoded.dev/framework/rpc/wire"
)

// Fail calls Fail of the app billing as the viewer of ctx, or as this app when ctx
// carries no viewer.
func Fail(ctx context.Context, in InvoiceID) (Invoice, error) {
	b, err := frameworkrpc.Call(ctx, "billing", "Fail", in.aicodedAppend(nil))
	if err != nil {
		return Invoice{}, err
	}
	var out Invoice
	if err := wire.Decode(b, out.aicodedDecode); err != nil {
		return Invoice{}, err
	}
	return out, nil
}

// GetInvoice calls GetInvoice of the app billing as the viewer of ctx, or as this app when ctx
// carries no viewer.
func GetInvoice(ctx context.Context, in InvoiceID) (Invoice, error) {
	b, err := frameworkrpc.Call(ctx, "billing", "GetInvoice", in.aicodedAppend(nil))
	if err != nil {
		return Invoice{}, err
	}
	var out Invoice
	if err := wire.Decode(b, out.aicodedDecode); err != nil {
		return Invoice{}, err
	}
	return out, nil
}

// Missing calls Missing of the app billing as the viewer of ctx, or as this app when ctx
// carries no viewer.
func Missing(ctx context.Context, in InvoiceID) (Invoice, error) {
	b, err := frameworkrpc.Call(ctx, "billing", "Missing", in.aicodedAppend(nil))
	if err != nil {
		return Invoice{}, err
	}
	var out Invoice
	if err := wire.Decode(b, out.aicodedDecode); err != nil {
		return Invoice{}, err
	}
	return out, nil
}

// Ping calls Ping of the app billing as the viewer of ctx, or as this app when ctx
// carries no viewer.
func Ping(ctx context.Context, in PingIn) (PingOut, error) {
	b, err := frameworkrpc.Call(ctx, "billing", "Ping", in.aicodedAppend(nil))
	if err != nil {
		return PingOut{}, err
	}
	var out PingOut
	if err := wire.Decode(b, out.aicodedDecode); err != nil {
		return PingOut{}, err
	}
	return out, nil
}

// Secret calls Secret of the app billing as the viewer of ctx, or as this app when ctx
// carries no viewer.
func Secret(ctx context.Context, in PingIn) (PingOut, error) {
	b, err := frameworkrpc.Call(ctx, "billing", "Secret", in.aicodedAppend(nil))
	if err != nil {
		return PingOut{}, err
	}
	var out PingOut
	if err := wire.Decode(b, out.aicodedDecode); err != nil {
		return PingOut{}, err
	}
	return out, nil
}

type Invoice struct {
	Customer string
	Due      time.Time
	ID       int64
	Lines    []Line
	Paid     *bool
	Viewer   string
}

func (x *Invoice) aicodedAppend(b []byte) []byte {
	if x.Customer != "" {
		b = wire.AppendString(b, 1, x.Customer)
	}
	if !x.Due.IsZero() {
		b = wire.AppendTime(b, 2, x.Due)
	}
	if x.ID != 0 {
		b = wire.AppendInt64(b, 3, x.ID)
	}
	for i := range x.Lines {
		b = wire.AppendMessage(b, 4, x.Lines[i].aicodedAppend)
	}
	if x.Paid != nil {
		b = wire.AppendBool(b, 5, *x.Paid)
	}
	if x.Viewer != "" {
		b = wire.AppendString(b, 6, x.Viewer)
	}
	return b
}

func (x *Invoice) aicodedDecode(n protowire.Number, v wire.Value) error {
	switch n {
	case 1:
		var err error
		x.Customer, err = v.String()
		return err
	case 2:
		var err error
		x.Due, err = v.Time()
		return err
	case 3:
		var err error
		x.ID, err = v.Int64()
		return err
	case 4:
		var e Line
		if err := v.Decode(e.aicodedDecode); err != nil {
			return err
		}
		x.Lines = append(x.Lines, e)
	case 5:
		e, err := v.Bool()
		if err != nil {
			return err
		}
		x.Paid = &e
	case 6:
		var err error
		x.Viewer, err = v.String()
		return err
	}
	return nil
}

type InvoiceID struct {
	ID int64
}

func (x *InvoiceID) aicodedAppend(b []byte) []byte {
	if x.ID != 0 {
		b = wire.AppendInt64(b, 1, x.ID)
	}
	return b
}

func (x *InvoiceID) aicodedDecode(n protowire.Number, v wire.Value) error {
	switch n {
	case 1:
		var err error
		x.ID, err = v.Int64()
		return err
	}
	return nil
}

type Line struct {
	Amount int64
	Item   string
}

func (x *Line) aicodedAppend(b []byte) []byte {
	if x.Amount != 0 {
		b = wire.AppendInt64(b, 1, x.Amount)
	}
	if x.Item != "" {
		b = wire.AppendString(b, 2, x.Item)
	}
	return b
}

func (x *Line) aicodedDecode(n protowire.Number, v wire.Value) error {
	switch n {
	case 1:
		var err error
		x.Amount, err = v.Int64()
		return err
	case 2:
		var err error
		x.Item, err = v.String()
		return err
	}
	return nil
}

type PingIn struct {
}

func (x *PingIn) aicodedAppend(b []byte) []byte {
	return b
}

func (x *PingIn) aicodedDecode(protowire.Number, wire.Value) error {
	return nil
}

type PingOut struct {
	Caller string
	Viewer string
}

func (x *PingOut) aicodedAppend(b []byte) []byte {
	if x.Caller != "" {
		b = wire.AppendString(b, 1, x.Caller)
	}
	if x.Viewer != "" {
		b = wire.AppendString(b, 2, x.Viewer)
	}
	return b
}

func (x *PingOut) aicodedDecode(n protowire.Number, v wire.Value) error {
	switch n {
	case 1:
		var err error
		x.Caller, err = v.String()
		return err
	case 2:
		var err error
		x.Viewer, err = v.String()
		return err
	}
	return nil
}
