// Code generated by aicoded. DO NOT EDIT.

package mcp

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "88fe637b"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Claude string
	Codex  string
	Cursor string
	Root   string
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/mcp")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:2
	claude := s.RouteData.Claude
	_ = claude
//line index.html:3
	codex := s.RouteData.Codex
	_ = codex
//line index.html:4
	cursor := s.RouteData.Cursor
	_ = cursor
//line index.html:1
	root := s.RouteData.Root
	_ = root
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:6
	if err := render.Text(w, root); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:8
	if err := render.Text(w, claude); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
//line index.html:10
	if err := render.Text(w, codex); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html3); err != nil {
		return err
	}
//line index.html:13
	if err := render.Text(w, cursor); err != nil {
		return err
	}
//line route_gen.go:108
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
	return nil
}

const (
	_html0 = "<h1>MCP setup</h1> <p>Your AI assistant builds and checks the apps of <code>"
	_html1 = "</code> through <code>aicoded mcp</code>. Set it up once in the assistant you use.</p> <h2>Claude Code</h2> <pre id=\"claude\">"
	_html2 = "</pre> <h2>Codex</h2> <pre id=\"codex\">"
	_html3 = "</pre> <h2>Cursor</h2> <p>Put this in <code>.cursor/mcp.json</code> in that folder:</p> <pre id=\"cursor\">"
	_html4 = "</pre>"
)
