// Code generated by aicoded. DO NOT EDIT.

package contacts

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "96c6ad32"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Emails []string
	Phones []string
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Guard(ctx context.Context, r *web.Request) error
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route { return &route{dp: dp} }

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"staff"}} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(ctx context.Context, r *web.Request) error { return s.dp.Guard(ctx, r) }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:3
	emails := s.RouteData.Emails
	_ = emails
//line index.html:2
	phones := s.RouteData.Phones
	_ = phones
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:5
	for _, phone := range phones {
		if _, err := io.WriteString(w, _html1); err != nil {
			return err
		}
//line index.html:5
		if err := render.Text(w, phone); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html3); err != nil {
		return err
	}
//line index.html:7
	for _, email := range emails {
		if _, err := io.WriteString(w, _html1); err != nil {
			return err
		}
//line index.html:7
		if err := render.Text(w, email); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
	return nil
}

const (
	_html0 = "<h2>Phones</h2> <ul id=\"phones\">"
	_html1 = "<li>"
	_html2 = "</li>"
	_html3 = "</ul> <h2>Emails</h2> <ul id=\"emails\">"
	_html4 = "</ul>"
)
