// Code generated by aicoded. DO NOT EDIT.

package pages

import (
	"net/http"

	"aicoded.dev/framework/web"

	"room-maintenance/deps"
	routeTickets "room-maintenance/pages/tickets"
	routeTicketsN_id "room-maintenance/pages/tickets/n_id"
	routeTicketsN_idEdit "room-maintenance/pages/tickets/n_id/edit"
	routeTicketsN_idStatus "room-maintenance/pages/tickets/n_id/status"
	routeTicketsReport "room-maintenance/pages/tickets/report"
)

// NewHandler returns the handler for the app's pages.
func NewHandler(d *deps.Deps) http.Handler {
	return web.New(map[string]web.Route{
		"/":                    NewRoute(NewDP(d)),
		"/tickets":             routeTickets.NewRoute(routeTickets.NewDP(d)),
		"/tickets/n_id":        routeTicketsN_id.NewRoute(routeTicketsN_id.NewDP(d)),
		"/tickets/n_id/edit":   routeTicketsN_idEdit.NewRoute(routeTicketsN_idEdit.NewDP(d)),
		"/tickets/n_id/status": routeTicketsN_idStatus.NewRoute(routeTicketsN_idStatus.NewDP(d)),
		"/tickets/report":      routeTicketsReport.NewRoute(routeTicketsReport.NewDP(d)),
	}, web.Options{Assets: assets})
}
