// Code generated by aicoded. DO NOT EDIT.

package status

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "ae4267a0"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Pong   string
	Secret string
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/status")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"*"}} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:2
	pong := s.RouteData.Pong
	_ = pong
//line index.html:3
	secret := s.RouteData.Secret
	_ = secret
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:4
	if err := render.Text(w, pong); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:5
	if err := render.Text(w, secret); err != nil {
		return err
	}
//line route_gen.go:86
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
	return nil
}

const (
	_html0 = "<p id=\"pong\">"
	_html1 = "</p> <pre id=\"secret\">"
	_html2 = "</pre>"
)
