// Code generated by aicoded. DO NOT EDIT.

package personas

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "7edd5483"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Personas  []Persona
	Switchers []Switcher
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/personas")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:1
	personas := s.RouteData.Personas
	_ = personas
//line index.html:2
	switchers := s.RouteData.Switchers
	_ = switchers
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:8
	for _, p := range personas {
		if _, err := io.WriteString(w, _html1); err != nil {
			return err
		}
//line index.html:8
		if err := render.Text(w, p.Name); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
//line index.html:8
		if err := render.Text(w, p.Roles); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
//line index.html:8
		if err := render.Text(w, p.Groups); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
//line index.html:14
	for _, sw := range switchers {
		if _, err := io.WriteString(w, _html5); err != nil {
			return err
		}
//line index.html:14
		if err := render.URL(w, sw.URL); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html6); err != nil {
			return err
		}
//line index.html:14
		if err := render.Text(w, sw.App); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html7); err != nil {
			return err
		}
	}
//line route_gen.go:125
	if _, err := io.WriteString(w, _html8); err != nil {
		return err
	}
	return nil
}

const (
	_html0 = "<h1>Personas</h1> <p>Each app sees you as one of these personas. They come from the personas of dev.yaml, or are the default ones when it names none.</p> <table id=\"personas\"> <thead><tr><th>Persona</th><th>Roles</th><th>Groups</th></tr></thead> <tbody> "
	_html1 = "<tr><td>"
	_html2 = "</td><td>"
	_html3 = "</td></tr>"
	_html4 = " </tbody> </table> <h2>Choose a persona</h2> <p>Choose the persona of an app on its own page:</p> <ul id=\"switchers\"> "
	_html5 = "<li><a href=\""
	_html6 = "\">"
	_html7 = "</a></li>"
	_html8 = " </ul>"
)
