// Code generated by aicoded. DO NOT EDIT.

package home

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "2cc974af"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Link string
	Page map[string]string
	Q    string
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/home")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:2
	link := s.RouteData.Link
	_ = link
//line index.html:3
	page := s.RouteData.Page
	_ = page
//line index.html:1
	q := s.RouteData.Q
	_ = q
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:5
	if err := render.Text(w, q); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:6
	if err := render.URL(w, link); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
//line index.html:7
	if err := render.URLQuery(w, q); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html3); err != nil {
		return err
	}
//line index.html:8
	if err := render.JSON(w, page); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
	return nil
}

const (
	_html0 = "<h1>Home</h1> <p id=\"echo\">"
	_html1 = "</p> <a id=\"link\" href=\""
	_html2 = "\">link</a> <a id=\"search\" href=\"/home?q="
	_html3 = "\">again</a> <script type=\"application/json\" id=\"page-data\">"
	_html4 = "</script>"
)
