// Code generated by aicoded. DO NOT EDIT.

package render

import (
	_ "embed"
	_ "os"

	_ "aicoded.dev/framework/rpc/wire"
	_ "aicoded.dev/framework/web/render"
	_ "google.golang.org/protobuf/encoding/protowire"
)
