// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: aicoded/runner/v1/files.proto

package runnerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size            int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Dir             bool                   `protobuf:"varint,3,opt,name=dir,proto3" json:"dir,omitempty"`
	ModTimeUnixNano int64                  `protobuf:"varint,4,opt,name=mod_time_unix_nano,json=modTimeUnixNano,proto3" json:"mod_time_unix_nano,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetDir() bool {
	if x != nil {
		return x.Dir
	}
	return false
}

func (x *FileInfo) GetModTimeUnixNano() int64 {
	if x != nil {
		return x.ModTimeUnixNano
	}
	return 0
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{1}
}

func (x *StatRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *StatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *FileInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{2}
}

func (x *StatResponse) GetInfo() *FileInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ReadDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirRequest) Reset() {
	*x = ReadDirRequest{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirRequest) ProtoMessage() {}

func (x *ReadDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirRequest.ProtoReflect.Descriptor instead.
func (*ReadDirRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{3}
}

func (x *ReadDirRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ReadDirRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReadDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileInfo            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirResponse) Reset() {
	*x = ReadDirResponse{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirResponse) ProtoMessage() {}

func (x *ReadDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirResponse.ProtoReflect.Descriptor instead.
func (*ReadDirResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{4}
}

func (x *ReadDirResponse) GetEntries() []*FileInfo {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{5}
}

func (x *ReadRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ReadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{6}
}

func (x *ReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteHeader) Reset() {
	*x = WriteHeader{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteHeader) ProtoMessage() {}

func (x *WriteHeader) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteHeader.ProtoReflect.Descriptor instead.
func (*WriteHeader) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{7}
}

func (x *WriteHeader) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *WriteHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Part:
	//
	//	*WriteRequest_Header
	//	*WriteRequest_Data
	Part          isWriteRequest_Part `protobuf_oneof:"part"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{8}
}

func (x *WriteRequest) GetPart() isWriteRequest_Part {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *WriteRequest) GetHeader() *WriteHeader {
	if x != nil {
		if x, ok := x.Part.(*WriteRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *WriteRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Part.(*WriteRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isWriteRequest_Part interface {
	isWriteRequest_Part()
}

type WriteRequest_Header struct {
	Header *WriteHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type WriteRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*WriteRequest_Header) isWriteRequest_Part() {}

func (*WriteRequest_Data) isWriteRequest_Part() {}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *FileInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{9}
}

func (x *WriteResponse) GetInfo() *FileInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{10}
}

func (x *MkdirRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *MkdirRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{11}
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *RemoveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{13}
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	OldName       string                 `protobuf:"bytes,2,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName       string                 `protobuf:"bytes,3,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{14}
}

func (x *RenameRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *RenameRequest) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RenameRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameResponse) Reset() {
	*x = RenameResponse{}
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResponse) ProtoMessage() {}

func (x *RenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_files_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResponse.ProtoReflect.Descriptor instead.
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_files_proto_rawDescGZIP(), []int{15}
}

var File_aicoded_runner_v1_files_proto protoreflect.FileDescriptor

const file_aicoded_runner_v1_files_proto_rawDesc = "" +
	"\n" +
	"\x1daicoded/runner/v1/files.proto\x12\x11aicoded.runner.v1\"q\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\bR\x03dir\x12+\n" +
	"\x12mod_time_unix_nano\x18\x04 \x01(\x03R\x0fmodTimeUnixNano\"7\n" +
	"\vStatRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"?\n" +
	"\fStatResponse\x12/\n" +
	"\x04info\x18\x01 \x01(\v2\x1b.aicoded.runner.v1.FileInfoR\x04info\":\n" +
	"\x0eReadDirRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"H\n" +
	"\x0fReadDirResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.aicoded.runner.v1.FileInfoR\aentries\"7\n" +
	"\vReadRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\"\n" +
	"\fReadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"7\n" +
	"\vWriteHeader\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"f\n" +
	"\fWriteRequest\x128\n" +
	"\x06header\x18\x01 \x01(\v2\x1e.aicoded.runner.v1.WriteHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x06\n" +
	"\x04part\"@\n" +
	"\rWriteResponse\x12/\n" +
	"\x04info\x18\x01 \x01(\v2\x1b.aicoded.runner.v1.FileInfoR\x04info\"8\n" +
	"\fMkdirRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x0f\n" +
	"\rMkdirResponse\"9\n" +
	"\rRemoveRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x10\n" +
	"\x0eRemoveResponse\"[\n" +
	"\rRenameRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x19\n" +
	"\bold_name\x18\x02 \x01(\tR\aoldName\x12\x19\n" +
	"\bnew_name\x18\x03 \x01(\tR\anewName\"\x10\n" +
	"\x0eRenameResponse2\xac\x04\n" +
	"\fFilesService\x12G\n" +
	"\x04Stat\x12\x1e.aicoded.runner.v1.StatRequest\x1a\x1f.aicoded.runner.v1.StatResponse\x12P\n" +
	"\aReadDir\x12!.aicoded.runner.v1.ReadDirRequest\x1a\".aicoded.runner.v1.ReadDirResponse\x12I\n" +
	"\x04Read\x12\x1e.aicoded.runner.v1.ReadRequest\x1a\x1f.aicoded.runner.v1.ReadResponse0\x01\x12L\n" +
	"\x05Write\x12\x1f.aicoded.runner.v1.WriteRequest\x1a .aicoded.runner.v1.WriteResponse(\x01\x12J\n" +
	"\x05Mkdir\x12\x1f.aicoded.runner.v1.MkdirRequest\x1a .aicoded.runner.v1.MkdirResponse\x12M\n" +
	"\x06Remove\x12 .aicoded.runner.v1.RemoveRequest\x1a!.aicoded.runner.v1.RemoveResponse\x12M\n" +
	"\x06Rename\x12 .aicoded.runner.v1.RenameRequest\x1a!.aicoded.runner.v1.RenameResponseB5Z3aicoded.dev/framework/runnerproto/runnerv1;runnerv1b\x06proto3"

var (
	file_aicoded_runner_v1_files_proto_rawDescOnce sync.Once
	file_aicoded_runner_v1_files_proto_rawDescData []byte
)

func file_aicoded_runner_v1_files_proto_rawDescGZIP() []byte {
	file_aicoded_runner_v1_files_proto_rawDescOnce.Do(func() {
		file_aicoded_runner_v1_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aicoded_runner_v1_files_proto_rawDesc), len(file_aicoded_runner_v1_files_proto_rawDesc)))
	})
	return file_aicoded_runner_v1_files_proto_rawDescData
}

var file_aicoded_runner_v1_files_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_aicoded_runner_v1_files_proto_goTypes = []any{
	(*FileInfo)(nil),        // 0: aicoded.runner.v1.FileInfo
	(*StatRequest)(nil),     // 1: aicoded.runner.v1.StatRequest
	(*StatResponse)(nil),    // 2: aicoded.runner.v1.StatResponse
	(*ReadDirRequest)(nil),  // 3: aicoded.runner.v1.ReadDirRequest
	(*ReadDirResponse)(nil), // 4: aicoded.runner.v1.ReadDirResponse
	(*ReadRequest)(nil),     // 5: aicoded.runner.v1.ReadRequest
	(*ReadResponse)(nil),    // 6: aicoded.runner.v1.ReadResponse
	(*WriteHeader)(nil),     // 7: aicoded.runner.v1.WriteHeader
	(*WriteRequest)(nil),    // 8: aicoded.runner.v1.WriteRequest
	(*WriteResponse)(nil),   // 9: aicoded.runner.v1.WriteResponse
	(*MkdirRequest)(nil),    // 10: aicoded.runner.v1.MkdirRequest
	(*MkdirResponse)(nil),   // 11: aicoded.runner.v1.MkdirResponse
	(*RemoveRequest)(nil),   // 12: aicoded.runner.v1.RemoveRequest
	(*RemoveResponse)(nil),  // 13: aicoded.runner.v1.RemoveResponse
	(*RenameRequest)(nil),   // 14: aicoded.runner.v1.RenameRequest
	(*RenameResponse)(nil),  // 15: aicoded.runner.v1.RenameResponse
}
var file_aicoded_runner_v1_files_proto_depIdxs = []int32{
	0,  // 0: aicoded.runner.v1.StatResponse.info:type_name -> aicoded.runner.v1.FileInfo
	0,  // 1: aicoded.runner.v1.ReadDirResponse.entries:type_name -> aicoded.runner.v1.FileInfo
	7,  // 2: aicoded.runner.v1.WriteRequest.header:type_name -> aicoded.runner.v1.WriteHeader
	0,  // 3: aicoded.runner.v1.WriteResponse.info:type_name -> aicoded.runner.v1.FileInfo
	1,  // 4: aicoded.runner.v1.FilesService.Stat:input_type -> aicoded.runner.v1.StatRequest
	3,  // 5: aicoded.runner.v1.FilesService.ReadDir:input_type -> aicoded.runner.v1.ReadDirRequest
	5,  // 6: aicoded.runner.v1.FilesService.Read:input_type -> aicoded.runner.v1.ReadRequest
	8,  // 7: aicoded.runner.v1.FilesService.Write:input_type -> aicoded.runner.v1.WriteRequest
	10, // 8: aicoded.runner.v1.FilesService.Mkdir:input_type -> aicoded.runner.v1.MkdirRequest
	12, // 9: aicoded.runner.v1.FilesService.Remove:input_type -> aicoded.runner.v1.RemoveRequest
	14, // 10: aicoded.runner.v1.FilesService.Rename:input_type -> aicoded.runner.v1.RenameRequest
	2,  // 11: aicoded.runner.v1.FilesService.Stat:output_type -> aicoded.runner.v1.StatResponse
	4,  // 12: aicoded.runner.v1.FilesService.ReadDir:output_type -> aicoded.runner.v1.ReadDirResponse
	6,  // 13: aicoded.runner.v1.FilesService.Read:output_type -> aicoded.runner.v1.ReadResponse
	9,  // 14: aicoded.runner.v1.FilesService.Write:output_type -> aicoded.runner.v1.WriteResponse
	11, // 15: aicoded.runner.v1.FilesService.Mkdir:output_type -> aicoded.runner.v1.MkdirResponse
	13, // 16: aicoded.runner.v1.FilesService.Remove:output_type -> aicoded.runner.v1.RemoveResponse
	15, // 17: aicoded.runner.v1.FilesService.Rename:output_type -> aicoded.runner.v1.RenameResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_aicoded_runner_v1_files_proto_init() }
func file_aicoded_runner_v1_files_proto_init() {
	if File_aicoded_runner_v1_files_proto != nil {
		return
	}
	file_aicoded_runner_v1_files_proto_msgTypes[8].OneofWrappers = []any{
		(*WriteRequest_Header)(nil),
		(*WriteRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aicoded_runner_v1_files_proto_rawDesc), len(file_aicoded_runner_v1_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aicoded_runner_v1_files_proto_goTypes,
		DependencyIndexes: file_aicoded_runner_v1_files_proto_depIdxs,
		MessageInfos:      file_aicoded_runner_v1_files_proto_msgTypes,
	}.Build()
	File_aicoded_runner_v1_files_proto = out.File
	file_aicoded_runner_v1_files_proto_goTypes = nil
	file_aicoded_runner_v1_files_proto_depIdxs = nil
}
