// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: aicoded/runner/v1/lifecycle.proto

package runnerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion  uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	FrameworkVersion string                 `protobuf:"bytes,2,opt,name=framework_version,json=frameworkVersion,proto3" json:"framework_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_aicoded_runner_v1_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HelloRequest) GetFrameworkVersion() string {
	if x != nil {
		return x.FrameworkVersion
	}
	return ""
}

type HelloResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	App     string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Env     string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	Version string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Key for signing CSRF tokens; at least 32 bytes.
	CsrfKey []byte `protobuf:"bytes,4,opt,name=csrf_key,json=csrfKey,proto3" json:"csrf_key,omitempty"`
	// Ed25519 public keys that verify viewer tokens.
	ViewerKeys [][]byte `protobuf:"bytes,5,rep,name=viewer_keys,json=viewerKeys,proto3" json:"viewer_keys,omitempty"`
	// Values of the settings declared in aicoded.yaml.
	Settings map[string]string `protobuf:"bytes,6,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Set by a runner that reaches app.sock as another user: the app then makes app.sock mode
	// 0666 right after it listens. Otherwise app.sock stays 0600.
	AppSocketOpen bool `protobuf:"varint,7,opt,name=app_socket_open,json=appSocketOpen,proto3" json:"app_socket_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_aicoded_runner_v1_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *HelloResponse) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *HelloResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelloResponse) GetCsrfKey() []byte {
	if x != nil {
		return x.CsrfKey
	}
	return nil
}

func (x *HelloResponse) GetViewerKeys() [][]byte {
	if x != nil {
		return x.ViewerKeys
	}
	return nil
}

func (x *HelloResponse) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *HelloResponse) GetAppSocketOpen() bool {
	if x != nil {
		return x.AppSocketOpen
	}
	return false
}

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_aicoded_runner_v1_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_lifecycle_proto_rawDescGZIP(), []int{2}
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_aicoded_runner_v1_lifecycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_lifecycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_lifecycle_proto_rawDescGZIP(), []int{3}
}

var File_aicoded_runner_v1_lifecycle_proto protoreflect.FileDescriptor

const file_aicoded_runner_v1_lifecycle_proto_rawDesc = "" +
	"\n" +
	"!aicoded/runner/v1/lifecycle.proto\x12\x11aicoded.runner.v1\"f\n" +
	"\fHelloRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12+\n" +
	"\x11framework_version\x18\x02 \x01(\tR\x10frameworkVersion\"\xba\x02\n" +
	"\rHelloResponse\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x19\n" +
	"\bcsrf_key\x18\x04 \x01(\fR\acsrfKey\x12\x1f\n" +
	"\vviewer_keys\x18\x05 \x03(\fR\n" +
	"viewerKeys\x12J\n" +
	"\bsettings\x18\x06 \x03(\v2..aicoded.runner.v1.HelloResponse.SettingsEntryR\bsettings\x12&\n" +
	"\x0fapp_socket_open\x18\a \x01(\bR\rappSocketOpen\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0e\n" +
	"\fReadyRequest\"\x0f\n" +
	"\rReadyResponse2\xaa\x01\n" +
	"\x10LifecycleService\x12J\n" +
	"\x05Hello\x12\x1f.aicoded.runner.v1.HelloRequest\x1a .aicoded.runner.v1.HelloResponse\x12J\n" +
	"\x05Ready\x12\x1f.aicoded.runner.v1.ReadyRequest\x1a .aicoded.runner.v1.ReadyResponseB5Z3aicoded.dev/framework/runnerproto/runnerv1;runnerv1b\x06proto3"

var (
	file_aicoded_runner_v1_lifecycle_proto_rawDescOnce sync.Once
	file_aicoded_runner_v1_lifecycle_proto_rawDescData []byte
)

func file_aicoded_runner_v1_lifecycle_proto_rawDescGZIP() []byte {
	file_aicoded_runner_v1_lifecycle_proto_rawDescOnce.Do(func() {
		file_aicoded_runner_v1_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aicoded_runner_v1_lifecycle_proto_rawDesc), len(file_aicoded_runner_v1_lifecycle_proto_rawDesc)))
	})
	return file_aicoded_runner_v1_lifecycle_proto_rawDescData
}

var file_aicoded_runner_v1_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_aicoded_runner_v1_lifecycle_proto_goTypes = []any{
	(*HelloRequest)(nil),  // 0: aicoded.runner.v1.HelloRequest
	(*HelloResponse)(nil), // 1: aicoded.runner.v1.HelloResponse
	(*ReadyRequest)(nil),  // 2: aicoded.runner.v1.ReadyRequest
	(*ReadyResponse)(nil), // 3: aicoded.runner.v1.ReadyResponse
	nil,                   // 4: aicoded.runner.v1.HelloResponse.SettingsEntry
}
var file_aicoded_runner_v1_lifecycle_proto_depIdxs = []int32{
	4, // 0: aicoded.runner.v1.HelloResponse.settings:type_name -> aicoded.runner.v1.HelloResponse.SettingsEntry
	0, // 1: aicoded.runner.v1.LifecycleService.Hello:input_type -> aicoded.runner.v1.HelloRequest
	2, // 2: aicoded.runner.v1.LifecycleService.Ready:input_type -> aicoded.runner.v1.ReadyRequest
	1, // 3: aicoded.runner.v1.LifecycleService.Hello:output_type -> aicoded.runner.v1.HelloResponse
	3, // 4: aicoded.runner.v1.LifecycleService.Ready:output_type -> aicoded.runner.v1.ReadyResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aicoded_runner_v1_lifecycle_proto_init() }
func file_aicoded_runner_v1_lifecycle_proto_init() {
	if File_aicoded_runner_v1_lifecycle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aicoded_runner_v1_lifecycle_proto_rawDesc), len(file_aicoded_runner_v1_lifecycle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aicoded_runner_v1_lifecycle_proto_goTypes,
		DependencyIndexes: file_aicoded_runner_v1_lifecycle_proto_depIdxs,
		MessageInfos:      file_aicoded_runner_v1_lifecycle_proto_msgTypes,
	}.Build()
	File_aicoded_runner_v1_lifecycle_proto = out.File
	file_aicoded_runner_v1_lifecycle_proto_goTypes = nil
	file_aicoded_runner_v1_lifecycle_proto_depIdxs = nil
}
