// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: aicoded/runner/v1/mail.proto

package runnerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_mail_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_mail_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_mail_proto_rawDescGZIP(), []int{2}
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Attachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	FromName       string                 `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	To             []*Address             `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	Cc             []*Address             `protobuf:"bytes,4,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc            []*Address             `protobuf:"bytes,5,rep,name=bcc,proto3" json:"bcc,omitempty"`
	ReplyTo        *Address               `protobuf:"bytes,6,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	Subject        string                 `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	Text           string                 `protobuf:"bytes,8,opt,name=text,proto3" json:"text,omitempty"`
	Html           string                 `protobuf:"bytes,9,opt,name=html,proto3" json:"html,omitempty"`
	Attachments    []*Attachment          `protobuf:"bytes,10,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Headers        []*Header              `protobuf:"bytes,11,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_mail_proto_rawDescGZIP(), []int{3}
}

func (x *SendRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SendRequest) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *SendRequest) GetTo() []*Address {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendRequest) GetCc() []*Address {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *SendRequest) GetBcc() []*Address {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *SendRequest) GetReplyTo() *Address {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

func (x *SendRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendRequest) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *SendRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_mail_proto_rawDescGZIP(), []int{4}
}

func (x *SendResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From          *Address               `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            []*Address             `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	DateUnix      int64                  `protobuf:"varint,5,opt,name=date_unix,json=dateUnix,proto3" json:"date_unix,omitempty"`
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Folder        string                 `protobuf:"bytes,7,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSummary) Reset() {
	*x = MessageSummary{}
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSummary) ProtoMessage() {}

func (x *MessageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSummary.ProtoReflect.Descriptor instead.
func (*MessageSummary) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_mail_proto_rawDescGZIP(), []int{5}
}

func (x *MessageSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageSummary) GetFrom() *Address {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *MessageSummary) GetTo() []*Address {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *MessageSummary) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MessageSummary) GetDateUnix() int64 {
	if x != nil {
		return x.DateUnix
	}
	return 0
}

func (x *MessageSummary) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MessageSummary) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

// ListRequest asks for one page of a folder, newest first. An offset below 0 means 0. A limit of
// 0 or less means 50 and a limit above 100 means 100 (mailrules.DefaultList and MaxList).
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        string                 `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_mail_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *ListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageSummary      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_mail_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetMessages() []*MessageSummary {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_mail_proto_rawDescGZIP(), []int{8}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *MessageSummary        `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Cc            []*Address             `protobuf:"bytes,2,rep,name=cc,proto3" json:"cc,omitempty"`
	ReplyTo       *Address               `protobuf:"bytes,3,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Html          string                 `protobuf:"bytes,5,opt,name=html,proto3" json:"html,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,6,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Headers       []*Header              `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty"`
	Bcc           []*Address             `protobuf:"bytes,8,rep,name=bcc,proto3" json:"bcc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_mail_proto_rawDescGZIP(), []int{9}
}

func (x *GetResponse) GetSummary() *MessageSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetResponse) GetCc() []*Address {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *GetResponse) GetReplyTo() *Address {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

func (x *GetResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GetResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *GetResponse) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *GetResponse) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *GetResponse) GetBcc() []*Address {
	if x != nil {
		return x.Bcc
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_mail_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_mail_proto_rawDescGZIP(), []int{11}
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Folder        string                 `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_mail_proto_rawDescGZIP(), []int{12}
}

func (x *MoveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MoveRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_mail_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_mail_proto_rawDescGZIP(), []int{13}
}

var File_aicoded_runner_v1_mail_proto protoreflect.FileDescriptor

const file_aicoded_runner_v1_mail_proto_rawDesc = "" +
	"\n" +
	"\x1caicoded/runner/v1/mail.proto\x12\x11aicoded.runner.v1\"7\n" +
	"\aAddress\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"2\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"_\n" +
	"\n" +
	"Attachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xc8\x03\n" +
	"\vSendRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x1b\n" +
	"\tfrom_name\x18\x02 \x01(\tR\bfromName\x12*\n" +
	"\x02to\x18\x03 \x03(\v2\x1a.aicoded.runner.v1.AddressR\x02to\x12*\n" +
	"\x02cc\x18\x04 \x03(\v2\x1a.aicoded.runner.v1.AddressR\x02cc\x12,\n" +
	"\x03bcc\x18\x05 \x03(\v2\x1a.aicoded.runner.v1.AddressR\x03bcc\x125\n" +
	"\breply_to\x18\x06 \x01(\v2\x1a.aicoded.runner.v1.AddressR\areplyTo\x12\x18\n" +
	"\asubject\x18\a \x01(\tR\asubject\x12\x12\n" +
	"\x04text\x18\b \x01(\tR\x04text\x12\x12\n" +
	"\x04html\x18\t \x01(\tR\x04html\x12?\n" +
	"\vattachments\x18\n" +
	" \x03(\v2\x1d.aicoded.runner.v1.AttachmentR\vattachments\x123\n" +
	"\aheaders\x18\v \x03(\v2\x19.aicoded.runner.v1.HeaderR\aheaders\"\x1e\n" +
	"\fSendResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xdf\x01\n" +
	"\x0eMessageSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.aicoded.runner.v1.AddressR\x04from\x12*\n" +
	"\x02to\x18\x03 \x03(\v2\x1a.aicoded.runner.v1.AddressR\x02to\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x1b\n" +
	"\tdate_unix\x18\x05 \x01(\x03R\bdateUnix\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x16\n" +
	"\x06folder\x18\a \x01(\tR\x06folder\"S\n" +
	"\vListRequest\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"c\n" +
	"\fListResponse\x12=\n" +
	"\bmessages\x18\x01 \x03(\v2!.aicoded.runner.v1.MessageSummaryR\bmessages\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xf9\x02\n" +
	"\vGetResponse\x12;\n" +
	"\asummary\x18\x01 \x01(\v2!.aicoded.runner.v1.MessageSummaryR\asummary\x12*\n" +
	"\x02cc\x18\x02 \x03(\v2\x1a.aicoded.runner.v1.AddressR\x02cc\x125\n" +
	"\breply_to\x18\x03 \x01(\v2\x1a.aicoded.runner.v1.AddressR\areplyTo\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x12\n" +
	"\x04html\x18\x05 \x01(\tR\x04html\x12?\n" +
	"\vattachments\x18\x06 \x03(\v2\x1d.aicoded.runner.v1.AttachmentR\vattachments\x123\n" +
	"\aheaders\x18\a \x03(\v2\x19.aicoded.runner.v1.HeaderR\aheaders\x12,\n" +
	"\x03bcc\x18\b \x03(\v2\x1a.aicoded.runner.v1.AddressR\x03bcc\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eDeleteResponse\"5\n" +
	"\vMoveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06folder\x18\x02 \x01(\tR\x06folder\"\x0e\n" +
	"\fMoveResponse2\xfd\x02\n" +
	"\vMailService\x12G\n" +
	"\x04Send\x12\x1e.aicoded.runner.v1.SendRequest\x1a\x1f.aicoded.runner.v1.SendResponse\x12G\n" +
	"\x04List\x12\x1e.aicoded.runner.v1.ListRequest\x1a\x1f.aicoded.runner.v1.ListResponse\x12D\n" +
	"\x03Get\x12\x1d.aicoded.runner.v1.GetRequest\x1a\x1e.aicoded.runner.v1.GetResponse\x12M\n" +
	"\x06Delete\x12 .aicoded.runner.v1.DeleteRequest\x1a!.aicoded.runner.v1.DeleteResponse\x12G\n" +
	"\x04Move\x12\x1e.aicoded.runner.v1.MoveRequest\x1a\x1f.aicoded.runner.v1.MoveResponseB5Z3aicoded.dev/framework/runnerproto/runnerv1;runnerv1b\x06proto3"

var (
	file_aicoded_runner_v1_mail_proto_rawDescOnce sync.Once
	file_aicoded_runner_v1_mail_proto_rawDescData []byte
)

func file_aicoded_runner_v1_mail_proto_rawDescGZIP() []byte {
	file_aicoded_runner_v1_mail_proto_rawDescOnce.Do(func() {
		file_aicoded_runner_v1_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aicoded_runner_v1_mail_proto_rawDesc), len(file_aicoded_runner_v1_mail_proto_rawDesc)))
	})
	return file_aicoded_runner_v1_mail_proto_rawDescData
}

var file_aicoded_runner_v1_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_aicoded_runner_v1_mail_proto_goTypes = []any{
	(*Address)(nil),        // 0: aicoded.runner.v1.Address
	(*Header)(nil),         // 1: aicoded.runner.v1.Header
	(*Attachment)(nil),     // 2: aicoded.runner.v1.Attachment
	(*SendRequest)(nil),    // 3: aicoded.runner.v1.SendRequest
	(*SendResponse)(nil),   // 4: aicoded.runner.v1.SendResponse
	(*MessageSummary)(nil), // 5: aicoded.runner.v1.MessageSummary
	(*ListRequest)(nil),    // 6: aicoded.runner.v1.ListRequest
	(*ListResponse)(nil),   // 7: aicoded.runner.v1.ListResponse
	(*GetRequest)(nil),     // 8: aicoded.runner.v1.GetRequest
	(*GetResponse)(nil),    // 9: aicoded.runner.v1.GetResponse
	(*DeleteRequest)(nil),  // 10: aicoded.runner.v1.DeleteRequest
	(*DeleteResponse)(nil), // 11: aicoded.runner.v1.DeleteResponse
	(*MoveRequest)(nil),    // 12: aicoded.runner.v1.MoveRequest
	(*MoveResponse)(nil),   // 13: aicoded.runner.v1.MoveResponse
}
var file_aicoded_runner_v1_mail_proto_depIdxs = []int32{
	0,  // 0: aicoded.runner.v1.SendRequest.to:type_name -> aicoded.runner.v1.Address
	0,  // 1: aicoded.runner.v1.SendRequest.cc:type_name -> aicoded.runner.v1.Address
	0,  // 2: aicoded.runner.v1.SendRequest.bcc:type_name -> aicoded.runner.v1.Address
	0,  // 3: aicoded.runner.v1.SendRequest.reply_to:type_name -> aicoded.runner.v1.Address
	2,  // 4: aicoded.runner.v1.SendRequest.attachments:type_name -> aicoded.runner.v1.Attachment
	1,  // 5: aicoded.runner.v1.SendRequest.headers:type_name -> aicoded.runner.v1.Header
	0,  // 6: aicoded.runner.v1.MessageSummary.from:type_name -> aicoded.runner.v1.Address
	0,  // 7: aicoded.runner.v1.MessageSummary.to:type_name -> aicoded.runner.v1.Address
	5,  // 8: aicoded.runner.v1.ListResponse.messages:type_name -> aicoded.runner.v1.MessageSummary
	5,  // 9: aicoded.runner.v1.GetResponse.summary:type_name -> aicoded.runner.v1.MessageSummary
	0,  // 10: aicoded.runner.v1.GetResponse.cc:type_name -> aicoded.runner.v1.Address
	0,  // 11: aicoded.runner.v1.GetResponse.reply_to:type_name -> aicoded.runner.v1.Address
	2,  // 12: aicoded.runner.v1.GetResponse.attachments:type_name -> aicoded.runner.v1.Attachment
	1,  // 13: aicoded.runner.v1.GetResponse.headers:type_name -> aicoded.runner.v1.Header
	0,  // 14: aicoded.runner.v1.GetResponse.bcc:type_name -> aicoded.runner.v1.Address
	3,  // 15: aicoded.runner.v1.MailService.Send:input_type -> aicoded.runner.v1.SendRequest
	6,  // 16: aicoded.runner.v1.MailService.List:input_type -> aicoded.runner.v1.ListRequest
	8,  // 17: aicoded.runner.v1.MailService.Get:input_type -> aicoded.runner.v1.GetRequest
	10, // 18: aicoded.runner.v1.MailService.Delete:input_type -> aicoded.runner.v1.DeleteRequest
	12, // 19: aicoded.runner.v1.MailService.Move:input_type -> aicoded.runner.v1.MoveRequest
	4,  // 20: aicoded.runner.v1.MailService.Send:output_type -> aicoded.runner.v1.SendResponse
	7,  // 21: aicoded.runner.v1.MailService.List:output_type -> aicoded.runner.v1.ListResponse
	9,  // 22: aicoded.runner.v1.MailService.Get:output_type -> aicoded.runner.v1.GetResponse
	11, // 23: aicoded.runner.v1.MailService.Delete:output_type -> aicoded.runner.v1.DeleteResponse
	13, // 24: aicoded.runner.v1.MailService.Move:output_type -> aicoded.runner.v1.MoveResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_aicoded_runner_v1_mail_proto_init() }
func file_aicoded_runner_v1_mail_proto_init() {
	if File_aicoded_runner_v1_mail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aicoded_runner_v1_mail_proto_rawDesc), len(file_aicoded_runner_v1_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aicoded_runner_v1_mail_proto_goTypes,
		DependencyIndexes: file_aicoded_runner_v1_mail_proto_depIdxs,
		MessageInfos:      file_aicoded_runner_v1_mail_proto_msgTypes,
	}.Build()
	File_aicoded_runner_v1_mail_proto = out.File
	file_aicoded_runner_v1_mail_proto_goTypes = nil
	file_aicoded_runner_v1_mail_proto_depIdxs = nil
}
