// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: aicoded/runner/v1/rpc.proto

package runnerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The callee app.
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// The callee's function.
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// The function's input, encoded as the callee's schema snapshot says.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// The viewer token of the request the call is made for; empty for a call the app makes as
	// itself.
	Viewer        string `protobuf:"bytes,4,opt,name=viewer,proto3" json:"viewer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_aicoded_runner_v1_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *CallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CallRequest) GetViewer() string {
	if x != nil {
		return x.Viewer
	}
	return ""
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_aicoded_runner_v1_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ServeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeRequest) Reset() {
	*x = ServeRequest{}
	mi := &file_aicoded_runner_v1_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeRequest) ProtoMessage() {}

func (x *ServeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeRequest.ProtoReflect.Descriptor instead.
func (*ServeRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ServeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ServeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ServeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeResponse) Reset() {
	*x = ServeResponse{}
	mi := &file_aicoded_runner_v1_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeResponse) ProtoMessage() {}

func (x *ServeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeResponse.ProtoReflect.Descriptor instead.
func (*ServeResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ServeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_aicoded_runner_v1_rpc_proto protoreflect.FileDescriptor

const file_aicoded_runner_v1_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1baicoded/runner/v1/rpc.proto\x12\x11aicoded.runner.v1\"i\n" +
	"\vCallRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x16\n" +
	"\x06viewer\x18\x04 \x01(\tR\x06viewer\"(\n" +
	"\fCallResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"@\n" +
	"\fServeRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\")\n" +
	"\rServeResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload2U\n" +
	"\n" +
	"RpcService\x12G\n" +
	"\x04Call\x12\x1e.aicoded.runner.v1.CallRequest\x1a\x1f.aicoded.runner.v1.CallResponse2X\n" +
	"\n" +
	"AppService\x12J\n" +
	"\x05Serve\x12\x1f.aicoded.runner.v1.ServeRequest\x1a .aicoded.runner.v1.ServeResponseB5Z3aicoded.dev/framework/runnerproto/runnerv1;runnerv1b\x06proto3"

var (
	file_aicoded_runner_v1_rpc_proto_rawDescOnce sync.Once
	file_aicoded_runner_v1_rpc_proto_rawDescData []byte
)

func file_aicoded_runner_v1_rpc_proto_rawDescGZIP() []byte {
	file_aicoded_runner_v1_rpc_proto_rawDescOnce.Do(func() {
		file_aicoded_runner_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aicoded_runner_v1_rpc_proto_rawDesc), len(file_aicoded_runner_v1_rpc_proto_rawDesc)))
	})
	return file_aicoded_runner_v1_rpc_proto_rawDescData
}

var file_aicoded_runner_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aicoded_runner_v1_rpc_proto_goTypes = []any{
	(*CallRequest)(nil),   // 0: aicoded.runner.v1.CallRequest
	(*CallResponse)(nil),  // 1: aicoded.runner.v1.CallResponse
	(*ServeRequest)(nil),  // 2: aicoded.runner.v1.ServeRequest
	(*ServeResponse)(nil), // 3: aicoded.runner.v1.ServeResponse
}
var file_aicoded_runner_v1_rpc_proto_depIdxs = []int32{
	0, // 0: aicoded.runner.v1.RpcService.Call:input_type -> aicoded.runner.v1.CallRequest
	2, // 1: aicoded.runner.v1.AppService.Serve:input_type -> aicoded.runner.v1.ServeRequest
	1, // 2: aicoded.runner.v1.RpcService.Call:output_type -> aicoded.runner.v1.CallResponse
	3, // 3: aicoded.runner.v1.AppService.Serve:output_type -> aicoded.runner.v1.ServeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aicoded_runner_v1_rpc_proto_init() }
func file_aicoded_runner_v1_rpc_proto_init() {
	if File_aicoded_runner_v1_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aicoded_runner_v1_rpc_proto_rawDesc), len(file_aicoded_runner_v1_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_aicoded_runner_v1_rpc_proto_goTypes,
		DependencyIndexes: file_aicoded_runner_v1_rpc_proto_depIdxs,
		MessageInfos:      file_aicoded_runner_v1_rpc_proto_msgTypes,
	}.Build()
	File_aicoded_runner_v1_rpc_proto = out.File
	file_aicoded_runner_v1_rpc_proto_goTypes = nil
	file_aicoded_runner_v1_rpc_proto_depIdxs = nil
}
