// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: aicoded/runner/v1/telemetry.proto

package runnerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        []byte                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId  []byte                 `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	StartUnixNano int64                  `protobuf:"varint,5,opt,name=start_unix_nano,json=startUnixNano,proto3" json:"start_unix_nano,omitempty"`
	EndUnixNano   int64                  `protobuf:"varint,6,opt,name=end_unix_nano,json=endUnixNano,proto3" json:"end_unix_nano,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_aicoded_runner_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Span) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *Span) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *Span) GetParentSpanId() []byte {
	if x != nil {
		return x.ParentSpanId
	}
	return nil
}

func (x *Span) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Span) GetStartUnixNano() int64 {
	if x != nil {
		return x.StartUnixNano
	}
	return 0
}

func (x *Span) GetEndUnixNano() int64 {
	if x != nil {
		return x.EndUnixNano
	}
	return 0
}

func (x *Span) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Span) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Spans []*Span                `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	// Spans the app dropped since the previous export.
	Dropped       uint64 `protobuf:"varint,2,opt,name=dropped,proto3" json:"dropped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_aicoded_runner_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *ExportRequest) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *ExportRequest) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_aicoded_runner_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aicoded_runner_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_aicoded_runner_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

var File_aicoded_runner_v1_telemetry_proto protoreflect.FileDescriptor

const file_aicoded_runner_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"!aicoded/runner/v1/telemetry.proto\x12\x11aicoded.runner.v1\"\xde\x02\n" +
	"\x04Span\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\fR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x03 \x01(\fR\fparentSpanId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12&\n" +
	"\x0fstart_unix_nano\x18\x05 \x01(\x03R\rstartUnixNano\x12\"\n" +
	"\rend_unix_nano\x18\x06 \x01(\x03R\vendUnixNano\x12G\n" +
	"\n" +
	"attributes\x18\a \x03(\v2'.aicoded.runner.v1.Span.AttributesEntryR\n" +
	"attributes\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\rExportRequest\x12-\n" +
	"\x05spans\x18\x01 \x03(\v2\x17.aicoded.runner.v1.SpanR\x05spans\x12\x18\n" +
	"\adropped\x18\x02 \x01(\x04R\adropped\"\x10\n" +
	"\x0eExportResponse2a\n" +
	"\x10TelemetryService\x12M\n" +
	"\x06Export\x12 .aicoded.runner.v1.ExportRequest\x1a!.aicoded.runner.v1.ExportResponseB5Z3aicoded.dev/framework/runnerproto/runnerv1;runnerv1b\x06proto3"

var (
	file_aicoded_runner_v1_telemetry_proto_rawDescOnce sync.Once
	file_aicoded_runner_v1_telemetry_proto_rawDescData []byte
)

func file_aicoded_runner_v1_telemetry_proto_rawDescGZIP() []byte {
	file_aicoded_runner_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_aicoded_runner_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aicoded_runner_v1_telemetry_proto_rawDesc), len(file_aicoded_runner_v1_telemetry_proto_rawDesc)))
	})
	return file_aicoded_runner_v1_telemetry_proto_rawDescData
}

var file_aicoded_runner_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aicoded_runner_v1_telemetry_proto_goTypes = []any{
	(*Span)(nil),           // 0: aicoded.runner.v1.Span
	(*ExportRequest)(nil),  // 1: aicoded.runner.v1.ExportRequest
	(*ExportResponse)(nil), // 2: aicoded.runner.v1.ExportResponse
	nil,                    // 3: aicoded.runner.v1.Span.AttributesEntry
}
var file_aicoded_runner_v1_telemetry_proto_depIdxs = []int32{
	3, // 0: aicoded.runner.v1.Span.attributes:type_name -> aicoded.runner.v1.Span.AttributesEntry
	0, // 1: aicoded.runner.v1.ExportRequest.spans:type_name -> aicoded.runner.v1.Span
	1, // 2: aicoded.runner.v1.TelemetryService.Export:input_type -> aicoded.runner.v1.ExportRequest
	2, // 3: aicoded.runner.v1.TelemetryService.Export:output_type -> aicoded.runner.v1.ExportResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_aicoded_runner_v1_telemetry_proto_init() }
func file_aicoded_runner_v1_telemetry_proto_init() {
	if File_aicoded_runner_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aicoded_runner_v1_telemetry_proto_rawDesc), len(file_aicoded_runner_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aicoded_runner_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_aicoded_runner_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_aicoded_runner_v1_telemetry_proto_msgTypes,
	}.Build()
	File_aicoded_runner_v1_telemetry_proto = out.File
	file_aicoded_runner_v1_telemetry_proto_goTypes = nil
	file_aicoded_runner_v1_telemetry_proto_depIdxs = nil
}
