// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aicoded/runner/v1/files.proto

package runnerv1connect

import (
	runnerv1 "aicoded.dev/framework/runnerproto/runnerv1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FilesServiceName is the fully-qualified name of the FilesService service.
	FilesServiceName = "aicoded.runner.v1.FilesService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FilesServiceStatProcedure is the fully-qualified name of the FilesService's Stat RPC.
	FilesServiceStatProcedure = "/aicoded.runner.v1.FilesService/Stat"
	// FilesServiceReadDirProcedure is the fully-qualified name of the FilesService's ReadDir RPC.
	FilesServiceReadDirProcedure = "/aicoded.runner.v1.FilesService/ReadDir"
	// FilesServiceReadProcedure is the fully-qualified name of the FilesService's Read RPC.
	FilesServiceReadProcedure = "/aicoded.runner.v1.FilesService/Read"
	// FilesServiceWriteProcedure is the fully-qualified name of the FilesService's Write RPC.
	FilesServiceWriteProcedure = "/aicoded.runner.v1.FilesService/Write"
	// FilesServiceMkdirProcedure is the fully-qualified name of the FilesService's Mkdir RPC.
	FilesServiceMkdirProcedure = "/aicoded.runner.v1.FilesService/Mkdir"
	// FilesServiceRemoveProcedure is the fully-qualified name of the FilesService's Remove RPC.
	FilesServiceRemoveProcedure = "/aicoded.runner.v1.FilesService/Remove"
	// FilesServiceRenameProcedure is the fully-qualified name of the FilesService's Rename RPC.
	FilesServiceRenameProcedure = "/aicoded.runner.v1.FilesService/Rename"
)

// FilesServiceClient is a client for the aicoded.runner.v1.FilesService service.
type FilesServiceClient interface {
	Stat(context.Context, *connect.Request[runnerv1.StatRequest]) (*connect.Response[runnerv1.StatResponse], error)
	// ReadDir lists a folder. On a file it is FAILED_PRECONDITION.
	ReadDir(context.Context, *connect.Request[runnerv1.ReadDirRequest]) (*connect.Response[runnerv1.ReadDirResponse], error)
	// Read streams the content of a file. On a folder it is FAILED_PRECONDITION.
	Read(context.Context, *connect.Request[runnerv1.ReadRequest]) (*connect.ServerStreamForClient[runnerv1.ReadResponse], error)
	// Write takes the header first and then the content. It creates the file, or replaces an
	// existing file of that name, only when the stream ends without error; until then, and after
	// an error, the store is unchanged.
	Write(context.Context) *connect.ClientStreamForClient[runnerv1.WriteRequest, runnerv1.WriteResponse]
	// Mkdir creates a folder and any missing parents. A folder that exists already is not an error.
	Mkdir(context.Context, *connect.Request[runnerv1.MkdirRequest]) (*connect.Response[runnerv1.MkdirResponse], error)
	// Remove removes a file or an empty folder.
	Remove(context.Context, *connect.Request[runnerv1.RemoveRequest]) (*connect.Response[runnerv1.RemoveResponse], error)
	// Rename moves a file or folder to new_name. An existing file at new_name is replaced; a folder
	// at new_name is never replaced, even an empty one.
	Rename(context.Context, *connect.Request[runnerv1.RenameRequest]) (*connect.Response[runnerv1.RenameResponse], error)
}

// NewFilesServiceClient constructs a client for the aicoded.runner.v1.FilesService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFilesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FilesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	filesServiceMethods := runnerv1.File_aicoded_runner_v1_files_proto.Services().ByName("FilesService").Methods()
	return &filesServiceClient{
		stat: connect.NewClient[runnerv1.StatRequest, runnerv1.StatResponse](
			httpClient,
			baseURL+FilesServiceStatProcedure,
			connect.WithSchema(filesServiceMethods.ByName("Stat")),
			connect.WithClientOptions(opts...),
		),
		readDir: connect.NewClient[runnerv1.ReadDirRequest, runnerv1.ReadDirResponse](
			httpClient,
			baseURL+FilesServiceReadDirProcedure,
			connect.WithSchema(filesServiceMethods.ByName("ReadDir")),
			connect.WithClientOptions(opts...),
		),
		read: connect.NewClient[runnerv1.ReadRequest, runnerv1.ReadResponse](
			httpClient,
			baseURL+FilesServiceReadProcedure,
			connect.WithSchema(filesServiceMethods.ByName("Read")),
			connect.WithClientOptions(opts...),
		),
		write: connect.NewClient[runnerv1.WriteRequest, runnerv1.WriteResponse](
			httpClient,
			baseURL+FilesServiceWriteProcedure,
			connect.WithSchema(filesServiceMethods.ByName("Write")),
			connect.WithClientOptions(opts...),
		),
		mkdir: connect.NewClient[runnerv1.MkdirRequest, runnerv1.MkdirResponse](
			httpClient,
			baseURL+FilesServiceMkdirProcedure,
			connect.WithSchema(filesServiceMethods.ByName("Mkdir")),
			connect.WithClientOptions(opts...),
		),
		remove: connect.NewClient[runnerv1.RemoveRequest, runnerv1.RemoveResponse](
			httpClient,
			baseURL+FilesServiceRemoveProcedure,
			connect.WithSchema(filesServiceMethods.ByName("Remove")),
			connect.WithClientOptions(opts...),
		),
		rename: connect.NewClient[runnerv1.RenameRequest, runnerv1.RenameResponse](
			httpClient,
			baseURL+FilesServiceRenameProcedure,
			connect.WithSchema(filesServiceMethods.ByName("Rename")),
			connect.WithClientOptions(opts...),
		),
	}
}

// filesServiceClient implements FilesServiceClient.
type filesServiceClient struct {
	stat    *connect.Client[runnerv1.StatRequest, runnerv1.StatResponse]
	readDir *connect.Client[runnerv1.ReadDirRequest, runnerv1.ReadDirResponse]
	read    *connect.Client[runnerv1.ReadRequest, runnerv1.ReadResponse]
	write   *connect.Client[runnerv1.WriteRequest, runnerv1.WriteResponse]
	mkdir   *connect.Client[runnerv1.MkdirRequest, runnerv1.MkdirResponse]
	remove  *connect.Client[runnerv1.RemoveRequest, runnerv1.RemoveResponse]
	rename  *connect.Client[runnerv1.RenameRequest, runnerv1.RenameResponse]
}

// Stat calls aicoded.runner.v1.FilesService.Stat.
func (c *filesServiceClient) Stat(ctx context.Context, req *connect.Request[runnerv1.StatRequest]) (*connect.Response[runnerv1.StatResponse], error) {
	return c.stat.CallUnary(ctx, req)
}

// ReadDir calls aicoded.runner.v1.FilesService.ReadDir.
func (c *filesServiceClient) ReadDir(ctx context.Context, req *connect.Request[runnerv1.ReadDirRequest]) (*connect.Response[runnerv1.ReadDirResponse], error) {
	return c.readDir.CallUnary(ctx, req)
}

// Read calls aicoded.runner.v1.FilesService.Read.
func (c *filesServiceClient) Read(ctx context.Context, req *connect.Request[runnerv1.ReadRequest]) (*connect.ServerStreamForClient[runnerv1.ReadResponse], error) {
	return c.read.CallServerStream(ctx, req)
}

// Write calls aicoded.runner.v1.FilesService.Write.
func (c *filesServiceClient) Write(ctx context.Context) *connect.ClientStreamForClient[runnerv1.WriteRequest, runnerv1.WriteResponse] {
	return c.write.CallClientStream(ctx)
}

// Mkdir calls aicoded.runner.v1.FilesService.Mkdir.
func (c *filesServiceClient) Mkdir(ctx context.Context, req *connect.Request[runnerv1.MkdirRequest]) (*connect.Response[runnerv1.MkdirResponse], error) {
	return c.mkdir.CallUnary(ctx, req)
}

// Remove calls aicoded.runner.v1.FilesService.Remove.
func (c *filesServiceClient) Remove(ctx context.Context, req *connect.Request[runnerv1.RemoveRequest]) (*connect.Response[runnerv1.RemoveResponse], error) {
	return c.remove.CallUnary(ctx, req)
}

// Rename calls aicoded.runner.v1.FilesService.Rename.
func (c *filesServiceClient) Rename(ctx context.Context, req *connect.Request[runnerv1.RenameRequest]) (*connect.Response[runnerv1.RenameResponse], error) {
	return c.rename.CallUnary(ctx, req)
}

// FilesServiceHandler is an implementation of the aicoded.runner.v1.FilesService service.
type FilesServiceHandler interface {
	Stat(context.Context, *connect.Request[runnerv1.StatRequest]) (*connect.Response[runnerv1.StatResponse], error)
	// ReadDir lists a folder. On a file it is FAILED_PRECONDITION.
	ReadDir(context.Context, *connect.Request[runnerv1.ReadDirRequest]) (*connect.Response[runnerv1.ReadDirResponse], error)
	// Read streams the content of a file. On a folder it is FAILED_PRECONDITION.
	Read(context.Context, *connect.Request[runnerv1.ReadRequest], *connect.ServerStream[runnerv1.ReadResponse]) error
	// Write takes the header first and then the content. It creates the file, or replaces an
	// existing file of that name, only when the stream ends without error; until then, and after
	// an error, the store is unchanged.
	Write(context.Context, *connect.ClientStream[runnerv1.WriteRequest]) (*connect.Response[runnerv1.WriteResponse], error)
	// Mkdir creates a folder and any missing parents. A folder that exists already is not an error.
	Mkdir(context.Context, *connect.Request[runnerv1.MkdirRequest]) (*connect.Response[runnerv1.MkdirResponse], error)
	// Remove removes a file or an empty folder.
	Remove(context.Context, *connect.Request[runnerv1.RemoveRequest]) (*connect.Response[runnerv1.RemoveResponse], error)
	// Rename moves a file or folder to new_name. An existing file at new_name is replaced; a folder
	// at new_name is never replaced, even an empty one.
	Rename(context.Context, *connect.Request[runnerv1.RenameRequest]) (*connect.Response[runnerv1.RenameResponse], error)
}

// NewFilesServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFilesServiceHandler(svc FilesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	filesServiceMethods := runnerv1.File_aicoded_runner_v1_files_proto.Services().ByName("FilesService").Methods()
	filesServiceStatHandler := connect.NewUnaryHandler(
		FilesServiceStatProcedure,
		svc.Stat,
		connect.WithSchema(filesServiceMethods.ByName("Stat")),
		connect.WithHandlerOptions(opts...),
	)
	filesServiceReadDirHandler := connect.NewUnaryHandler(
		FilesServiceReadDirProcedure,
		svc.ReadDir,
		connect.WithSchema(filesServiceMethods.ByName("ReadDir")),
		connect.WithHandlerOptions(opts...),
	)
	filesServiceReadHandler := connect.NewServerStreamHandler(
		FilesServiceReadProcedure,
		svc.Read,
		connect.WithSchema(filesServiceMethods.ByName("Read")),
		connect.WithHandlerOptions(opts...),
	)
	filesServiceWriteHandler := connect.NewClientStreamHandler(
		FilesServiceWriteProcedure,
		svc.Write,
		connect.WithSchema(filesServiceMethods.ByName("Write")),
		connect.WithHandlerOptions(opts...),
	)
	filesServiceMkdirHandler := connect.NewUnaryHandler(
		FilesServiceMkdirProcedure,
		svc.Mkdir,
		connect.WithSchema(filesServiceMethods.ByName("Mkdir")),
		connect.WithHandlerOptions(opts...),
	)
	filesServiceRemoveHandler := connect.NewUnaryHandler(
		FilesServiceRemoveProcedure,
		svc.Remove,
		connect.WithSchema(filesServiceMethods.ByName("Remove")),
		connect.WithHandlerOptions(opts...),
	)
	filesServiceRenameHandler := connect.NewUnaryHandler(
		FilesServiceRenameProcedure,
		svc.Rename,
		connect.WithSchema(filesServiceMethods.ByName("Rename")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aicoded.runner.v1.FilesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FilesServiceStatProcedure:
			filesServiceStatHandler.ServeHTTP(w, r)
		case FilesServiceReadDirProcedure:
			filesServiceReadDirHandler.ServeHTTP(w, r)
		case FilesServiceReadProcedure:
			filesServiceReadHandler.ServeHTTP(w, r)
		case FilesServiceWriteProcedure:
			filesServiceWriteHandler.ServeHTTP(w, r)
		case FilesServiceMkdirProcedure:
			filesServiceMkdirHandler.ServeHTTP(w, r)
		case FilesServiceRemoveProcedure:
			filesServiceRemoveHandler.ServeHTTP(w, r)
		case FilesServiceRenameProcedure:
			filesServiceRenameHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFilesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFilesServiceHandler struct{}

func (UnimplementedFilesServiceHandler) Stat(context.Context, *connect.Request[runnerv1.StatRequest]) (*connect.Response[runnerv1.StatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.FilesService.Stat is not implemented"))
}

func (UnimplementedFilesServiceHandler) ReadDir(context.Context, *connect.Request[runnerv1.ReadDirRequest]) (*connect.Response[runnerv1.ReadDirResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.FilesService.ReadDir is not implemented"))
}

func (UnimplementedFilesServiceHandler) Read(context.Context, *connect.Request[runnerv1.ReadRequest], *connect.ServerStream[runnerv1.ReadResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.FilesService.Read is not implemented"))
}

func (UnimplementedFilesServiceHandler) Write(context.Context, *connect.ClientStream[runnerv1.WriteRequest]) (*connect.Response[runnerv1.WriteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.FilesService.Write is not implemented"))
}

func (UnimplementedFilesServiceHandler) Mkdir(context.Context, *connect.Request[runnerv1.MkdirRequest]) (*connect.Response[runnerv1.MkdirResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.FilesService.Mkdir is not implemented"))
}

func (UnimplementedFilesServiceHandler) Remove(context.Context, *connect.Request[runnerv1.RemoveRequest]) (*connect.Response[runnerv1.RemoveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.FilesService.Remove is not implemented"))
}

func (UnimplementedFilesServiceHandler) Rename(context.Context, *connect.Request[runnerv1.RenameRequest]) (*connect.Response[runnerv1.RenameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.FilesService.Rename is not implemented"))
}
