// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aicoded/runner/v1/lifecycle.proto

package runnerv1connect

import (
	runnerv1 "aicoded.dev/framework/runnerproto/runnerv1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LifecycleServiceName is the fully-qualified name of the LifecycleService service.
	LifecycleServiceName = "aicoded.runner.v1.LifecycleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LifecycleServiceHelloProcedure is the fully-qualified name of the LifecycleService's Hello RPC.
	LifecycleServiceHelloProcedure = "/aicoded.runner.v1.LifecycleService/Hello"
	// LifecycleServiceReadyProcedure is the fully-qualified name of the LifecycleService's Ready RPC.
	LifecycleServiceReadyProcedure = "/aicoded.runner.v1.LifecycleService/Ready"
)

// LifecycleServiceClient is a client for the aicoded.runner.v1.LifecycleService service.
type LifecycleServiceClient interface {
	// Hello is the app's first call. The runner answers with everything the app needs to serve.
	Hello(context.Context, *connect.Request[runnerv1.HelloRequest]) (*connect.Response[runnerv1.HelloResponse], error)
	// Ready tells the runner that the app accepts requests on app.sock.
	Ready(context.Context, *connect.Request[runnerv1.ReadyRequest]) (*connect.Response[runnerv1.ReadyResponse], error)
}

// NewLifecycleServiceClient constructs a client for the aicoded.runner.v1.LifecycleService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLifecycleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LifecycleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lifecycleServiceMethods := runnerv1.File_aicoded_runner_v1_lifecycle_proto.Services().ByName("LifecycleService").Methods()
	return &lifecycleServiceClient{
		hello: connect.NewClient[runnerv1.HelloRequest, runnerv1.HelloResponse](
			httpClient,
			baseURL+LifecycleServiceHelloProcedure,
			connect.WithSchema(lifecycleServiceMethods.ByName("Hello")),
			connect.WithClientOptions(opts...),
		),
		ready: connect.NewClient[runnerv1.ReadyRequest, runnerv1.ReadyResponse](
			httpClient,
			baseURL+LifecycleServiceReadyProcedure,
			connect.WithSchema(lifecycleServiceMethods.ByName("Ready")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lifecycleServiceClient implements LifecycleServiceClient.
type lifecycleServiceClient struct {
	hello *connect.Client[runnerv1.HelloRequest, runnerv1.HelloResponse]
	ready *connect.Client[runnerv1.ReadyRequest, runnerv1.ReadyResponse]
}

// Hello calls aicoded.runner.v1.LifecycleService.Hello.
func (c *lifecycleServiceClient) Hello(ctx context.Context, req *connect.Request[runnerv1.HelloRequest]) (*connect.Response[runnerv1.HelloResponse], error) {
	return c.hello.CallUnary(ctx, req)
}

// Ready calls aicoded.runner.v1.LifecycleService.Ready.
func (c *lifecycleServiceClient) Ready(ctx context.Context, req *connect.Request[runnerv1.ReadyRequest]) (*connect.Response[runnerv1.ReadyResponse], error) {
	return c.ready.CallUnary(ctx, req)
}

// LifecycleServiceHandler is an implementation of the aicoded.runner.v1.LifecycleService service.
type LifecycleServiceHandler interface {
	// Hello is the app's first call. The runner answers with everything the app needs to serve.
	Hello(context.Context, *connect.Request[runnerv1.HelloRequest]) (*connect.Response[runnerv1.HelloResponse], error)
	// Ready tells the runner that the app accepts requests on app.sock.
	Ready(context.Context, *connect.Request[runnerv1.ReadyRequest]) (*connect.Response[runnerv1.ReadyResponse], error)
}

// NewLifecycleServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLifecycleServiceHandler(svc LifecycleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lifecycleServiceMethods := runnerv1.File_aicoded_runner_v1_lifecycle_proto.Services().ByName("LifecycleService").Methods()
	lifecycleServiceHelloHandler := connect.NewUnaryHandler(
		LifecycleServiceHelloProcedure,
		svc.Hello,
		connect.WithSchema(lifecycleServiceMethods.ByName("Hello")),
		connect.WithHandlerOptions(opts...),
	)
	lifecycleServiceReadyHandler := connect.NewUnaryHandler(
		LifecycleServiceReadyProcedure,
		svc.Ready,
		connect.WithSchema(lifecycleServiceMethods.ByName("Ready")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aicoded.runner.v1.LifecycleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LifecycleServiceHelloProcedure:
			lifecycleServiceHelloHandler.ServeHTTP(w, r)
		case LifecycleServiceReadyProcedure:
			lifecycleServiceReadyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLifecycleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLifecycleServiceHandler struct{}

func (UnimplementedLifecycleServiceHandler) Hello(context.Context, *connect.Request[runnerv1.HelloRequest]) (*connect.Response[runnerv1.HelloResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.LifecycleService.Hello is not implemented"))
}

func (UnimplementedLifecycleServiceHandler) Ready(context.Context, *connect.Request[runnerv1.ReadyRequest]) (*connect.Response[runnerv1.ReadyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.LifecycleService.Ready is not implemented"))
}
