// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aicoded/runner/v1/mail.proto

package runnerv1connect

import (
	runnerv1 "aicoded.dev/framework/runnerproto/runnerv1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MailServiceName is the fully-qualified name of the MailService service.
	MailServiceName = "aicoded.runner.v1.MailService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MailServiceSendProcedure is the fully-qualified name of the MailService's Send RPC.
	MailServiceSendProcedure = "/aicoded.runner.v1.MailService/Send"
	// MailServiceListProcedure is the fully-qualified name of the MailService's List RPC.
	MailServiceListProcedure = "/aicoded.runner.v1.MailService/List"
	// MailServiceGetProcedure is the fully-qualified name of the MailService's Get RPC.
	MailServiceGetProcedure = "/aicoded.runner.v1.MailService/Get"
	// MailServiceDeleteProcedure is the fully-qualified name of the MailService's Delete RPC.
	MailServiceDeleteProcedure = "/aicoded.runner.v1.MailService/Delete"
	// MailServiceMoveProcedure is the fully-qualified name of the MailService's Move RPC.
	MailServiceMoveProcedure = "/aicoded.runner.v1.MailService/Move"
)

// MailServiceClient is a client for the aicoded.runner.v1.MailService service.
type MailServiceClient interface {
	// Send is idempotent per idempotency_key: a repeated key returns the first message's id and
	// sends nothing.
	Send(context.Context, *connect.Request[runnerv1.SendRequest]) (*connect.Response[runnerv1.SendResponse], error)
	List(context.Context, *connect.Request[runnerv1.ListRequest]) (*connect.Response[runnerv1.ListResponse], error)
	Get(context.Context, *connect.Request[runnerv1.GetRequest]) (*connect.Response[runnerv1.GetResponse], error)
	Delete(context.Context, *connect.Request[runnerv1.DeleteRequest]) (*connect.Response[runnerv1.DeleteResponse], error)
	Move(context.Context, *connect.Request[runnerv1.MoveRequest]) (*connect.Response[runnerv1.MoveResponse], error)
}

// NewMailServiceClient constructs a client for the aicoded.runner.v1.MailService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMailServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MailServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	mailServiceMethods := runnerv1.File_aicoded_runner_v1_mail_proto.Services().ByName("MailService").Methods()
	return &mailServiceClient{
		send: connect.NewClient[runnerv1.SendRequest, runnerv1.SendResponse](
			httpClient,
			baseURL+MailServiceSendProcedure,
			connect.WithSchema(mailServiceMethods.ByName("Send")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[runnerv1.ListRequest, runnerv1.ListResponse](
			httpClient,
			baseURL+MailServiceListProcedure,
			connect.WithSchema(mailServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[runnerv1.GetRequest, runnerv1.GetResponse](
			httpClient,
			baseURL+MailServiceGetProcedure,
			connect.WithSchema(mailServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[runnerv1.DeleteRequest, runnerv1.DeleteResponse](
			httpClient,
			baseURL+MailServiceDeleteProcedure,
			connect.WithSchema(mailServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		move: connect.NewClient[runnerv1.MoveRequest, runnerv1.MoveResponse](
			httpClient,
			baseURL+MailServiceMoveProcedure,
			connect.WithSchema(mailServiceMethods.ByName("Move")),
			connect.WithClientOptions(opts...),
		),
	}
}

// mailServiceClient implements MailServiceClient.
type mailServiceClient struct {
	send   *connect.Client[runnerv1.SendRequest, runnerv1.SendResponse]
	list   *connect.Client[runnerv1.ListRequest, runnerv1.ListResponse]
	get    *connect.Client[runnerv1.GetRequest, runnerv1.GetResponse]
	delete *connect.Client[runnerv1.DeleteRequest, runnerv1.DeleteResponse]
	move   *connect.Client[runnerv1.MoveRequest, runnerv1.MoveResponse]
}

// Send calls aicoded.runner.v1.MailService.Send.
func (c *mailServiceClient) Send(ctx context.Context, req *connect.Request[runnerv1.SendRequest]) (*connect.Response[runnerv1.SendResponse], error) {
	return c.send.CallUnary(ctx, req)
}

// List calls aicoded.runner.v1.MailService.List.
func (c *mailServiceClient) List(ctx context.Context, req *connect.Request[runnerv1.ListRequest]) (*connect.Response[runnerv1.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Get calls aicoded.runner.v1.MailService.Get.
func (c *mailServiceClient) Get(ctx context.Context, req *connect.Request[runnerv1.GetRequest]) (*connect.Response[runnerv1.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Delete calls aicoded.runner.v1.MailService.Delete.
func (c *mailServiceClient) Delete(ctx context.Context, req *connect.Request[runnerv1.DeleteRequest]) (*connect.Response[runnerv1.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// Move calls aicoded.runner.v1.MailService.Move.
func (c *mailServiceClient) Move(ctx context.Context, req *connect.Request[runnerv1.MoveRequest]) (*connect.Response[runnerv1.MoveResponse], error) {
	return c.move.CallUnary(ctx, req)
}

// MailServiceHandler is an implementation of the aicoded.runner.v1.MailService service.
type MailServiceHandler interface {
	// Send is idempotent per idempotency_key: a repeated key returns the first message's id and
	// sends nothing.
	Send(context.Context, *connect.Request[runnerv1.SendRequest]) (*connect.Response[runnerv1.SendResponse], error)
	List(context.Context, *connect.Request[runnerv1.ListRequest]) (*connect.Response[runnerv1.ListResponse], error)
	Get(context.Context, *connect.Request[runnerv1.GetRequest]) (*connect.Response[runnerv1.GetResponse], error)
	Delete(context.Context, *connect.Request[runnerv1.DeleteRequest]) (*connect.Response[runnerv1.DeleteResponse], error)
	Move(context.Context, *connect.Request[runnerv1.MoveRequest]) (*connect.Response[runnerv1.MoveResponse], error)
}

// NewMailServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMailServiceHandler(svc MailServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	mailServiceMethods := runnerv1.File_aicoded_runner_v1_mail_proto.Services().ByName("MailService").Methods()
	mailServiceSendHandler := connect.NewUnaryHandler(
		MailServiceSendProcedure,
		svc.Send,
		connect.WithSchema(mailServiceMethods.ByName("Send")),
		connect.WithHandlerOptions(opts...),
	)
	mailServiceListHandler := connect.NewUnaryHandler(
		MailServiceListProcedure,
		svc.List,
		connect.WithSchema(mailServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	mailServiceGetHandler := connect.NewUnaryHandler(
		MailServiceGetProcedure,
		svc.Get,
		connect.WithSchema(mailServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	mailServiceDeleteHandler := connect.NewUnaryHandler(
		MailServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(mailServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	mailServiceMoveHandler := connect.NewUnaryHandler(
		MailServiceMoveProcedure,
		svc.Move,
		connect.WithSchema(mailServiceMethods.ByName("Move")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aicoded.runner.v1.MailService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MailServiceSendProcedure:
			mailServiceSendHandler.ServeHTTP(w, r)
		case MailServiceListProcedure:
			mailServiceListHandler.ServeHTTP(w, r)
		case MailServiceGetProcedure:
			mailServiceGetHandler.ServeHTTP(w, r)
		case MailServiceDeleteProcedure:
			mailServiceDeleteHandler.ServeHTTP(w, r)
		case MailServiceMoveProcedure:
			mailServiceMoveHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMailServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMailServiceHandler struct{}

func (UnimplementedMailServiceHandler) Send(context.Context, *connect.Request[runnerv1.SendRequest]) (*connect.Response[runnerv1.SendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.MailService.Send is not implemented"))
}

func (UnimplementedMailServiceHandler) List(context.Context, *connect.Request[runnerv1.ListRequest]) (*connect.Response[runnerv1.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.MailService.List is not implemented"))
}

func (UnimplementedMailServiceHandler) Get(context.Context, *connect.Request[runnerv1.GetRequest]) (*connect.Response[runnerv1.GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.MailService.Get is not implemented"))
}

func (UnimplementedMailServiceHandler) Delete(context.Context, *connect.Request[runnerv1.DeleteRequest]) (*connect.Response[runnerv1.DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.MailService.Delete is not implemented"))
}

func (UnimplementedMailServiceHandler) Move(context.Context, *connect.Request[runnerv1.MoveRequest]) (*connect.Response[runnerv1.MoveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.MailService.Move is not implemented"))
}
