// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aicoded/runner/v1/rpc.proto

package runnerv1connect

import (
	runnerv1 "aicoded.dev/framework/runnerproto/runnerv1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RpcServiceName is the fully-qualified name of the RpcService service.
	RpcServiceName = "aicoded.runner.v1.RpcService"
	// AppServiceName is the fully-qualified name of the AppService service.
	AppServiceName = "aicoded.runner.v1.AppService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RpcServiceCallProcedure is the fully-qualified name of the RpcService's Call RPC.
	RpcServiceCallProcedure = "/aicoded.runner.v1.RpcService/Call"
	// AppServiceServeProcedure is the fully-qualified name of the AppService's Serve RPC.
	AppServiceServeProcedure = "/aicoded.runner.v1.AppService/Serve"
)

// RpcServiceClient is a client for the aicoded.runner.v1.RpcService service.
type RpcServiceClient interface {
	Call(context.Context, *connect.Request[runnerv1.CallRequest]) (*connect.Response[runnerv1.CallResponse], error)
}

// NewRpcServiceClient constructs a client for the aicoded.runner.v1.RpcService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRpcServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RpcServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	rpcServiceMethods := runnerv1.File_aicoded_runner_v1_rpc_proto.Services().ByName("RpcService").Methods()
	return &rpcServiceClient{
		call: connect.NewClient[runnerv1.CallRequest, runnerv1.CallResponse](
			httpClient,
			baseURL+RpcServiceCallProcedure,
			connect.WithSchema(rpcServiceMethods.ByName("Call")),
			connect.WithClientOptions(opts...),
		),
	}
}

// rpcServiceClient implements RpcServiceClient.
type rpcServiceClient struct {
	call *connect.Client[runnerv1.CallRequest, runnerv1.CallResponse]
}

// Call calls aicoded.runner.v1.RpcService.Call.
func (c *rpcServiceClient) Call(ctx context.Context, req *connect.Request[runnerv1.CallRequest]) (*connect.Response[runnerv1.CallResponse], error) {
	return c.call.CallUnary(ctx, req)
}

// RpcServiceHandler is an implementation of the aicoded.runner.v1.RpcService service.
type RpcServiceHandler interface {
	Call(context.Context, *connect.Request[runnerv1.CallRequest]) (*connect.Response[runnerv1.CallResponse], error)
}

// NewRpcServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRpcServiceHandler(svc RpcServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	rpcServiceMethods := runnerv1.File_aicoded_runner_v1_rpc_proto.Services().ByName("RpcService").Methods()
	rpcServiceCallHandler := connect.NewUnaryHandler(
		RpcServiceCallProcedure,
		svc.Call,
		connect.WithSchema(rpcServiceMethods.ByName("Call")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aicoded.runner.v1.RpcService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RpcServiceCallProcedure:
			rpcServiceCallHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRpcServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRpcServiceHandler struct{}

func (UnimplementedRpcServiceHandler) Call(context.Context, *connect.Request[runnerv1.CallRequest]) (*connect.Response[runnerv1.CallResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.RpcService.Call is not implemented"))
}

// AppServiceClient is a client for the aicoded.runner.v1.AppService service.
type AppServiceClient interface {
	Serve(context.Context, *connect.Request[runnerv1.ServeRequest]) (*connect.Response[runnerv1.ServeResponse], error)
}

// NewAppServiceClient constructs a client for the aicoded.runner.v1.AppService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAppServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AppServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	appServiceMethods := runnerv1.File_aicoded_runner_v1_rpc_proto.Services().ByName("AppService").Methods()
	return &appServiceClient{
		serve: connect.NewClient[runnerv1.ServeRequest, runnerv1.ServeResponse](
			httpClient,
			baseURL+AppServiceServeProcedure,
			connect.WithSchema(appServiceMethods.ByName("Serve")),
			connect.WithClientOptions(opts...),
		),
	}
}

// appServiceClient implements AppServiceClient.
type appServiceClient struct {
	serve *connect.Client[runnerv1.ServeRequest, runnerv1.ServeResponse]
}

// Serve calls aicoded.runner.v1.AppService.Serve.
func (c *appServiceClient) Serve(ctx context.Context, req *connect.Request[runnerv1.ServeRequest]) (*connect.Response[runnerv1.ServeResponse], error) {
	return c.serve.CallUnary(ctx, req)
}

// AppServiceHandler is an implementation of the aicoded.runner.v1.AppService service.
type AppServiceHandler interface {
	Serve(context.Context, *connect.Request[runnerv1.ServeRequest]) (*connect.Response[runnerv1.ServeResponse], error)
}

// NewAppServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAppServiceHandler(svc AppServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	appServiceMethods := runnerv1.File_aicoded_runner_v1_rpc_proto.Services().ByName("AppService").Methods()
	appServiceServeHandler := connect.NewUnaryHandler(
		AppServiceServeProcedure,
		svc.Serve,
		connect.WithSchema(appServiceMethods.ByName("Serve")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aicoded.runner.v1.AppService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AppServiceServeProcedure:
			appServiceServeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAppServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAppServiceHandler struct{}

func (UnimplementedAppServiceHandler) Serve(context.Context, *connect.Request[runnerv1.ServeRequest]) (*connect.Response[runnerv1.ServeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.AppService.Serve is not implemented"))
}
