// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aicoded/runner/v1/secrets.proto

package runnerv1connect

import (
	runnerv1 "aicoded.dev/framework/runnerproto/runnerv1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SecretsServiceName is the fully-qualified name of the SecretsService service.
	SecretsServiceName = "aicoded.runner.v1.SecretsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SecretsServiceGetSecretProcedure is the fully-qualified name of the SecretsService's GetSecret
	// RPC.
	SecretsServiceGetSecretProcedure = "/aicoded.runner.v1.SecretsService/GetSecret"
)

// SecretsServiceClient is a client for the aicoded.runner.v1.SecretsService service.
type SecretsServiceClient interface {
	// GetSecret returns NOT_FOUND for a secret that is not declared.
	GetSecret(context.Context, *connect.Request[runnerv1.GetSecretRequest]) (*connect.Response[runnerv1.GetSecretResponse], error)
}

// NewSecretsServiceClient constructs a client for the aicoded.runner.v1.SecretsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSecretsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SecretsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	secretsServiceMethods := runnerv1.File_aicoded_runner_v1_secrets_proto.Services().ByName("SecretsService").Methods()
	return &secretsServiceClient{
		getSecret: connect.NewClient[runnerv1.GetSecretRequest, runnerv1.GetSecretResponse](
			httpClient,
			baseURL+SecretsServiceGetSecretProcedure,
			connect.WithSchema(secretsServiceMethods.ByName("GetSecret")),
			connect.WithClientOptions(opts...),
		),
	}
}

// secretsServiceClient implements SecretsServiceClient.
type secretsServiceClient struct {
	getSecret *connect.Client[runnerv1.GetSecretRequest, runnerv1.GetSecretResponse]
}

// GetSecret calls aicoded.runner.v1.SecretsService.GetSecret.
func (c *secretsServiceClient) GetSecret(ctx context.Context, req *connect.Request[runnerv1.GetSecretRequest]) (*connect.Response[runnerv1.GetSecretResponse], error) {
	return c.getSecret.CallUnary(ctx, req)
}

// SecretsServiceHandler is an implementation of the aicoded.runner.v1.SecretsService service.
type SecretsServiceHandler interface {
	// GetSecret returns NOT_FOUND for a secret that is not declared.
	GetSecret(context.Context, *connect.Request[runnerv1.GetSecretRequest]) (*connect.Response[runnerv1.GetSecretResponse], error)
}

// NewSecretsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSecretsServiceHandler(svc SecretsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	secretsServiceMethods := runnerv1.File_aicoded_runner_v1_secrets_proto.Services().ByName("SecretsService").Methods()
	secretsServiceGetSecretHandler := connect.NewUnaryHandler(
		SecretsServiceGetSecretProcedure,
		svc.GetSecret,
		connect.WithSchema(secretsServiceMethods.ByName("GetSecret")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aicoded.runner.v1.SecretsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SecretsServiceGetSecretProcedure:
			secretsServiceGetSecretHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSecretsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSecretsServiceHandler struct{}

func (UnimplementedSecretsServiceHandler) GetSecret(context.Context, *connect.Request[runnerv1.GetSecretRequest]) (*connect.Response[runnerv1.GetSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.SecretsService.GetSecret is not implemented"))
}
