// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aicoded/runner/v1/telemetry.proto

package runnerv1connect

import (
	runnerv1 "aicoded.dev/framework/runnerproto/runnerv1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TelemetryServiceName is the fully-qualified name of the TelemetryService service.
	TelemetryServiceName = "aicoded.runner.v1.TelemetryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TelemetryServiceExportProcedure is the fully-qualified name of the TelemetryService's Export RPC.
	TelemetryServiceExportProcedure = "/aicoded.runner.v1.TelemetryService/Export"
)

// TelemetryServiceClient is a client for the aicoded.runner.v1.TelemetryService service.
type TelemetryServiceClient interface {
	Export(context.Context, *connect.Request[runnerv1.ExportRequest]) (*connect.Response[runnerv1.ExportResponse], error)
}

// NewTelemetryServiceClient constructs a client for the aicoded.runner.v1.TelemetryService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTelemetryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TelemetryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	telemetryServiceMethods := runnerv1.File_aicoded_runner_v1_telemetry_proto.Services().ByName("TelemetryService").Methods()
	return &telemetryServiceClient{
		export: connect.NewClient[runnerv1.ExportRequest, runnerv1.ExportResponse](
			httpClient,
			baseURL+TelemetryServiceExportProcedure,
			connect.WithSchema(telemetryServiceMethods.ByName("Export")),
			connect.WithClientOptions(opts...),
		),
	}
}

// telemetryServiceClient implements TelemetryServiceClient.
type telemetryServiceClient struct {
	export *connect.Client[runnerv1.ExportRequest, runnerv1.ExportResponse]
}

// Export calls aicoded.runner.v1.TelemetryService.Export.
func (c *telemetryServiceClient) Export(ctx context.Context, req *connect.Request[runnerv1.ExportRequest]) (*connect.Response[runnerv1.ExportResponse], error) {
	return c.export.CallUnary(ctx, req)
}

// TelemetryServiceHandler is an implementation of the aicoded.runner.v1.TelemetryService service.
type TelemetryServiceHandler interface {
	Export(context.Context, *connect.Request[runnerv1.ExportRequest]) (*connect.Response[runnerv1.ExportResponse], error)
}

// NewTelemetryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTelemetryServiceHandler(svc TelemetryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	telemetryServiceMethods := runnerv1.File_aicoded_runner_v1_telemetry_proto.Services().ByName("TelemetryService").Methods()
	telemetryServiceExportHandler := connect.NewUnaryHandler(
		TelemetryServiceExportProcedure,
		svc.Export,
		connect.WithSchema(telemetryServiceMethods.ByName("Export")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aicoded.runner.v1.TelemetryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TelemetryServiceExportProcedure:
			telemetryServiceExportHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTelemetryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTelemetryServiceHandler struct{}

func (UnimplementedTelemetryServiceHandler) Export(context.Context, *connect.Request[runnerv1.ExportRequest]) (*connect.Response[runnerv1.ExportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aicoded.runner.v1.TelemetryService.Export is not implemented"))
}
