// Code generated by aicoded. DO NOT EDIT.

package apps

import (
	"context"
	"io"
	"strings"
	"sync"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/reactive"
	"aicoded.dev/framework/web/render"
)

const routeKey = "56797486"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Apps []App
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	// Subscribe runs while the page is open and must return when ctx is done.
	Subscribe(ctx context.Context, r *web.Request, state *ReactiveState) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/apps")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/aicoded/reactive-ZRZHG67R.css\">", "<script defer src=\"/_aicoded/assets/aicoded/reactive-MTQXR3MF.js\"></script>"})
	return s
}

type state struct {
	web.Frame
	mu        sync.Mutex
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) RouteKey() string { return routeKey }

func (s *state) Snapshot(ctx context.Context) map[string]reactive.Binding {
	s.mu.Lock()
	defer s.mu.Unlock()
	return map[string]reactive.Binding{
		routeKey + ".2e99b33e8bf4bb86": renderBlock_2e99b33e8bf4bb86(ctx, &s.RouteData),
	}
}

func (s *state) Subscribe(ctx context.Context, r *web.Request, conn *reactive.Conn) error {
	return s.dp.Subscribe(ctx, r, &ReactiveState{ctx: ctx, s: s, conn: conn})
}

func (s *state) HandleWrite(ctx context.Context, r *web.Request, conn *reactive.Conn, msg reactive.WriteMsg) {
	conn.Reject(ctx, msg, "unknown variable", reactive.CodeValidation)
}

// ReactiveState sends new values of the page's live variables to one open page. Its Set
// methods may be called from any goroutine.
type ReactiveState struct {
	ctx  context.Context
	s    *state
	conn *reactive.Conn
}

// SetApps stores v as apps and sends the parts of the page that show it.
func (rs *ReactiveState) SetApps(v []App) {
	rs.s.mu.Lock()
	defer rs.s.mu.Unlock()
	rs.s.RouteData.Apps = v
	rs.conn.Enqueue(routeKey+".2e99b33e8bf4bb86", renderBlock_2e99b33e8bf4bb86(rs.ctx, &rs.s.RouteData))
}

func (s *state) Write(w io.Writer) error {
//line index.html:1
	apps := s.RouteData.Apps
	_ = apps
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:4
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
	if len(apps) > 0 {
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
//line index.html:7
		for _, a := range apps {
			if _, err := io.WriteString(w, _html3); err != nil {
				return err
			}
//line index.html:8
			if err := render.URLPart(w, a.Name); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html4); err != nil {
				return err
			}
//line index.html:8
			if err := render.Text(w, a.Name); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html5); err != nil {
				return err
			}
//line index.html:9
			if err := render.Text(w, a.State); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html6); err != nil {
				return err
			}
//line index.html:10
			if err := render.Attr(w, a.Stamp); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html4); err != nil {
				return err
			}
//line index.html:10
			if err := render.Text(w, a.Since); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html7); err != nil {
				return err
			}
//line index.html:11
			if a.URL != "" {
				if _, err := io.WriteString(w, _html8); err != nil {
					return err
				}
//line index.html:11
				if err := render.URL(w, a.URL); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html4); err != nil {
					return err
				}
//line index.html:11
				if err := render.Text(w, a.URL); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html9); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html10); err != nil {
				return err
			}
//line index.html:12
			if err := render.Text(w, a.Problem); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
//line index.html:16
	} else {
		if _, err := io.WriteString(w, _html13); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html14); err != nil {
		return err
	}
	return nil
}

func renderBlock_2e99b33e8bf4bb86(ctx context.Context, data *RouteData) reactive.Binding {
	var b strings.Builder
	if err := func(w io.Writer) error {
//line index.html:1
		apps := data.Apps
//line index.html:4
		if len(apps) > 0 {
			if _, err := io.WriteString(w, _html2); err != nil {
				return err
			}
//line index.html:7
			for _, a := range apps {
				if _, err := io.WriteString(w, _html3); err != nil {
					return err
				}
//line index.html:8
				if err := render.URLPart(w, a.Name); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html4); err != nil {
					return err
				}
//line index.html:8
				if err := render.Text(w, a.Name); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html5); err != nil {
					return err
				}
//line index.html:9
				if err := render.Text(w, a.State); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html6); err != nil {
					return err
				}
//line index.html:10
				if err := render.Attr(w, a.Stamp); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html4); err != nil {
					return err
				}
//line index.html:10
				if err := render.Text(w, a.Since); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html7); err != nil {
					return err
				}
//line index.html:11
				if a.URL != "" {
					if _, err := io.WriteString(w, _html8); err != nil {
						return err
					}
//line index.html:11
					if err := render.URL(w, a.URL); err != nil {
						return err
					}
					if _, err := io.WriteString(w, _html4); err != nil {
						return err
					}
//line index.html:11
					if err := render.Text(w, a.URL); err != nil {
						return err
					}
					if _, err := io.WriteString(w, _html9); err != nil {
						return err
					}
				}
				if _, err := io.WriteString(w, _html10); err != nil {
					return err
				}
//line index.html:12
				if err := render.Text(w, a.Problem); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html11); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html12); err != nil {
				return err
			}
//line index.html:16
		} else {
			if _, err := io.WriteString(w, _html13); err != nil {
				return err
			}
		}
		return nil
	}(&b); err != nil {
		web.LogError(ctx, "live block not rendered", err, "route", routeKey, "block", "2e99b33e8bf4bb86")
		return reactive.HTMLBinding("")
	}
	return reactive.HTMLBinding(b.String())
}

const (
	_html0  = "<h1>Apps</h1> <div id=\"apps\"> "
	_html1  = "<ssr-block data-ssr-bind=\"56797486.2e99b33e8bf4bb86\">"
	_html2  = "<table> <thead><tr><th>App</th><th>State</th><th>Since</th><th>Address</th><th>Problem</th></tr></thead> <tbody> "
	_html3  = "<tr> <td><a href=\"/apps/"
	_html4  = "\">"
	_html5  = "</a></td> <td>"
	_html6  = "</td> <td><time datetime=\""
	_html7  = "</time></td> <td>"
	_html8  = "<a href=\""
	_html9  = "</a>"
	_html10 = "</td> <td>"
	_html11 = "</td> </tr>"
	_html12 = " </tbody> </table>"
	_html13 = "<p>The workspace has no apps.</p>"
	_html14 = "</ssr-block> </div>"
)
