// Code generated by aicoded. DO NOT EDIT.

package traces

import (
	"context"
	"io"
	"strings"
	"sync"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/reactive"
	"aicoded.dev/framework/web/render"
)

const routeKey = "131f6b7b"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Names  []string
	Query  Query
	Traces Traces
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	// Subscribe runs while the page is open and must return when ctx is done.
	Subscribe(ctx context.Context, r *web.Request, state *ReactiveState) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/traces")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/aicoded/reactive-ZRZHG67R.css\">", "<script defer src=\"/_aicoded/assets/aicoded/reactive-MTQXR3MF.js\"></script>", "<link rel=\"stylesheet\" href=\"/_aicoded/assets/pages/traces/index-UZUPUNLC.css\">"})
	return s
}

type state struct {
	web.Frame
	mu        sync.Mutex
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) RouteKey() string { return routeKey }

func (s *state) Snapshot(ctx context.Context) map[string]reactive.Binding {
	s.mu.Lock()
	defer s.mu.Unlock()
	return map[string]reactive.Binding{
		routeKey + ".d5fcfdd9024962f0": renderBlock_d5fcfdd9024962f0(ctx, &s.RouteData),
		routeKey + ".fb0be1b5f6680178": renderBlock_fb0be1b5f6680178(ctx, &s.RouteData),
	}
}

func (s *state) Subscribe(ctx context.Context, r *web.Request, conn *reactive.Conn) error {
	return s.dp.Subscribe(ctx, r, &ReactiveState{ctx: ctx, s: s, conn: conn})
}

func (s *state) HandleWrite(ctx context.Context, r *web.Request, conn *reactive.Conn, msg reactive.WriteMsg) {
	conn.Reject(ctx, msg, "unknown variable", reactive.CodeValidation)
}

// ReactiveState sends new values of the page's live variables to one open page. Its Set
// methods may be called from any goroutine.
type ReactiveState struct {
	ctx  context.Context
	s    *state
	conn *reactive.Conn
}

// SetTraces stores v as traces and sends the parts of the page that show it.
func (rs *ReactiveState) SetTraces(v Traces) {
	rs.s.mu.Lock()
	defer rs.s.mu.Unlock()
	rs.s.RouteData.Traces = v
	rs.conn.Enqueue(routeKey+".d5fcfdd9024962f0", renderBlock_d5fcfdd9024962f0(rs.ctx, &rs.s.RouteData))
	rs.conn.Enqueue(routeKey+".fb0be1b5f6680178", renderBlock_fb0be1b5f6680178(rs.ctx, &rs.s.RouteData))
}

func (s *state) Write(w io.Writer) error {
//line index.html:1
	names := s.RouteData.Names
	_ = names
//line index.html:2
	query := s.RouteData.Query
	_ = query
//line index.html:3
	traces := s.RouteData.Traces
	_ = traces
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:6
	if err := render.Attr(w, query.App); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:7
	for _, n := range names {
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
//line index.html:7
		if err := render.Attr(w, n); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
//line index.html:8
	if query.ErrorsOnly {
		if _, err := io.WriteString(w, _html5); err != nil {
			return err
		}
//line index.html:9
	} else {
		if _, err := io.WriteString(w, _html6); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html7); err != nil {
		return err
	}
//line index.html:12
	if _, err := io.WriteString(w, _html8); err != nil {
		return err
	}
	if traces.Problem != "" {
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
//line index.html:12
		if err := render.Text(w, traces.Problem); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html10); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html11); err != nil {
		return err
	}
//line index.html:14
	if _, err := io.WriteString(w, _html12); err != nil {
		return err
	}
	if len(traces.Traces) > 0 {
		if _, err := io.WriteString(w, _html13); err != nil {
			return err
		}
//line index.html:17
		for _, t := range traces.Traces {
			if _, err := io.WriteString(w, _html14); err != nil {
				return err
			}
//line index.html:17
			if err := render.Attr(w, t.Stamp); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html15); err != nil {
				return err
			}
//line index.html:17
			if err := render.Text(w, t.Start); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html16); err != nil {
				return err
			}
//line index.html:17
			if err := render.URLPart(w, t.ID); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html15); err != nil {
				return err
			}
//line index.html:17
			if err := render.Text(w, t.Root); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html17); err != nil {
				return err
			}
//line index.html:17
			if err := render.Text(w, t.Apps); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html18); err != nil {
				return err
			}
//line index.html:17
			if err := render.Text(w, t.Spans); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html18); err != nil {
				return err
			}
//line index.html:17
			if err := render.Text(w, t.Duration); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html18); err != nil {
				return err
			}
//line index.html:17
			if t.Error {
				if _, err := io.WriteString(w, _html19); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html20); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html21); err != nil {
			return err
		}
//line index.html:20
	} else {
		if _, err := io.WriteString(w, _html22); err != nil {
			return err
		}
	}
//line route_gen.go:258
	if _, err := io.WriteString(w, _html23); err != nil {
		return err
	}
	return nil
}

func renderBlock_d5fcfdd9024962f0(ctx context.Context, data *RouteData) reactive.Binding {
	var b strings.Builder
	if err := func(w io.Writer) error {
//line index.html:3
		traces := data.Traces
//line index.html:14
		if len(traces.Traces) > 0 {
			if _, err := io.WriteString(w, _html13); err != nil {
				return err
			}
//line index.html:17
			for _, t := range traces.Traces {
				if _, err := io.WriteString(w, _html14); err != nil {
					return err
				}
//line index.html:17
				if err := render.Attr(w, t.Stamp); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html15); err != nil {
					return err
				}
//line index.html:17
				if err := render.Text(w, t.Start); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html16); err != nil {
					return err
				}
//line index.html:17
				if err := render.URLPart(w, t.ID); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html15); err != nil {
					return err
				}
//line index.html:17
				if err := render.Text(w, t.Root); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html17); err != nil {
					return err
				}
//line index.html:17
				if err := render.Text(w, t.Apps); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html18); err != nil {
					return err
				}
//line index.html:17
				if err := render.Text(w, t.Spans); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html18); err != nil {
					return err
				}
//line index.html:17
				if err := render.Text(w, t.Duration); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html18); err != nil {
					return err
				}
//line index.html:17
				if t.Error {
					if _, err := io.WriteString(w, _html19); err != nil {
						return err
					}
				}
				if _, err := io.WriteString(w, _html20); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html21); err != nil {
				return err
			}
//line index.html:20
		} else {
			if _, err := io.WriteString(w, _html22); err != nil {
				return err
			}
		}
//line route_gen.go:348
		return nil
	}(&b); err != nil {
		web.LogError(ctx, "live block not rendered", err, "route", routeKey, "block", "d5fcfdd9024962f0")
		return reactive.HTMLBinding("")
	}
	return reactive.HTMLBinding(b.String())
}

func renderBlock_fb0be1b5f6680178(ctx context.Context, data *RouteData) reactive.Binding {
	var b strings.Builder
	if err := func(w io.Writer) error {
//line index.html:3
		traces := data.Traces
//line index.html:12
		if traces.Problem != "" {
			if _, err := io.WriteString(w, _html9); err != nil {
				return err
			}
//line index.html:12
			if err := render.Text(w, traces.Problem); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html10); err != nil {
				return err
			}
		}
//line route_gen.go:375
		return nil
	}(&b); err != nil {
		web.LogError(ctx, "live block not rendered", err, "route", routeKey, "block", "fb0be1b5f6680178")
		return reactive.HTMLBinding("")
	}
	return reactive.HTMLBinding(b.String())
}

const (
	_html0  = "<h1>Traces</h1> <form method=\"get\" action=\"/traces\" id=\"filter\"> <label>App <input name=\"app\" list=\"app-names\" value=\""
	_html1  = "\"></label> <datalist id=\"app-names\">"
	_html2  = "<option value=\""
	_html3  = "\"></option>"
	_html4  = "</datalist> "
	_html5  = "<label><input type=\"checkbox\" name=\"errors\" value=\"1\" checked> Only with an error</label>"
	_html6  = "<label><input type=\"checkbox\" name=\"errors\" value=\"1\"> Only with an error</label>"
	_html7  = " <button type=\"submit\">Show</button> </form> <div id=\"problem\">"
	_html8  = "<ssr-block data-ssr-bind=\"131f6b7b.fb0be1b5f6680178\">"
	_html9  = "<pre class=\"error\">"
	_html10 = "</pre>"
	_html11 = "</ssr-block></div> <div id=\"traces\"> "
	_html12 = "<ssr-block data-ssr-bind=\"131f6b7b.d5fcfdd9024962f0\">"
	_html13 = "<table> <thead><tr><th>Start</th><th>Root span</th><th>Apps</th><th>Spans</th><th>Duration</th><th>Error</th></tr></thead> <tbody> "
	_html14 = "<tr><td><time datetime=\""
	_html15 = "\">"
	_html16 = "</time></td><td><a href=\"/traces/"
	_html17 = "</a></td><td>"
	_html18 = "</td><td>"
	_html19 = "<span class=\"error\">error</span>"
	_html20 = "</td></tr>"
	_html21 = " </tbody> </table>"
	_html22 = "<p>No traces match.</p>"
	_html23 = "</ssr-block> </div>"
)
