// Code generated by aicoded. DO NOT EDIT.

package contact

import (
	"context"
	"io"
	"net/http"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/form"
	"aicoded.dev/framework/web/render"
)

const routeKey = "4eb95063"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Sent bool
}

// FormContactValues holds the fields of the form contact.
type FormContactValues struct {
	form.BaseFormValues
	Name    form.Input[string]
	Email   form.Input[string]
	Topic   form.Select[string]
	Message form.Textarea
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	InitContact(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormContactValues) error
	ProcessContact(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormContactValues) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/contact")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	s.FormContact.SetElements([]form.Element{&s.FormContact.Name, &s.FormContact.Email, &s.FormContact.Topic, &s.FormContact.Message})
	return s
}

type state struct {
	web.Frame
	dp          RouteDataProvider
	RouteData   RouteData
	FormContact FormContactValues
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	s.FormContact.Prepare(routeKey+".contact", r.CSRFToken())
	if err := s.dp.InitContact(ctx, r, w, &s.FormContact); err != nil {
		return err
	}
	return nil
}

func (s *state) SubmitForm(ctx context.Context, r *web.Request, w web.ResponseWriter, id string) (bool, error) {
	switch id {
	case routeKey + ".contact":
		if form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormContact.Name.Process(r.Request, "name", false, true)
		s.FormContact.Email.Process(r.Request, "email", false, true)
		s.FormContact.Topic.Process(r.Request, "topic", false, true)
		s.FormContact.Message.Process(r.Request, "message", false, true)
		s.FormContact.MarkValidated()
		if s.FormContact.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessContact(ctx, r, w, &s.FormContact)
	}
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:1
	sent := s.RouteData.Sent
	_ = sent
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:4
	if sent {
		if _, err := io.WriteString(w, _html1); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
	{
		form := s.FormContact
		_ = form
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html4); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html5); err != nil {
			return err
		}
		{
//line index.html:9
			input := form.Name
			_ = input
			if _, err := io.WriteString(w, _html6); err != nil {
				return err
			}
			if input.IsNotNull() {
				if _, err := io.WriteString(w, _html7); err != nil {
					return err
				}
				v := any(input.GetValue())
				if input.HasError() {
					v = input.GetFormValue()
				}
				if err := render.Attr(w, v); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html8); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html9); err != nil {
				return err
			}
//line index.html:9
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(input.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html10); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
//line index.html:11
		if form.Name.HasError() {
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
//line index.html:11
			if err := render.Text(w, form.Name.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html12); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html13); err != nil {
			return err
		}
		{
//line index.html:15
			input := form.Email
			_ = input
			if _, err := io.WriteString(w, _html14); err != nil {
				return err
			}
			if input.IsNotNull() {
				if _, err := io.WriteString(w, _html7); err != nil {
					return err
				}
				v := any(input.GetValue())
				if input.HasError() {
					v = input.GetFormValue()
				}
				if err := render.Attr(w, v); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html8); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html15); err != nil {
				return err
			}
//line index.html:15
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(input.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html10); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
//line index.html:17
		if form.Email.HasError() {
			if _, err := io.WriteString(w, _html16); err != nil {
				return err
			}
//line index.html:17
			if err := render.Text(w, form.Email.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html12); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html17); err != nil {
			return err
		}
		{
//line index.html:21
			input := form.Topic
			_ = input
			if _, err := io.WriteString(w, _html18); err != nil {
				return err
			}
//line index.html:21
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(input.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html10); err != nil {
				return err
			}
			isSelected := func(v string) bool { return v == input.GetValue() }
			for _, o := range input.GetOptions() {
				if err := o.WriteHtml(w, isSelected); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html19); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
//line index.html:23
		if form.Topic.HasError() {
			if _, err := io.WriteString(w, _html20); err != nil {
				return err
			}
//line index.html:23
			if err := render.Text(w, form.Topic.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html12); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html21); err != nil {
			return err
		}
		{
//line index.html:27
			textarea := form.Message
			_ = textarea
			if _, err := io.WriteString(w, _html22); err != nil {
				return err
			}
//line index.html:27
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(textarea.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html10); err != nil {
				return err
			}
			if err := render.Text(w, textarea.GetValue()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html23); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
//line index.html:29
		if form.Message.HasError() {
			if _, err := io.WriteString(w, _html24); err != nil {
				return err
			}
//line index.html:29
			if err := render.Text(w, form.Message.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html12); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html25); err != nil {
			return err
		}
	}
//line route_gen.go:322
	return nil
}

const (
	_html0  = "<h1>Contact us</h1> <p>Your message goes to the team by mail.</p> "
	_html1  = "<p id=\"sent\" class=\"alert success\">Your message was sent.</p>"
	_html2  = " "
	_html3  = "<form method=\"post\" enctype=\"application/x-www-form-urlencoded\"><input type=\"hidden\" name=\"_aicoded_form\" value=\""
	_html4  = "\"><input type=\"hidden\" name=\"_aicoded_csrf\" value=\""
	_html5  = "\"> <div class=\"field\"> <label for=\"contact-name\">Your name</label> "
	_html6  = "<input name=\"name\" type=\"text\""
	_html7  = " value=\""
	_html8  = "\""
	_html9  = " required maxlength=\"100\" id=\"contact-name\" class=\""
	_html10 = "\">"
	_html11 = "<p id=\"contact-name-error\" class=\"error\">"
	_html12 = "</p>"
	_html13 = " </div> <div class=\"field\"> <label for=\"contact-email\">Your email address</label> "
	_html14 = "<input name=\"email\" type=\"email\""
	_html15 = " required maxlength=\"254\" id=\"contact-email\" class=\""
	_html16 = "<p id=\"contact-email-error\" class=\"error\">"
	_html17 = " </div> <div class=\"field\"> <label for=\"contact-topic\">Topic</label> "
	_html18 = "<select name=\"topic\" required id=\"contact-topic\" class=\""
	_html19 = "</select>"
	_html20 = "<p id=\"contact-topic-error\" class=\"error\">"
	_html21 = " </div> <div class=\"field\"> <label for=\"contact-message\">Message</label> "
	_html22 = "<textarea name=\"message\" required maxlength=\"2000\" rows=\"6\" id=\"contact-message\" class=\""
	_html23 = "</textarea>"
	_html24 = "<p id=\"contact-message-error\" class=\"error\">"
	_html25 = " </div> <button type=\"submit\">Send message</button> </form>"
)
