// Code generated by aicoded. DO NOT EDIT.

package home

import (
	"context"
	"errors"
	"io"
	"strings"
	"sync"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/reactive"
	"aicoded.dev/framework/web/render"
)

const routeKey = "2cc974af"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	DisplayName    string
	Fruits         []string
	Intro          web.SafeHTML
	Langs          []string
	Price          float64
	Quantity       float64
	Status         string
	UserAge        int
	UserName       string
	VisitorsOnline int
	VisitorsTone   string
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	// Subscribe runs while the page is open and must return when ctx is done.
	Subscribe(ctx context.Context, r *web.Request, state *ReactiveState) error
	ValidateDisplayName(ctx context.Context, r *web.Request, val string) (string, error)
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/home")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/aicoded/reactive-ZRZHG67R.css\">", "<script defer src=\"/_aicoded/assets/aicoded/reactive-MTQXR3MF.js\"></script>", "<script defer src=\"/_aicoded/assets/pages/home/index-Y6CMEUT4.js\"></script>"})
	return s
}

type state struct {
	web.Frame
	mu        sync.Mutex
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) RouteKey() string { return routeKey }

func (s *state) Snapshot(ctx context.Context) map[string]reactive.Binding {
	s.mu.Lock()
	defer s.mu.Unlock()
	return map[string]reactive.Binding{
		routeKey + ".10504f08610e7f96": renderBlock_10504f08610e7f96(ctx, &s.RouteData),
		routeKey + ".displayName":      renderBlock_displayName(ctx, &s.RouteData),
	}
}

func (s *state) Subscribe(ctx context.Context, r *web.Request, conn *reactive.Conn) error {
	return s.dp.Subscribe(ctx, r, &ReactiveState{ctx: ctx, s: s, conn: conn})
}

func (s *state) HandleWrite(ctx context.Context, r *web.Request, conn *reactive.Conn, msg reactive.WriteMsg) {
	switch msg.Var {
	case "displayName":
		v, err := reactive.Decode[string](msg.Value)
		if err != nil {
			conn.Reject(ctx, msg, "The value has the wrong type.", reactive.CodeDecode)
			return
		}
		if v, err = s.dp.ValidateDisplayName(ctx, r, v); err != nil {
			s.refuseWrite(ctx, conn, msg, "displayName", err)
			return
		}
		(&ReactiveState{ctx: ctx, s: s, conn: conn}).SetDisplayName(v)
		conn.Ack(ctx, msg)
	default:
		conn.Reject(ctx, msg, "unknown variable", reactive.CodeValidation)
	}
}

// refuseWrite answers a write that a Validate hook refused. The page shows the message of a
// web.Error; any other error is logged and the page gets a general message.
func (s *state) refuseWrite(ctx context.Context, conn *reactive.Conn, msg reactive.WriteMsg, name string, err error) {
	var he *web.HTTPError
	if errors.As(err, &he) {
		conn.Reject(ctx, msg, he.Message, reactive.CodeValidation)
		return
	}
	web.LogError(ctx, "live value refused", err, "route", routeKey, "var", name)
	conn.Reject(ctx, msg, "The value was not accepted.", reactive.CodeValidation)
}

// ReactiveState sends new values of the page's live variables to one open page. Its Set
// methods may be called from any goroutine.
type ReactiveState struct {
	ctx  context.Context
	s    *state
	conn *reactive.Conn
}

// SetDisplayName stores v as displayName and sends the parts of the page that show it.
func (rs *ReactiveState) SetDisplayName(v string) {
	rs.s.mu.Lock()
	defer rs.s.mu.Unlock()
	rs.s.RouteData.DisplayName = v
	rs.conn.Enqueue(routeKey+".displayName", renderBlock_displayName(rs.ctx, &rs.s.RouteData))
}

// SetVisitorsOnline stores v as visitorsOnline and sends the parts of the page that show it.
func (rs *ReactiveState) SetVisitorsOnline(v int) {
	rs.s.mu.Lock()
	defer rs.s.mu.Unlock()
	rs.s.RouteData.VisitorsOnline = v
	rs.conn.Enqueue(routeKey+".10504f08610e7f96", renderBlock_10504f08610e7f96(rs.ctx, &rs.s.RouteData))
}

// SetVisitorsTone stores v as visitorsTone and sends the parts of the page that show it.
func (rs *ReactiveState) SetVisitorsTone(v string) {
	rs.s.mu.Lock()
	defer rs.s.mu.Unlock()
	rs.s.RouteData.VisitorsTone = v
	rs.conn.Enqueue(routeKey+".10504f08610e7f96", renderBlock_10504f08610e7f96(rs.ctx, &rs.s.RouteData))
}

func (s *state) Write(w io.Writer) error {
//line index.html:4
	displayName := s.RouteData.DisplayName
	_ = displayName
//line index.html:10
	fruits := s.RouteData.Fruits
	_ = fruits
//line index.html:1
	intro := s.RouteData.Intro
	_ = intro
//line index.html:11
	langs := s.RouteData.Langs
	_ = langs
//line index.html:5
	price := s.RouteData.Price
	_ = price
//line index.html:6
	quantity := s.RouteData.Quantity
	_ = quantity
//line index.html:9
	status := s.RouteData.Status
	_ = status
//line index.html:8
	userAge := s.RouteData.UserAge
	_ = userAge
//line index.html:7
	userName := s.RouteData.UserName
	_ = userName
//line index.html:2
	visitorsOnline := s.RouteData.VisitorsOnline
	_ = visitorsOnline
//line index.html:3
	visitorsTone := s.RouteData.VisitorsTone
	_ = visitorsTone
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:12
	if err := render.JSON(w, langs); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:17
	if err := render.HTML(w, intro); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
//line index.html:23
	if err := render.Attr(w, visitorsTone); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html3); err != nil {
		return err
	}
//line index.html:23
	if err := render.Text(w, visitorsOnline); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
//line index.html:29
	if _, err := io.WriteString(w, _html5); err != nil {
		return err
	}
	if err := render.Text(w, displayName); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html6); err != nil {
		return err
	}
//line index.html:38
	if err := render.Text(w, price); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html7); err != nil {
		return err
	}
//line index.html:39
	if err := render.Text(w, quantity); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html8); err != nil {
		return err
	}
//line index.html:40
	if err := render.Text(w, price*quantity); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html9); err != nil {
		return err
	}
//line index.html:41
	if err := render.Text(w, userName); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html10); err != nil {
		return err
	}
//line index.html:41
	if err := render.Text(w, render.If(userAge >= 18, "an adult", "a minor")); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html11); err != nil {
		return err
	}
//line index.html:46
	if err := render.Text(w, status); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html12); err != nil {
		return err
	}
//line index.html:47
	if status == "active" {
		if _, err := io.WriteString(w, _html13); err != nil {
			return err
		}
//line index.html:48
	} else if status == "pending" {
		if _, err := io.WriteString(w, _html14); err != nil {
			return err
		}
//line index.html:49
	} else {
		if _, err := io.WriteString(w, _html15); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html16); err != nil {
		return err
	}
//line index.html:53
	for _, fruit := range fruits {
		if _, err := io.WriteString(w, _html17); err != nil {
			return err
		}
//line index.html:53
		if err := render.Text(w, fruit); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html18); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html19); err != nil {
		return err
	}
//line index.html:54
	for i, lang := range langs {
		if _, err := io.WriteString(w, _html20); err != nil {
			return err
		}
//line index.html:54
		if err := render.Text(w, i); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html21); err != nil {
			return err
		}
//line index.html:54
		if err := render.Text(w, lang); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html18); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html22); err != nil {
		return err
	}
	return nil
}

func renderBlock_10504f08610e7f96(ctx context.Context, data *RouteData) reactive.Binding {
	var b strings.Builder
	if err := func(w io.Writer) error {
//line index.html:2
		visitorsOnline := data.VisitorsOnline
//line index.html:3
		visitorsTone := data.VisitorsTone
		if _, err := io.WriteString(w, _html23); err != nil {
			return err
		}
//line index.html:23
		if err := render.Attr(w, visitorsTone); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
//line index.html:23
		if err := render.Text(w, visitorsOnline); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html24); err != nil {
			return err
		}
		return nil
	}(&b); err != nil {
		web.LogError(ctx, "live block not rendered", err, "route", routeKey, "block", "10504f08610e7f96")
		return reactive.HTMLBinding("")
	}
	return reactive.HTMLBinding(b.String())
}

func renderBlock_displayName(_ context.Context, data *RouteData) reactive.Binding {
	return reactive.TextBinding(render.Format(data.DisplayName))
}

const (
	_html0  = "<script type=\"application/json\" id=\"langs-data\">"
	_html1  = "</script> <section class=\"card\"> <img src=\"/_aicoded/assets/pages/home/logo-b373b5c1.svg\" alt width=\"64\" height=\"64\"> <h1>People</h1> <p id=\"intro\">"
	_html2  = "</p> </section> <div class=\"row\"> <section class=\"card\"> <h2>Live values</h2> <p><ssr-block data-ssr-bind=\"2cc974af.10504f08610e7f96\"><strong id=\"visitors\" class=\"badge "
	_html3  = "\">"
	_html4  = "</strong></ssr-block> home pages are open right now.</p> </section> <section class=\"card field\"> <label for=\"display-name\">Your display name</label> <input id=\"display-name\" type=\"text\" placeholder=\"Your name\" data-ssr-bind=\"2cc974af.displayName\" data-ssr-write> <p id=\"display-name-error\" class=\"error\"></p> <p id=\"greeting\">Hi, "
	_html5  = "<span data-ssr-bind=\"2cc974af.displayName\">"
	_html6  = "</span>!</p> </section> </div> <h2>Templates</h2> <div class=\"row\"> <section class=\"card\"> <h3>Arithmetic and fields</h3> <ul> <li>Price: <code id=\"price\">"
	_html7  = "</code></li> <li>Quantity: <code id=\"quantity\">"
	_html8  = "</code></li> <li>Total: <strong id=\"total\">"
	_html9  = "</strong></li> <li>"
	_html10 = " is <span id=\"age-check\">"
	_html11 = "</span>.</li> </ul> </section> <section class=\"card\"> <h3>Conditions</h3> <p>Status: <code>"
	_html12 = "</code></p> "
	_html13 = "<span id=\"status\" class=\"badge many\">Active</span>"
	_html14 = "<span id=\"status\" class=\"badge few\">Pending</span>"
	_html15 = "<span id=\"status\" class=\"badge\">Inactive</span>"
	_html16 = " </section> <section class=\"card\"> <h3>Loops</h3> <ul id=\"fruits\">"
	_html17 = "<li>"
	_html18 = "</li>"
	_html19 = "</ul> <ol id=\"langs\">"
	_html20 = "<li>#"
	_html21 = ": "
	_html22 = "</ol> <p id=\"script-note\"></p> </section> </div>"
	_html23 = "<strong id=\"visitors\" class=\"badge "
	_html24 = "</strong>"
)
