// Code generated by aicoded. DO NOT EDIT.

// Package contacts calls the functions of the app contacts through the runner.
package contacts

import (
	"context"

	"google.golang.org/protobuf/encoding/protowire"

	frameworkrpc "aicoded.dev/framework/rpc"
	"aicoded.dev/framework/rpc/wire"
)

// Contacts calls Contacts of the app contacts as the viewer of ctx, or as this app when ctx
// carries no viewer.
func Contacts(ctx context.Context, in ContactsIn) (ContactsOut, error) {
	b, err := frameworkrpc.Call(ctx, "contacts", "Contacts", in.aicodedAppend(nil))
	if err != nil {
		return ContactsOut{}, err
	}
	var out ContactsOut
	if err := wire.Decode(b, out.aicodedDecode); err != nil {
		return ContactsOut{}, err
	}
	return out, nil
}

type ContactsIn struct {
	Login string
}

func (x *ContactsIn) aicodedAppend(b []byte) []byte {
	if x.Login != "" {
		b = wire.AppendString(b, 1, x.Login)
	}
	return b
}

func (x *ContactsIn) aicodedDecode(n protowire.Number, v wire.Value) error {
	switch n {
	case 1:
		var err error
		x.Login, err = v.String()
		return err
	}
	return nil
}

type ContactsOut struct {
	Emails []string
	Phones []string
}

func (x *ContactsOut) aicodedAppend(b []byte) []byte {
	for _, v := range x.Emails {
		b = wire.AppendString(b, 1, v)
	}
	for _, v := range x.Phones {
		b = wire.AppendString(b, 2, v)
	}
	return b
}

func (x *ContactsOut) aicodedDecode(n protowire.Number, v wire.Value) error {
	switch n {
	case 1:
		e, err := v.String()
		if err != nil {
			return err
		}
		x.Emails = append(x.Emails, e)
	case 2:
		e, err := v.String()
		if err != nil {
			return err
		}
		x.Phones = append(x.Phones, e)
	}
	return nil
}
