// Code generated by aicoded. DO NOT EDIT.

package s_app

import (
	"context"
	"io"
	"net/http"
	"strings"
	"sync"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/form"
	"aicoded.dev/framework/web/reactive"
	"aicoded.dev/framework/web/render"
)

const routeKey = "b6a1a776"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	App  App
	Name string
}

// FormAutoValues holds the fields of the form auto.
type FormAutoValues struct {
	form.BaseFormValues
}

// FormManualValues holds the fields of the form manual.
type FormManualValues struct {
	form.BaseFormValues
}

// FormRestartValues holds the fields of the form restart.
type FormRestartValues struct {
	form.BaseFormValues
}

// FormStartValues holds the fields of the form start.
type FormStartValues struct {
	form.BaseFormValues
}

// FormStopValues holds the fields of the form stop.
type FormStopValues struct {
	form.BaseFormValues
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Guard(ctx context.Context, r *web.Request) error
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	InitAuto(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormAutoValues) error
	ProcessAuto(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormAutoValues) error
	InitManual(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormManualValues) error
	ProcessManual(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormManualValues) error
	InitRestart(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormRestartValues) error
	ProcessRestart(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormRestartValues) error
	InitStart(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormStartValues) error
	ProcessStart(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormStartValues) error
	InitStop(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormStopValues) error
	ProcessStop(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormStopValues) error
	// Subscribe runs while the page is open and must return when ctx is done.
	Subscribe(ctx context.Context, r *web.Request, state *ReactiveState) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route { return &route{dp: dp} }

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"developer"}} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/aicoded/reactive-ZRZHG67R.css\">", "<script defer src=\"/_aicoded/assets/aicoded/reactive-MTQXR3MF.js\"></script>", "<link rel=\"stylesheet\" href=\"/_aicoded/assets/pages/apps/s_app/index-ZMDA4INL.css\">"})
	s.FormAuto.SetElements([]form.Element{})
	s.FormManual.SetElements([]form.Element{})
	s.FormRestart.SetElements([]form.Element{})
	s.FormStart.SetElements([]form.Element{})
	s.FormStop.SetElements([]form.Element{})
	return s
}

type state struct {
	web.Frame
	mu          sync.Mutex
	dp          RouteDataProvider
	RouteData   RouteData
	FormAuto    FormAutoValues
	FormManual  FormManualValues
	FormRestart FormRestartValues
	FormStart   FormStartValues
	FormStop    FormStopValues
}

func (s *state) Guard(ctx context.Context, r *web.Request) error { return s.dp.Guard(ctx, r) }

func (s *state) InitForms(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	s.FormAuto.Prepare(routeKey+".auto", r.CSRFToken())
	if err := s.dp.InitAuto(ctx, r, w, &s.FormAuto); err != nil {
		return err
	}
	s.FormManual.Prepare(routeKey+".manual", r.CSRFToken())
	if err := s.dp.InitManual(ctx, r, w, &s.FormManual); err != nil {
		return err
	}
	s.FormRestart.Prepare(routeKey+".restart", r.CSRFToken())
	if err := s.dp.InitRestart(ctx, r, w, &s.FormRestart); err != nil {
		return err
	}
	s.FormStart.Prepare(routeKey+".start", r.CSRFToken())
	if err := s.dp.InitStart(ctx, r, w, &s.FormStart); err != nil {
		return err
	}
	s.FormStop.Prepare(routeKey+".stop", r.CSRFToken())
	if err := s.dp.InitStop(ctx, r, w, &s.FormStop); err != nil {
		return err
	}
	return nil
}

func (s *state) SubmitForm(ctx context.Context, r *web.Request, w web.ResponseWriter, id string) (bool, error) {
	switch id {
	case routeKey + ".auto":
		if form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormAuto.MarkValidated()
		if s.FormAuto.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessAuto(ctx, r, w, &s.FormAuto)
	case routeKey + ".manual":
		if form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormManual.MarkValidated()
		if s.FormManual.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessManual(ctx, r, w, &s.FormManual)
	case routeKey + ".restart":
		if form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormRestart.MarkValidated()
		if s.FormRestart.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessRestart(ctx, r, w, &s.FormRestart)
	case routeKey + ".start":
		if form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormStart.MarkValidated()
		if s.FormStart.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessStart(ctx, r, w, &s.FormStart)
	case routeKey + ".stop":
		if form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormStop.MarkValidated()
		if s.FormStop.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessStop(ctx, r, w, &s.FormStop)
	}
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) RouteKey() string { return routeKey }

func (s *state) Snapshot(ctx context.Context) map[string]reactive.Binding {
	s.mu.Lock()
	defer s.mu.Unlock()
	return map[string]reactive.Binding{
		routeKey + ".962f4beba91e658a": renderBlock_962f4beba91e658a(ctx, &s.RouteData),
		routeKey + ".a14e40c581600464": renderBlock_a14e40c581600464(ctx, &s.RouteData),
		routeKey + ".a33cd1c548f6391f": renderBlock_a33cd1c548f6391f(ctx, &s.RouteData),
		routeKey + ".aa39e6749c3460c8": renderBlock_aa39e6749c3460c8(ctx, &s.RouteData),
		routeKey + ".b4607e2d5eb9720b": renderBlock_b4607e2d5eb9720b(ctx, &s.RouteData),
	}
}

func (s *state) Subscribe(ctx context.Context, r *web.Request, conn *reactive.Conn) error {
	return s.dp.Subscribe(ctx, r, &ReactiveState{ctx: ctx, s: s, conn: conn})
}

func (s *state) HandleWrite(ctx context.Context, r *web.Request, conn *reactive.Conn, msg reactive.WriteMsg) {
	conn.Reject(ctx, msg, "unknown variable", reactive.CodeValidation)
}

// ReactiveState sends new values of the page's live variables to one open page. Its Set
// methods may be called from any goroutine.
type ReactiveState struct {
	ctx  context.Context
	s    *state
	conn *reactive.Conn
}

// SetApp stores v as app and sends the parts of the page that show it.
func (rs *ReactiveState) SetApp(v App) {
	rs.s.mu.Lock()
	defer rs.s.mu.Unlock()
	rs.s.RouteData.App = v
	rs.conn.Enqueue(routeKey+".962f4beba91e658a", renderBlock_962f4beba91e658a(rs.ctx, &rs.s.RouteData))
	rs.conn.Enqueue(routeKey+".a14e40c581600464", renderBlock_a14e40c581600464(rs.ctx, &rs.s.RouteData))
	rs.conn.Enqueue(routeKey+".a33cd1c548f6391f", renderBlock_a33cd1c548f6391f(rs.ctx, &rs.s.RouteData))
	rs.conn.Enqueue(routeKey+".aa39e6749c3460c8", renderBlock_aa39e6749c3460c8(rs.ctx, &rs.s.RouteData))
	rs.conn.Enqueue(routeKey+".b4607e2d5eb9720b", renderBlock_b4607e2d5eb9720b(rs.ctx, &rs.s.RouteData))
}

func (s *state) Write(w io.Writer) error {
//line index.html:3
	app := s.RouteData.App
	_ = app
//line index.html:2
	name := s.RouteData.Name
	_ = name
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:4
	if err := render.Text(w, name); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:7
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
	if err := render.Text(w, app.State); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html3); err != nil {
		return err
	}
//line index.html:9
	if err := render.Attr(w, app.Stamp); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
//line index.html:9
	if err := render.Text(w, app.Since); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html5); err != nil {
		return err
	}
//line index.html:11
	if _, err := io.WriteString(w, _html6); err != nil {
		return err
	}
	if app.URL != "" {
		if _, err := io.WriteString(w, _html7); err != nil {
			return err
		}
//line index.html:11
		if err := render.URL(w, app.URL); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html4); err != nil {
			return err
		}
//line index.html:11
		if err := render.Text(w, app.URL); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html8); err != nil {
			return err
		}
//line index.html:11
	} else {
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html10); err != nil {
		return err
	}
	{
		form := s.FormStart
		_ = form
		if _, err := io.WriteString(w, _html11); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html13); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html14); err != nil {
		return err
	}
	{
		form := s.FormRestart
		_ = form
		if _, err := io.WriteString(w, _html11); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html15); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html14); err != nil {
		return err
	}
	{
		form := s.FormStop
		_ = form
		if _, err := io.WriteString(w, _html11); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html16); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html17); err != nil {
		return err
	}
	{
		form := s.FormManual
		_ = form
		if _, err := io.WriteString(w, _html11); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html18); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html14); err != nil {
		return err
	}
	{
		form := s.FormAuto
		_ = form
		if _, err := io.WriteString(w, _html11); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html19); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html20); err != nil {
		return err
	}
//line index.html:23
	if _, err := io.WriteString(w, _html21); err != nil {
		return err
	}
	if app.Command != "" {
		if _, err := io.WriteString(w, _html22); err != nil {
			return err
		}
//line index.html:26
		if err := render.Text(w, app.Command); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html23); err != nil {
			return err
		}
//line index.html:28
		if err := render.Text(w, app.RunnerDir); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html24); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html25); err != nil {
		return err
	}
//line index.html:32
	if _, err := io.WriteString(w, _html26); err != nil {
		return err
	}
	if len(app.Problems) > 0 {
		if _, err := io.WriteString(w, _html27); err != nil {
			return err
		}
//line index.html:35
		for _, p := range app.Problems {
			if _, err := io.WriteString(w, _html28); err != nil {
				return err
			}
//line index.html:36
			if p.Code != "" {
				if _, err := io.WriteString(w, _html29); err != nil {
					return err
				}
//line index.html:36
				if err := render.Text(w, p.Code); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html30); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html14); err != nil {
				return err
			}
//line index.html:36
			if p.Pos != "" {
				if _, err := io.WriteString(w, _html31); err != nil {
					return err
				}
//line index.html:36
				if err := render.Text(w, p.Pos); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html32); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html33); err != nil {
				return err
			}
//line index.html:37
			if err := render.Text(w, p.Message); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html34); err != nil {
				return err
			}
//line index.html:38
			if p.Fix != "" {
				if _, err := io.WriteString(w, _html35); err != nil {
					return err
				}
//line index.html:38
				if err := render.Text(w, p.Fix); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html36); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html14); err != nil {
				return err
			}
//line index.html:39
			if p.Docs != "" {
				if _, err := io.WriteString(w, _html37); err != nil {
					return err
				}
//line index.html:39
				if err := render.URL(w, p.Docs); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html4); err != nil {
					return err
				}
//line index.html:39
				if err := render.Text(w, p.Docs); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html38); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html39); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html40); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html41); err != nil {
		return err
	}
	return nil
}

func renderBlock_962f4beba91e658a(ctx context.Context, data *RouteData) reactive.Binding {
	var b strings.Builder
	if err := func(w io.Writer) error {
//line index.html:3
		app := data.App
		if _, err := io.WriteString(w, _html42); err != nil {
			return err
		}
//line index.html:9
		if err := render.Attr(w, app.Stamp); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html4); err != nil {
			return err
		}
//line index.html:9
		if err := render.Text(w, app.Since); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html43); err != nil {
			return err
		}
		return nil
	}(&b); err != nil {
		web.LogError(ctx, "live block not rendered", err, "route", routeKey, "block", "962f4beba91e658a")
		return reactive.HTMLBinding("")
	}
	return reactive.HTMLBinding(b.String())
}

func renderBlock_a14e40c581600464(ctx context.Context, data *RouteData) reactive.Binding {
	var b strings.Builder
	if err := func(w io.Writer) error {
//line index.html:3
		app := data.App
//line index.html:32
		if len(app.Problems) > 0 {
			if _, err := io.WriteString(w, _html27); err != nil {
				return err
			}
//line index.html:35
			for _, p := range app.Problems {
				if _, err := io.WriteString(w, _html28); err != nil {
					return err
				}
//line index.html:36
				if p.Code != "" {
					if _, err := io.WriteString(w, _html29); err != nil {
						return err
					}
//line index.html:36
					if err := render.Text(w, p.Code); err != nil {
						return err
					}
					if _, err := io.WriteString(w, _html30); err != nil {
						return err
					}
				}
				if _, err := io.WriteString(w, _html14); err != nil {
					return err
				}
//line index.html:36
				if p.Pos != "" {
					if _, err := io.WriteString(w, _html31); err != nil {
						return err
					}
//line index.html:36
					if err := render.Text(w, p.Pos); err != nil {
						return err
					}
					if _, err := io.WriteString(w, _html32); err != nil {
						return err
					}
				}
				if _, err := io.WriteString(w, _html33); err != nil {
					return err
				}
//line index.html:37
				if err := render.Text(w, p.Message); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html34); err != nil {
					return err
				}
//line index.html:38
				if p.Fix != "" {
					if _, err := io.WriteString(w, _html35); err != nil {
						return err
					}
//line index.html:38
					if err := render.Text(w, p.Fix); err != nil {
						return err
					}
					if _, err := io.WriteString(w, _html36); err != nil {
						return err
					}
				}
				if _, err := io.WriteString(w, _html14); err != nil {
					return err
				}
//line index.html:39
				if p.Docs != "" {
					if _, err := io.WriteString(w, _html37); err != nil {
						return err
					}
//line index.html:39
					if err := render.URL(w, p.Docs); err != nil {
						return err
					}
					if _, err := io.WriteString(w, _html4); err != nil {
						return err
					}
//line index.html:39
					if err := render.Text(w, p.Docs); err != nil {
						return err
					}
					if _, err := io.WriteString(w, _html38); err != nil {
						return err
					}
				}
				if _, err := io.WriteString(w, _html39); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html40); err != nil {
				return err
			}
		}
		return nil
	}(&b); err != nil {
		web.LogError(ctx, "live block not rendered", err, "route", routeKey, "block", "a14e40c581600464")
		return reactive.HTMLBinding("")
	}
	return reactive.HTMLBinding(b.String())
}

func renderBlock_a33cd1c548f6391f(ctx context.Context, data *RouteData) reactive.Binding {
	var b strings.Builder
	if err := func(w io.Writer) error {
//line index.html:3
		app := data.App
//line index.html:23
		if app.Command != "" {
			if _, err := io.WriteString(w, _html22); err != nil {
				return err
			}
//line index.html:26
			if err := render.Text(w, app.Command); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html23); err != nil {
				return err
			}
//line index.html:28
			if err := render.Text(w, app.RunnerDir); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html24); err != nil {
				return err
			}
		}
		return nil
	}(&b); err != nil {
		web.LogError(ctx, "live block not rendered", err, "route", routeKey, "block", "a33cd1c548f6391f")
		return reactive.HTMLBinding("")
	}
	return reactive.HTMLBinding(b.String())
}

func renderBlock_aa39e6749c3460c8(ctx context.Context, data *RouteData) reactive.Binding {
	var b strings.Builder
	if err := func(w io.Writer) error {
//line index.html:3
		app := data.App
//line index.html:11
		if app.URL != "" {
			if _, err := io.WriteString(w, _html7); err != nil {
				return err
			}
//line index.html:11
			if err := render.URL(w, app.URL); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html4); err != nil {
				return err
			}
//line index.html:11
			if err := render.Text(w, app.URL); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
//line index.html:11
		} else {
			if _, err := io.WriteString(w, _html9); err != nil {
				return err
			}
		}
		return nil
	}(&b); err != nil {
		web.LogError(ctx, "live block not rendered", err, "route", routeKey, "block", "aa39e6749c3460c8")
		return reactive.HTMLBinding("")
	}
	return reactive.HTMLBinding(b.String())
}

func renderBlock_b4607e2d5eb9720b(_ context.Context, data *RouteData) reactive.Binding {
	{
//line index.html:3
		app := data.App
//line index.html:7
		return reactive.TextBinding(render.Format(app.State))
	}
}

const (
	_html0  = "<h1>"
	_html1  = "</h1> <dl> <dt>State</dt> <dd id=\"state\">"
	_html2  = "<span data-ssr-bind=\"b6a1a776.b4607e2d5eb9720b\">"
	_html3  = "</span></dd> <dt>Since</dt> <dd id=\"since\"><ssr-block data-ssr-bind=\"b6a1a776.962f4beba91e658a\"><time datetime=\""
	_html4  = "\">"
	_html5  = "</time></ssr-block></dd> <dt>Address</dt> <dd id=\"address\">"
	_html6  = "<ssr-block data-ssr-bind=\"b6a1a776.aa39e6749c3460c8\">"
	_html7  = "<a href=\""
	_html8  = "</a>"
	_html9  = "<span>The app has no pages.</span>"
	_html10 = "</ssr-block></dd> </dl> <div class=\"actions\"> "
	_html11 = "<form method=\"post\" enctype=\"application/x-www-form-urlencoded\"><input type=\"hidden\" name=\"_aicoded_form\" value=\""
	_html12 = "\"><input type=\"hidden\" name=\"_aicoded_csrf\" value=\""
	_html13 = "\"><button type=\"submit\">Start</button></form>"
	_html14 = " "
	_html15 = "\"><button type=\"submit\">Restart</button></form>"
	_html16 = "\"><button type=\"submit\">Stop</button></form>"
	_html17 = " </div> <div class=\"actions\"> "
	_html18 = "\"><button type=\"submit\">Run it yourself</button></form>"
	_html19 = "\"><button type=\"submit\">Let aicoded dev run it</button></form>"
	_html20 = " </div> <section id=\"manual\"> "
	_html21 = "<ssr-block data-ssr-bind=\"b6a1a776.a33cd1c548f6391f\">"
	_html22 = "<div> <h2>Run it yourself</h2> <p>aicoded dev keeps the app&#39;s runner up, and never builds or starts the app. Start it with:</p> <pre>"
	_html23 = "</pre> <p>To start it from a debugger, run it in its folder with the environment variable <code>AICODED_RUNNER_DIR</code> set to:</p> <pre>"
	_html24 = "</pre> </div>"
	_html25 = "</ssr-block> </section> <section id=\"problems\"> "
	_html26 = "<ssr-block data-ssr-bind=\"b6a1a776.a14e40c581600464\">"
	_html27 = "<div> <h2>Problems</h2> <ul> "
	_html28 = "<li> <p>"
	_html29 = "<strong>"
	_html30 = "</strong>"
	_html31 = "<code>"
	_html32 = "</code>"
	_html33 = "</p> <pre>"
	_html34 = "</pre> "
	_html35 = "<p>Fix: "
	_html36 = "</p>"
	_html37 = "<p><a href=\""
	_html38 = "</a></p>"
	_html39 = " </li>"
	_html40 = " </ul> </div>"
	_html41 = "</ssr-block> </section>"
	_html42 = "<time datetime=\""
	_html43 = "</time>"
)
