// Code generated by aicoded. DO NOT EDIT.

package s_app

import (
	"context"
	"io"
	"net/http"
	"strings"
	"sync"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/form"
	"aicoded.dev/framework/web/reactive"
	"aicoded.dev/framework/web/render"
)

const routeKey = "ec6bc9b3"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	App  string
	Mail []Message
}

// FormReceiveValues holds the fields of the form receive.
type FormReceiveValues struct {
	form.BaseFormValues
	From    form.Input[string]
	Subject form.Input[string]
	Text    form.Textarea
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Guard(ctx context.Context, r *web.Request) error
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	InitReceive(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormReceiveValues) error
	ProcessReceive(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormReceiveValues) error
	// Subscribe runs while the page is open and must return when ctx is done.
	Subscribe(ctx context.Context, r *web.Request, state *ReactiveState) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route { return &route{dp: dp} }

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"developer"}} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/aicoded/reactive-ZRZHG67R.css\">", "<script defer src=\"/_aicoded/assets/aicoded/reactive-MTQXR3MF.js\"></script>", "<link rel=\"stylesheet\" href=\"/_aicoded/assets/pages/mail/s_app/index-QKZEH6IE.css\">"})
	s.FormReceive.SetElements([]form.Element{&s.FormReceive.From, &s.FormReceive.Subject, &s.FormReceive.Text})
	return s
}

type state struct {
	web.Frame
	mu          sync.Mutex
	dp          RouteDataProvider
	RouteData   RouteData
	FormReceive FormReceiveValues
}

func (s *state) Guard(ctx context.Context, r *web.Request) error { return s.dp.Guard(ctx, r) }

func (s *state) InitForms(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	s.FormReceive.Prepare(routeKey+".receive", r.CSRFToken())
	if err := s.dp.InitReceive(ctx, r, w, &s.FormReceive); err != nil {
		return err
	}
	return nil
}

func (s *state) SubmitForm(ctx context.Context, r *web.Request, w web.ResponseWriter, id string) (bool, error) {
	switch id {
	case routeKey + ".receive":
		if form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormReceive.From.Process(r.Request, "from", false, true)
		s.FormReceive.Subject.Process(r.Request, "subject", false, false)
		s.FormReceive.Text.Process(r.Request, "text", false, false)
		s.FormReceive.MarkValidated()
		if s.FormReceive.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessReceive(ctx, r, w, &s.FormReceive)
	}
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) RouteKey() string { return routeKey }

func (s *state) Snapshot(ctx context.Context) map[string]reactive.Binding {
	s.mu.Lock()
	defer s.mu.Unlock()
	return map[string]reactive.Binding{
		routeKey + ".12059da99926ebad": renderBlock_12059da99926ebad(ctx, &s.RouteData),
	}
}

func (s *state) Subscribe(ctx context.Context, r *web.Request, conn *reactive.Conn) error {
	return s.dp.Subscribe(ctx, r, &ReactiveState{ctx: ctx, s: s, conn: conn})
}

func (s *state) HandleWrite(ctx context.Context, r *web.Request, conn *reactive.Conn, msg reactive.WriteMsg) {
	conn.Reject(ctx, msg, "unknown variable", reactive.CodeValidation)
}

// ReactiveState sends new values of the page's live variables to one open page. Its Set
// methods may be called from any goroutine.
type ReactiveState struct {
	ctx  context.Context
	s    *state
	conn *reactive.Conn
}

// SetMail stores v as mail and sends the parts of the page that show it.
func (rs *ReactiveState) SetMail(v []Message) {
	rs.s.mu.Lock()
	defer rs.s.mu.Unlock()
	rs.s.RouteData.Mail = v
	rs.conn.Enqueue(routeKey+".12059da99926ebad", renderBlock_12059da99926ebad(rs.ctx, &rs.s.RouteData))
}

func (s *state) Write(w io.Writer) error {
//line index.html:2
	app := s.RouteData.App
	_ = app
//line index.html:3
	mail := s.RouteData.Mail
	_ = mail
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:4
	if err := render.Text(w, app); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:6
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
	if len(mail) > 0 {
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
//line index.html:9
		for _, m := range mail {
			if _, err := io.WriteString(w, _html4); err != nil {
				return err
			}
//line index.html:9
			if err := render.Text(w, m.Folder); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html5); err != nil {
				return err
			}
//line index.html:9
			if err := render.Attr(w, m.Stamp); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html6); err != nil {
				return err
			}
//line index.html:9
			if err := render.Text(w, m.Time); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html7); err != nil {
				return err
			}
//line index.html:9
			if err := render.Text(w, m.From); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
//line index.html:9
			if err := render.Text(w, m.To); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html9); err != nil {
				return err
			}
//line index.html:9
			if err := render.URLPart(w, app); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html10); err != nil {
				return err
			}
//line index.html:9
			if err := render.URLPart(w, m.ID); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html6); err != nil {
				return err
			}
//line index.html:9
			if err := render.Text(w, render.If(m.Subject != "", m.Subject, "(no subject)")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
//line index.html:12
	} else {
		if _, err := io.WriteString(w, _html13); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html14); err != nil {
		return err
	}
	{
		form := s.FormReceive
		_ = form
		if _, err := io.WriteString(w, _html15); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html16); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html17); err != nil {
			return err
		}
		{
//line index.html:16
			input := form.From
			_ = input
			if _, err := io.WriteString(w, _html18); err != nil {
				return err
			}
			if input.IsNotNull() {
				if _, err := io.WriteString(w, _html19); err != nil {
					return err
				}
				v := any(input.GetValue())
				if input.HasError() {
					v = input.GetFormValue()
				}
				if err := render.Attr(w, v); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html20); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html21); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html22); err != nil {
			return err
		}
		{
//line index.html:17
			input := form.Subject
			_ = input
			if _, err := io.WriteString(w, _html23); err != nil {
				return err
			}
			if input.IsNotNull() {
				if _, err := io.WriteString(w, _html19); err != nil {
					return err
				}
				v := any(input.GetValue())
				if input.HasError() {
					v = input.GetFormValue()
				}
				if err := render.Attr(w, v); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html20); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html24); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html25); err != nil {
			return err
		}
		{
//line index.html:18
			textarea := form.Text
			_ = textarea
			if _, err := io.WriteString(w, _html26); err != nil {
				return err
			}
			if err := render.Text(w, textarea.GetValue()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html27); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html28); err != nil {
			return err
		}
//line index.html:19
		if form.GetError() != "" {
			if _, err := io.WriteString(w, _html29); err != nil {
				return err
			}
//line index.html:19
			if err := render.Text(w, form.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html30); err != nil {
				return err
			}
		} else {
//line index.html:20
			if form.HasError() {
				if _, err := io.WriteString(w, _html31); err != nil {
					return err
				}
			}
		}
		if _, err := io.WriteString(w, _html32); err != nil {
			return err
		}
	}
	return nil
}

func renderBlock_12059da99926ebad(ctx context.Context, data *RouteData) reactive.Binding {
	var b strings.Builder
	if err := func(w io.Writer) error {
//line index.html:2
		app := data.App
//line index.html:3
		mail := data.Mail
//line index.html:6
		if len(mail) > 0 {
			if _, err := io.WriteString(w, _html3); err != nil {
				return err
			}
//line index.html:9
			for _, m := range mail {
				if _, err := io.WriteString(w, _html4); err != nil {
					return err
				}
//line index.html:9
				if err := render.Text(w, m.Folder); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html5); err != nil {
					return err
				}
//line index.html:9
				if err := render.Attr(w, m.Stamp); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html6); err != nil {
					return err
				}
//line index.html:9
				if err := render.Text(w, m.Time); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html7); err != nil {
					return err
				}
//line index.html:9
				if err := render.Text(w, m.From); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html8); err != nil {
					return err
				}
//line index.html:9
				if err := render.Text(w, m.To); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html9); err != nil {
					return err
				}
//line index.html:9
				if err := render.URLPart(w, app); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html10); err != nil {
					return err
				}
//line index.html:9
				if err := render.URLPart(w, m.ID); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html6); err != nil {
					return err
				}
//line index.html:9
				if err := render.Text(w, render.If(m.Subject != "", m.Subject, "(no subject)")); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html11); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html12); err != nil {
				return err
			}
//line index.html:12
		} else {
			if _, err := io.WriteString(w, _html13); err != nil {
				return err
			}
		}
		return nil
	}(&b); err != nil {
		web.LogError(ctx, "live block not rendered", err, "route", routeKey, "block", "12059da99926ebad")
		return reactive.HTMLBinding("")
	}
	return reactive.HTMLBinding(b.String())
}

const (
	_html0  = "<h1>Mail of "
	_html1  = "</h1> <div id=\"messages\"> "
	_html2  = "<ssr-block data-ssr-bind=\"ec6bc9b3.12059da99926ebad\">"
	_html3  = "<table> <thead><tr><th>Folder</th><th>Time</th><th>From</th><th>To</th><th>Subject</th></tr></thead> <tbody> "
	_html4  = "<tr><td>"
	_html5  = "</td><td><time datetime=\""
	_html6  = "\">"
	_html7  = "</time></td><td>"
	_html8  = "</td><td>"
	_html9  = "</td><td><a href=\"/mail/"
	_html10 = "/"
	_html11 = "</a></td></tr>"
	_html12 = " </tbody> </table>"
	_html13 = "<p>No mail yet.</p>"
	_html14 = "</ssr-block> </div> <h2>Simulate inbound mail</h2> "
	_html15 = "<form method=\"post\" enctype=\"application/x-www-form-urlencoded\"><input type=\"hidden\" name=\"_aicoded_form\" value=\""
	_html16 = "\"><input type=\"hidden\" name=\"_aicoded_csrf\" value=\""
	_html17 = "\"> <label>From "
	_html18 = "<input name=\"from\" type=\"email\""
	_html19 = " value=\""
	_html20 = "\""
	_html21 = " required>"
	_html22 = "</label> <label>Subject "
	_html23 = "<input name=\"subject\" type=\"text\""
	_html24 = ">"
	_html25 = "</label> <label>Text "
	_html26 = "<textarea name=\"text\" rows=\"6\">"
	_html27 = "</textarea>"
	_html28 = "</label> "
	_html29 = "<p class=\"error\" id=\"receive-error\">"
	_html30 = "</p>"
	_html31 = "<p class=\"error\">Give the address the mail comes from.</p>"
	_html32 = " <button type=\"submit\">Put it in the inbox</button> </form>"
)
