// Code generated by aicoded. DO NOT EDIT.

package pages

import (
	"net/http"

	"aicoded.dev/framework/web"

	"people/deps"
	routeContact "people/pages/contact"
	routeHome "people/pages/home"
	routeUsers "people/pages/users"
	routeUsersAdd "people/pages/users/add"
	routeUsersS_login "people/pages/users/s_login"
	routeUsersS_loginContacts "people/pages/users/s_login/contacts"
	routeUsersS_loginInfo "people/pages/users/s_login/info"
)

// NewHandler returns the handler for the app's pages.
func NewHandler(d *deps.Deps) http.Handler {
	return web.New(map[string]web.Route{
		"/":                       NewRoute(NewDP(d)),
		"/contact":                routeContact.NewRoute(routeContact.NewDP(d)),
		"/home":                   routeHome.NewRoute(routeHome.NewDP(d)),
		"/users":                  routeUsers.NewRoute(routeUsers.NewDP(d)),
		"/users/add":              routeUsersAdd.NewRoute(routeUsersAdd.NewDP(d)),
		"/users/s_login":          routeUsersS_login.NewRoute(routeUsersS_login.NewDP(d)),
		"/users/s_login/contacts": routeUsersS_loginContacts.NewRoute(routeUsersS_loginContacts.NewDP(d)),
		"/users/s_login/info":     routeUsersS_loginInfo.NewRoute(routeUsersS_loginInfo.NewDP(d)),
	}, web.Options{Assets: assets})
}
