// Code generated by aicoded. DO NOT EDIT.

package pages

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "8a5edab2"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Section string
	Staff   bool
	Viewer  string
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"*"}} }

func (rt *route) Layout() bool { return true }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/pages/index-TOO5AASF.css\">"})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "home", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:11
	section := s.RouteData.Section
	_ = section
//line index.html:13
	staff := s.RouteData.Staff
	_ = staff
//line index.html:12
	viewer := s.RouteData.Viewer
	_ = viewer
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
	if err := s.WriteAssets(w); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:16
	if err := render.Attr(w, render.If(section == "home", "active", "")); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
//line index.html:17
	if staff {
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
//line index.html:17
		if err := render.Attr(w, render.If(section == "users", "active", "")); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html4); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html5); err != nil {
		return err
	}
//line index.html:18
	if err := render.Attr(w, render.If(section == "contact", "active", "")); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html6); err != nil {
		return err
	}
//line index.html:19
	if err := render.Text(w, viewer); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html7); err != nil {
		return err
	}
	if err := s.WriteChild(w); err != nil {
		return err
	}
//line route_gen.go:125
	if _, err := io.WriteString(w, _html8); err != nil {
		return err
	}
	return nil
}

const (
	_html0 = "<!doctype html> <html lang=\"en\"> <head> <meta charset=\"utf-8\"> <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> <title>People</title> "
	_html1 = " </head> <body> <nav> <a class=\"brand\" href=\"/home\">People</a> <a class=\""
	_html2 = "\" href=\"/home\">Home</a> "
	_html3 = "<a id=\"nav-users\" class=\""
	_html4 = "\" href=\"/users\">Users</a>"
	_html5 = " <a class=\""
	_html6 = "\" href=\"/contact\">Contact</a> <span id=\"viewer\" class=\"viewer\">"
	_html7 = "</span> </nav> <main> "
	_html8 = " </main> </body> </html>"
)
