// Code generated by aicoded. DO NOT EDIT.

package pages

import (
	"net/http"

	"aicoded.dev/framework/web"

	"shop/deps"
	routeChecks "shop/pages/checks"
	routeInvoicesN_id "shop/pages/invoices/n_id"
	routeStatus "shop/pages/status"
)

// NewHandler returns the handler for the app's pages.
func NewHandler(d *deps.Deps) http.Handler {
	return web.New(map[string]web.Route{
		"/":              NewRoute(NewDP(d)),
		"/checks":        routeChecks.NewRoute(routeChecks.NewDP(d)),
		"/invoices/n_id": routeInvoicesN_id.NewRoute(routeInvoicesN_id.NewDP(d)),
		"/status":        routeStatus.NewRoute(routeStatus.NewDP(d)),
	}, web.Options{Assets: assets})
}
