// Code generated by aicoded. DO NOT EDIT.

package pages

import (
	"net/http"

	"aicoded.dev/framework/web"

	"aicoded.dev/framework/cmd/aicoded/internal/devui/deps"
	routeApps "aicoded.dev/framework/cmd/aicoded/internal/devui/pages/apps"
	routeAppsS_app "aicoded.dev/framework/cmd/aicoded/internal/devui/pages/apps/s_app"
	routeLogs "aicoded.dev/framework/cmd/aicoded/internal/devui/pages/logs"
	routeMail "aicoded.dev/framework/cmd/aicoded/internal/devui/pages/mail"
	routeMailS_app "aicoded.dev/framework/cmd/aicoded/internal/devui/pages/mail/s_app"
	routeMailS_appS_id "aicoded.dev/framework/cmd/aicoded/internal/devui/pages/mail/s_app/s_id"
	routeMcp "aicoded.dev/framework/cmd/aicoded/internal/devui/pages/mcp"
	routePersonas "aicoded.dev/framework/cmd/aicoded/internal/devui/pages/personas"
	routeTraces "aicoded.dev/framework/cmd/aicoded/internal/devui/pages/traces"
	routeTracesS_id "aicoded.dev/framework/cmd/aicoded/internal/devui/pages/traces/s_id"
)

// NewHandler returns the handler for the app's pages.
func NewHandler(d *deps.Deps) http.Handler {
	return web.New(map[string]web.Route{
		"/":                NewRoute(NewDP(d)),
		"/apps":            routeApps.NewRoute(routeApps.NewDP(d)),
		"/apps/s_app":      routeAppsS_app.NewRoute(routeAppsS_app.NewDP(d)),
		"/logs":            routeLogs.NewRoute(routeLogs.NewDP(d)),
		"/mail":            routeMail.NewRoute(routeMail.NewDP(d)),
		"/mail/s_app":      routeMailS_app.NewRoute(routeMailS_app.NewDP(d)),
		"/mail/s_app/s_id": routeMailS_appS_id.NewRoute(routeMailS_appS_id.NewDP(d)),
		"/mcp":             routeMcp.NewRoute(routeMcp.NewDP(d)),
		"/personas":        routePersonas.NewRoute(routePersonas.NewDP(d)),
		"/traces":          routeTraces.NewRoute(routeTraces.NewDP(d)),
		"/traces/s_id":     routeTracesS_id.NewRoute(routeTracesS_id.NewDP(d)),
	}, web.Options{Assets: assets})
}
