// Code generated by aicoded. DO NOT EDIT.

package s_id

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "dabb9c25"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Trace Trace
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/traces/s_id")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/pages/traces/s_id/index-Z2H5CAAB.css\">"})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:1
	trace := s.RouteData.Trace
	_ = trace
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:2
	if err := render.Text(w, trace.ID); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:3
	if err := render.Text(w, trace.Duration); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
//line index.html:3
	if err := render.Text(w, trace.Apps); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html3); err != nil {
		return err
	}
//line index.html:3
	if err := render.URLQuery(w, trace.ID); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
//line index.html:7
	for _, sp := range trace.Spans {
		if _, err := io.WriteString(w, _html5); err != nil {
			return err
		}
//line index.html:7
		if err := render.Attr(w, sp.Depth); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html6); err != nil {
			return err
		}
//line index.html:7
		if err := render.Text(w, sp.Name); err != nil {
			return err
		}
//line index.html:7
		if len(sp.Attrs) > 0 {
			if _, err := io.WriteString(w, _html7); err != nil {
				return err
			}
//line index.html:7
			for _, a := range sp.Attrs {
				if _, err := io.WriteString(w, _html8); err != nil {
					return err
				}
//line index.html:7
				if err := render.Text(w, a.Key); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html9); err != nil {
					return err
				}
//line index.html:7
				if err := render.Text(w, a.Value); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html10); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
//line index.html:7
		if err := render.Text(w, sp.App); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html13); err != nil {
			return err
		}
//line index.html:7
		if err := render.Text(w, sp.Offset); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
//line index.html:7
		if err := render.Text(w, sp.Duration); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html14); err != nil {
			return err
		}
//line index.html:7
		if err := render.Attr(w, trace.Total); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html15); err != nil {
			return err
		}
//line index.html:7
		if err := render.Attr(w, sp.Length); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html16); err != nil {
			return err
		}
//line index.html:7
		if err := render.Text(w, sp.Error); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html17); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html18); err != nil {
		return err
	}
	return nil
}

const (
	_html0  = "<h1>Trace "
	_html1  = "</h1> <p>"
	_html2  = " in "
	_html3  = ". <a href=\"/logs?trace="
	_html4  = "\">Its log lines</a></p> <table id=\"spans\"> <thead><tr><th>Span</th><th>App</th><th>Start</th><th>Duration</th><th>Of the trace</th><th>Error</th></tr></thead> <tbody> "
	_html5  = "<tr><td class=\"depth-"
	_html6  = "\">"
	_html7  = "<ul class=\"attrs\">"
	_html8  = "<li>"
	_html9  = "="
	_html10 = "</li>"
	_html11 = "</ul>"
	_html12 = "</td><td>"
	_html13 = "</td><td>+"
	_html14 = "</td><td><meter min=\"0\" max=\""
	_html15 = "\" value=\""
	_html16 = "\"></meter></td><td class=\"error\">"
	_html17 = "</td></tr>"
	_html18 = " </tbody> </table>"
)
