// Code generated by aicoded. DO NOT EDIT.

package notes

import (
	"context"
	"io"
	"net/http"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/form"
	"aicoded.dev/framework/web/render"
)

const routeKey = "46bd1cc6"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Notes []Note
}

// FormAddValues holds the fields of the form add.
type FormAddValues struct {
	form.BaseFormValues
	Title    form.Input[string]
	Priority form.Select[int]
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	InitAdd(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormAddValues) error
	ProcessAdd(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormAddValues) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/notes")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"editor"}} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	s.FormAdd.SetElements([]form.Element{&s.FormAdd.Title, &s.FormAdd.Priority})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
	FormAdd   FormAddValues
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	s.FormAdd.Prepare(routeKey+".add", r.CSRFToken())
	if err := s.dp.InitAdd(ctx, r, w, &s.FormAdd); err != nil {
		return err
	}
	return nil
}

func (s *state) SubmitForm(ctx context.Context, r *web.Request, w web.ResponseWriter, id string) (bool, error) {
	switch id {
	case routeKey + ".add":
		if form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormAdd.Title.Process(r.Request, "title", false, true)
		s.FormAdd.Priority.Process(r.Request, "priority", false, true)
		s.FormAdd.MarkValidated()
		if s.FormAdd.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessAdd(ctx, r, w, &s.FormAdd)
	}
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:2
	notes := s.RouteData.Notes
	_ = notes
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:3
	for _, n := range notes {
		if _, err := io.WriteString(w, _html1); err != nil {
			return err
		}
//line index.html:3
		if err := render.URLPart(w, n.ID); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
//line index.html:3
		if err := render.Text(w, n.Title); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
	{
		form := s.FormAdd
		_ = form
		if _, err := io.WriteString(w, _html5); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html6); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html7); err != nil {
			return err
		}
		{
//line index.html:5
			input := form.Title
			_ = input
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
			if input.IsNotNull() {
				if _, err := io.WriteString(w, _html9); err != nil {
					return err
				}
				v := any(input.GetValue())
				if input.HasError() {
					v = input.GetFormValue()
				}
				if err := render.Attr(w, v); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html10); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
		{
//line index.html:6
			input := form.Priority
			_ = input
			if _, err := io.WriteString(w, _html13); err != nil {
				return err
			}
			isSelected := func(v int) bool { return v == input.GetValue() }
			for _, o := range input.GetOptions() {
				if err := o.WriteHtml(w, isSelected); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html14); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
//line index.html:7
		if form.HasError() {
			if _, err := io.WriteString(w, _html15); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html16); err != nil {
			return err
		}
	}
	return nil
}

const (
	_html0  = "<ul id=\"notes\">"
	_html1  = "<li><a href=\"/notes/"
	_html2  = "\">"
	_html3  = "</a></li>"
	_html4  = "</ul> "
	_html5  = "<form method=\"post\" enctype=\"application/x-www-form-urlencoded\"><input type=\"hidden\" name=\"_aicoded_form\" value=\""
	_html6  = "\"><input type=\"hidden\" name=\"_aicoded_csrf\" value=\""
	_html7  = "\"> "
	_html8  = "<input name=\"title\" type=\"text\""
	_html9  = " value=\""
	_html10 = "\""
	_html11 = " required>"
	_html12 = " "
	_html13 = "<select name=\"priority\" required>"
	_html14 = "</select>"
	_html15 = "<p id=\"form-error\">Check the form.</p>"
	_html16 = " <button type=\"submit\">Add</button> </form>"
)
