// Code generated by aicoded. DO NOT EDIT.

package rpc

import frameworkrpc "aicoded.dev/framework/rpc"

// Server returns the functions the app serves.
func Server() *frameworkrpc.Server { return frameworkrpc.NewServer() }
