// Code generated by aicoded. DO NOT EDIT.

package report

import (
	"context"
	"io"
	"net/http"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/form"
	"aicoded.dev/framework/web/render"
)

const routeKey = "38f212bb"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct{}

// FormReportValues holds the fields of the form report.
type FormReportValues struct {
	form.BaseFormValues
	Room    form.Select[int]
	Title   form.Input[string]
	Details form.Textarea
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	InitReport(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormReportValues) error
	ProcessReport(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormReportValues) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/tickets/report")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	s.FormReport.SetElements([]form.Element{&s.FormReport.Room, &s.FormReport.Title, &s.FormReport.Details})
	return s
}

type state struct {
	web.Frame
	dp         RouteDataProvider
	RouteData  RouteData
	FormReport FormReportValues
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	s.FormReport.Prepare(routeKey+".report", r.CSRFToken())
	if err := s.dp.InitReport(ctx, r, w, &s.FormReport); err != nil {
		return err
	}
	return nil
}

func (s *state) SubmitForm(ctx context.Context, r *web.Request, w web.ResponseWriter, id string) (bool, error) {
	switch id {
	case routeKey + ".report":
		if form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormReport.Room.Process(r.Request, "room", false, true)
		s.FormReport.Title.Process(r.Request, "title", false, true)
		s.FormReport.Details.Process(r.Request, "details", false, true)
		s.FormReport.MarkValidated()
		if s.FormReport.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessReport(ctx, r, w, &s.FormReport)
	}
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
	{
		form := s.FormReport
		_ = form
		if _, err := io.WriteString(w, _html1); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
		{
//line index.html:5
			input := form.Room
			_ = input
			if _, err := io.WriteString(w, _html4); err != nil {
				return err
			}
//line index.html:5
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(input.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html5); err != nil {
				return err
			}
			isSelected := func(v int) bool { return v == input.GetValue() }
			for _, o := range input.GetOptions() {
				if err := o.WriteHtml(w, isSelected); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html6); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html7); err != nil {
			return err
		}
//line index.html:7
		if form.Room.HasError() {
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
//line index.html:7
			if err := render.Text(w, form.Room.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html9); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html10); err != nil {
			return err
		}
		{
//line index.html:11
			input := form.Title
			_ = input
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
			if input.IsNotNull() {
				if _, err := io.WriteString(w, _html12); err != nil {
					return err
				}
				v := any(input.GetValue())
				if input.HasError() {
					v = input.GetFormValue()
				}
				if err := render.Attr(w, v); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html13); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html14); err != nil {
				return err
			}
//line index.html:11
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(input.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html5); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html7); err != nil {
			return err
		}
//line index.html:13
		if form.Title.HasError() {
			if _, err := io.WriteString(w, _html15); err != nil {
				return err
			}
//line index.html:13
			if err := render.Text(w, form.Title.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html9); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html16); err != nil {
			return err
		}
		{
//line index.html:17
			textarea := form.Details
			_ = textarea
			if _, err := io.WriteString(w, _html17); err != nil {
				return err
			}
//line index.html:17
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(textarea.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html5); err != nil {
				return err
			}
			if err := render.Text(w, textarea.GetValue()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html18); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html7); err != nil {
			return err
		}
//line index.html:19
		if form.Details.HasError() {
			if _, err := io.WriteString(w, _html19); err != nil {
				return err
			}
//line index.html:19
			if err := render.Text(w, form.Details.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html9); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html20); err != nil {
			return err
		}
	}
//line route_gen.go:254
	return nil
}

const (
	_html0  = "<h1>Report a problem</h1> "
	_html1  = "<form method=\"post\" enctype=\"application/x-www-form-urlencoded\"><input type=\"hidden\" name=\"_aicoded_form\" value=\""
	_html2  = "\"><input type=\"hidden\" name=\"_aicoded_csrf\" value=\""
	_html3  = "\"> <div class=\"field\"> <label for=\"room\">Room</label> "
	_html4  = "<select name=\"room\" required id=\"room\" class=\""
	_html5  = "\">"
	_html6  = "</select>"
	_html7  = " "
	_html8  = "<p id=\"room-error\" class=\"error\">"
	_html9  = "</p>"
	_html10 = " </div> <div class=\"field\"> <label for=\"title\">What is wrong</label> "
	_html11 = "<input name=\"title\" type=\"text\""
	_html12 = " value=\""
	_html13 = "\""
	_html14 = " required maxlength=\"100\" id=\"title\" class=\""
	_html15 = "<p id=\"title-error\" class=\"error\">"
	_html16 = " </div> <div class=\"field\"> <label for=\"details\">Details</label> "
	_html17 = "<textarea name=\"details\" required maxlength=\"2000\" rows=\"5\" id=\"details\" class=\""
	_html18 = "</textarea>"
	_html19 = "<p id=\"details-error\" class=\"error\">"
	_html20 = " </div> <button type=\"submit\">Report</button> </form>"
)
