// Code generated by aicoded. DO NOT EDIT.

package s_login

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "6baff01c"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Initials string
	Photos   []PhotoFile
	TabClass func(string) string
	User     User
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/users/s_login")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"staff"}} }

func (rt *route) Layout() bool { return true }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/pages/users/s_login/index-2LFQJA6K.css\">"})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "info", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:3
	initials := s.RouteData.Initials
	_ = initials
//line index.html:4
	photos := s.RouteData.Photos
	_ = photos
//line index.html:5
	tabClass := s.RouteData.TabClass
	_ = tabClass
//line index.html:2
	user := s.RouteData.User
	_ = user
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:7
	if err := render.Text(w, initials); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:9
	if err := render.Text(w, user.Name); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
//line index.html:11
	if err := render.Text(w, user.Login); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html3); err != nil {
		return err
	}
//line index.html:12
	if err := render.Text(w, user.Age); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
//line index.html:13
	for _, photo := range photos {
		if _, err := io.WriteString(w, _html5); err != nil {
			return err
		}
//line index.html:13
		if err := render.Text(w, photo.Name); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html6); err != nil {
			return err
		}
//line index.html:13
		if err := render.Text(w, photo.Size); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html7); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html8); err != nil {
		return err
	}
//line index.html:16
	if err := render.Attr(w, tabClass("info")); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html9); err != nil {
		return err
	}
//line index.html:16
	if err := render.URLPart(w, user.Login); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html10); err != nil {
		return err
	}
//line index.html:17
	if err := render.Attr(w, tabClass("contacts")); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html9); err != nil {
		return err
	}
//line index.html:17
	if err := render.URLPart(w, user.Login); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html11); err != nil {
		return err
	}
	if err := s.WriteChild(w); err != nil {
		return err
	}
//line route_gen.go:165
	return nil
}

const (
	_html0  = "<article class=\"card profile\"> <div id=\"avatar\" class=\"avatar\">"
	_html1  = "</div> <div> <h1 id=\"user-name\">"
	_html2  = "</h1> <ul> <li>Login: <strong id=\"user-login\">"
	_html3  = "</strong></li> <li>Age: <strong id=\"user-age\">"
	_html4  = "</strong></li> "
	_html5  = "<li class=\"photo\">Photo: "
	_html6  = ", "
	_html7  = " bytes</li>"
	_html8  = " </ul> <nav class=\"tabs\"> <a id=\"tab-info\" class=\""
	_html9  = "\" href=\"/users/"
	_html10 = "/info\">Info</a> <a id=\"tab-contacts\" class=\""
	_html11 = "/contacts\">Contacts</a> </nav> </div> </article> "
)
