// Code generated by aicoded. DO NOT EDIT.

package mail

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "aa537b28"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Apps []string
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/mail")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:1
	apps := s.RouteData.Apps
	_ = apps
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:4
	for _, a := range apps {
		if _, err := io.WriteString(w, _html1); err != nil {
			return err
		}
//line index.html:4
		if err := render.URLPart(w, a); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
//line index.html:4
		if err := render.Text(w, a); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
	}
//line route_gen.go:91
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
	return nil
}

const (
	_html0 = "<h1>Mail</h1> <p>aicoded dev keeps the mail each app sends, and sends none of it.</p> <ul id=\"apps\">"
	_html1 = "<li><a href=\"/mail/"
	_html2 = "\">"
	_html3 = "</a></li>"
	_html4 = "</ul>"
)
