// Code generated by aicoded. DO NOT EDIT.

package rpc

import (
	"context"

	"google.golang.org/protobuf/encoding/protowire"

	frameworkrpc "aicoded.dev/framework/rpc"
	"aicoded.dev/framework/rpc/wire"
)

// Server returns the functions of this package as the app serves them to other apps.
func Server() *frameworkrpc.Server {
	return frameworkrpc.NewServer(
		frameworkrpc.Method{
			Name:    "Contacts",
			Callers: []string{"people"},
			Require: []string{"staff"},
			Call: func(ctx context.Context, in []byte) ([]byte, error) {
				var x ContactsIn
				if err := wire.Decode(in, x.aicodedDecode); err != nil {
					return nil, frameworkrpc.DecodeError(err)
				}
				out, err := Contacts(ctx, x)
				if err != nil {
					return nil, err
				}
				return out.aicodedAppend(nil), nil
			},
		},
	)
}

func (x *ContactsIn) aicodedAppend(b []byte) []byte {
	if x.Login != "" {
		b = wire.AppendString(b, 1, x.Login)
	}
	return b
}

func (x *ContactsIn) aicodedDecode(n protowire.Number, v wire.Value) error {
	switch n {
	case 1:
		var err error
		x.Login, err = v.String()
		return err
	}
	return nil
}

func (x *ContactsOut) aicodedAppend(b []byte) []byte {
	for _, v := range x.Emails {
		b = wire.AppendString(b, 1, v)
	}
	for _, v := range x.Phones {
		b = wire.AppendString(b, 2, v)
	}
	return b
}

func (x *ContactsOut) aicodedDecode(n protowire.Number, v wire.Value) error {
	switch n {
	case 1:
		e, err := v.String()
		if err != nil {
			return err
		}
		x.Emails = append(x.Emails, e)
	case 2:
		e, err := v.String()
		if err != nil {
			return err
		}
		x.Phones = append(x.Phones, e)
	}
	return nil
}
