// Code generated by aicoded. DO NOT EDIT.

package edit

import (
	"context"
	"io"
	"net/http"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/form"
	"aicoded.dev/framework/web/render"
)

const routeKey = "3f969c1b"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct{}

// FormEditValues holds the fields of the form edit.
type FormEditValues struct {
	form.BaseFormValues
	Title   form.Input[string]
	Details form.Textarea
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Guard(ctx context.Context, r *web.Request) error
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	InitEdit(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormEditValues) error
	ProcessEdit(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormEditValues) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route { return &route{dp: dp} }

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"staff"}} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	s.FormEdit.SetElements([]form.Element{&s.FormEdit.Title, &s.FormEdit.Details})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
	FormEdit  FormEditValues
}

func (s *state) Guard(ctx context.Context, r *web.Request) error { return s.dp.Guard(ctx, r) }

func (s *state) InitForms(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	s.FormEdit.Prepare(routeKey+".edit", r.CSRFToken())
	if err := s.dp.InitEdit(ctx, r, w, &s.FormEdit); err != nil {
		return err
	}
	return nil
}

func (s *state) SubmitForm(ctx context.Context, r *web.Request, w web.ResponseWriter, id string) (bool, error) {
	switch id {
	case routeKey + ".edit":
		if form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormEdit.Title.Process(r.Request, "title", false, true)
		s.FormEdit.Details.Process(r.Request, "details", false, true)
		s.FormEdit.MarkValidated()
		if s.FormEdit.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessEdit(ctx, r, w, &s.FormEdit)
	}
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
	{
		form := s.FormEdit
		_ = form
		if _, err := io.WriteString(w, _html1); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
		{
//line index.html:6
			input := form.Title
			_ = input
			if _, err := io.WriteString(w, _html4); err != nil {
				return err
			}
			if input.IsNotNull() {
				if _, err := io.WriteString(w, _html5); err != nil {
					return err
				}
				v := any(input.GetValue())
				if input.HasError() {
					v = input.GetFormValue()
				}
				if err := render.Attr(w, v); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html6); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html7); err != nil {
				return err
			}
//line index.html:6
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(input.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
//line index.html:8
		if form.Title.HasError() {
			if _, err := io.WriteString(w, _html10); err != nil {
				return err
			}
//line index.html:8
			if err := render.Text(w, form.Title.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
		{
//line index.html:12
			textarea := form.Details
			_ = textarea
			if _, err := io.WriteString(w, _html13); err != nil {
				return err
			}
//line index.html:12
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(textarea.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
			if err := render.Text(w, textarea.GetValue()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html14); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
//line index.html:14
		if form.Details.HasError() {
			if _, err := io.WriteString(w, _html15); err != nil {
				return err
			}
//line index.html:14
			if err := render.Text(w, form.Details.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html16); err != nil {
			return err
		}
	}
	return nil
}

const (
	_html0  = "<h1>Edit the ticket</h1> "
	_html1  = "<form method=\"post\" enctype=\"application/x-www-form-urlencoded\"><input type=\"hidden\" name=\"_aicoded_form\" value=\""
	_html2  = "\"><input type=\"hidden\" name=\"_aicoded_csrf\" value=\""
	_html3  = "\"> <div class=\"field\"> <label for=\"title\">What is wrong</label> "
	_html4  = "<input name=\"title\" type=\"text\""
	_html5  = " value=\""
	_html6  = "\""
	_html7  = " required maxlength=\"100\" id=\"title\" class=\""
	_html8  = "\">"
	_html9  = " "
	_html10 = "<p id=\"title-error\" class=\"error\">"
	_html11 = "</p>"
	_html12 = " </div> <div class=\"field\"> <label for=\"details\">Details</label> "
	_html13 = "<textarea name=\"details\" required maxlength=\"2000\" rows=\"5\" id=\"details\" class=\""
	_html14 = "</textarea>"
	_html15 = "<p id=\"details-error\" class=\"error\">"
	_html16 = " </div> <button type=\"submit\">Save</button> </form>"
)
