// Code generated by aicoded. DO NOT EDIT.

package add

import (
	"context"
	"io"
	"net/http"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/form"
	"aicoded.dev/framework/web/render"
)

const routeKey = "8b217f88"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct{}

// FormAddValues holds the fields of the form add.
type FormAddValues struct {
	form.BaseFormValues
	Login     form.Input[string]
	Name      form.Input[string]
	Age       form.Input[uint8]
	Team      form.Select[string]
	Languages form.SelectMultiple[string]
	Remote    form.InputMultiple[bool]
	Shift     form.Input[uint8]
	Bio       form.Textarea
	Photo     form.File
	Photos    form.FileMultiple
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	InitAdd(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormAddValues) error
	ProcessAdd(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormAddValues) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/users/add")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"hr"}} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	s.FormAdd.SetElements([]form.Element{&s.FormAdd.Login, &s.FormAdd.Name, &s.FormAdd.Age, &s.FormAdd.Team, &s.FormAdd.Languages, &s.FormAdd.Remote, &s.FormAdd.Shift, &s.FormAdd.Bio, &s.FormAdd.Photo, &s.FormAdd.Photos})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
	FormAdd   FormAddValues
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	s.FormAdd.Prepare(routeKey+".add", r.CSRFToken())
	if err := s.dp.InitAdd(ctx, r, w, &s.FormAdd); err != nil {
		return err
	}
	return nil
}

func (s *state) SubmitForm(ctx context.Context, r *web.Request, w web.ResponseWriter, id string) (bool, error) {
	switch id {
	case routeKey + ".add":
		if !form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormAdd.Login.Process(r.Request, "login", true, true)
		s.FormAdd.Name.Process(r.Request, "name", true, true)
		s.FormAdd.Age.Process(r.Request, "age", true, true)
		s.FormAdd.Team.Process(r.Request, "team", true, true)
		s.FormAdd.Languages.Process(r.Request, "languages", true, false)
		s.FormAdd.Remote.Process(r.Request, "remote", true, false)
		s.FormAdd.Shift.Process(r.Request, "shift", true, true)
		s.FormAdd.Bio.Process(r.Request, "bio", true, true)
		s.FormAdd.Photo.Process(r.Request, "photo", true, true)
		s.FormAdd.Photos.Process(r.Request, "photos", true, false)
		s.FormAdd.MarkValidated()
		if s.FormAdd.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessAdd(ctx, r, w, &s.FormAdd)
	}
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
	{
		form := s.FormAdd
		_ = form
		if _, err := io.WriteString(w, _html1); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
		{
//line index.html:6
			input := form.Login
			_ = input
			if _, err := io.WriteString(w, _html4); err != nil {
				return err
			}
			if input.IsNotNull() {
				if _, err := io.WriteString(w, _html5); err != nil {
					return err
				}
				v := any(input.GetValue())
				if input.HasError() {
					v = input.GetFormValue()
				}
				if err := render.Attr(w, v); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html6); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html7); err != nil {
				return err
			}
//line index.html:6
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(input.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
//line index.html:8
		if form.Login.HasError() {
			if _, err := io.WriteString(w, _html10); err != nil {
				return err
			}
//line index.html:8
			if err := render.Text(w, form.Login.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
		{
//line index.html:12
			input := form.Name
			_ = input
			if _, err := io.WriteString(w, _html13); err != nil {
				return err
			}
			if input.IsNotNull() {
				if _, err := io.WriteString(w, _html5); err != nil {
					return err
				}
				v := any(input.GetValue())
				if input.HasError() {
					v = input.GetFormValue()
				}
				if err := render.Attr(w, v); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html6); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html14); err != nil {
				return err
			}
//line index.html:12
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(input.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
//line index.html:14
		if form.Name.HasError() {
			if _, err := io.WriteString(w, _html15); err != nil {
				return err
			}
//line index.html:14
			if err := render.Text(w, form.Name.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html16); err != nil {
			return err
		}
		{
//line index.html:18
			input := form.Age
			_ = input
			if _, err := io.WriteString(w, _html17); err != nil {
				return err
			}
			if input.IsNotNull() {
				if _, err := io.WriteString(w, _html5); err != nil {
					return err
				}
				v := any(input.GetValue())
				if input.HasError() {
					v = input.GetFormValue()
				}
				if err := render.Attr(w, v); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html6); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html18); err != nil {
				return err
			}
//line index.html:18
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(input.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
//line index.html:20
		if form.Age.HasError() {
			if _, err := io.WriteString(w, _html19); err != nil {
				return err
			}
//line index.html:20
			if err := render.Text(w, form.Age.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html20); err != nil {
			return err
		}
		{
//line index.html:24
			input := form.Team
			_ = input
			if _, err := io.WriteString(w, _html21); err != nil {
				return err
			}
//line index.html:24
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(input.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
			isSelected := func(v string) bool { return v == input.GetValue() }
			for _, o := range input.GetOptions() {
				if err := o.WriteHtml(w, isSelected); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html22); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
//line index.html:26
		if form.Team.HasError() {
			if _, err := io.WriteString(w, _html23); err != nil {
				return err
			}
//line index.html:26
			if err := render.Text(w, form.Team.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html24); err != nil {
			return err
		}
		{
//line index.html:30
			input := form.Languages
			_ = input
			if _, err := io.WriteString(w, _html25); err != nil {
				return err
			}
//line index.html:30
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(input.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
			isSelected := func(v string) bool { _, exists := input.GetValue()[v]; return exists }
			for _, o := range input.GetOptions() {
				if err := o.WriteHtml(w, isSelected); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html22); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
//line index.html:32
		if form.Languages.HasError() {
			if _, err := io.WriteString(w, _html26); err != nil {
				return err
			}
//line index.html:32
			if err := render.Text(w, form.Languages.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html27); err != nil {
			return err
		}
		{
//line index.html:36
			input := form.Remote
			_ = input
			if _, err := io.WriteString(w, _html28); err != nil {
				return err
			}
			if _, exists := input.GetValue()[false]; exists {
				if _, err := io.WriteString(w, _html29); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html30); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html31); err != nil {
			return err
		}
		{
//line index.html:37
			input := form.Remote
			_ = input
			if _, err := io.WriteString(w, _html32); err != nil {
				return err
			}
			if _, exists := input.GetValue()[true]; exists {
				if _, err := io.WriteString(w, _html29); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html33); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html34); err != nil {
			return err
		}
//line index.html:38
		if form.Remote.HasError() {
			if _, err := io.WriteString(w, _html35); err != nil {
				return err
			}
//line index.html:38
			if err := render.Text(w, form.Remote.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html36); err != nil {
			return err
		}
		{
//line index.html:42
			input := form.Shift
			_ = input
			if _, err := io.WriteString(w, _html37); err != nil {
				return err
			}
			if input.GetValue() == 1 {
				if _, err := io.WriteString(w, _html29); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html38); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html39); err != nil {
			return err
		}
		{
//line index.html:43
			input := form.Shift
			_ = input
			if _, err := io.WriteString(w, _html40); err != nil {
				return err
			}
			if input.GetValue() == 2 {
				if _, err := io.WriteString(w, _html29); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html41); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html42); err != nil {
			return err
		}
//line index.html:44
		if form.Shift.HasError() {
			if _, err := io.WriteString(w, _html43); err != nil {
				return err
			}
//line index.html:44
			if err := render.Text(w, form.Shift.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html44); err != nil {
			return err
		}
		{
//line index.html:48
			textarea := form.Bio
			_ = textarea
			if _, err := io.WriteString(w, _html45); err != nil {
				return err
			}
//line index.html:48
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(textarea.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
			if err := render.Text(w, textarea.GetValue()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html46); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
//line index.html:50
		if form.Bio.HasError() {
			if _, err := io.WriteString(w, _html47); err != nil {
				return err
			}
//line index.html:50
			if err := render.Text(w, form.Bio.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html48); err != nil {
			return err
		}
		{
//line index.html:54
			input := form.Photo
			_ = input
			if _, err := io.WriteString(w, _html49); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
//line index.html:55
		if form.Photo.HasError() {
			if _, err := io.WriteString(w, _html50); err != nil {
				return err
			}
//line index.html:55
			if err := render.Text(w, form.Photo.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html51); err != nil {
			return err
		}
		{
//line index.html:59
			input := form.Photos
			_ = input
			if _, err := io.WriteString(w, _html52); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
//line index.html:60
		if form.Photos.HasError() {
			if _, err := io.WriteString(w, _html53); err != nil {
				return err
			}
//line index.html:60
			if err := render.Text(w, form.Photos.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html54); err != nil {
			return err
		}
	}
	return nil
}

const (
	_html0  = "<h1>Add a user</h1> "
	_html1  = "<form method=\"post\" enctype=\"multipart/form-data\"><input type=\"hidden\" name=\"_aicoded_form\" value=\""
	_html2  = "\"><input type=\"hidden\" name=\"_aicoded_csrf\" value=\""
	_html3  = "\"> <div class=\"field\"> <label for=\"login\">Login</label> "
	_html4  = "<input name=\"login\" type=\"text\""
	_html5  = " value=\""
	_html6  = "\""
	_html7  = " required maxlength=\"32\" id=\"login\" class=\""
	_html8  = "\">"
	_html9  = " "
	_html10 = "<p id=\"login-error\" class=\"error\">"
	_html11 = "</p>"
	_html12 = " </div> <div class=\"field\"> <label for=\"name\">Name</label> "
	_html13 = "<input name=\"name\" type=\"text\""
	_html14 = " required maxlength=\"100\" id=\"name\" class=\""
	_html15 = "<p id=\"name-error\" class=\"error\">"
	_html16 = " </div> <div class=\"field\"> <label for=\"age\">Age</label> "
	_html17 = "<input name=\"age\" type=\"number\""
	_html18 = " required min=\"18\" max=\"120\" step=\"1\" id=\"age\" class=\""
	_html19 = "<p id=\"age-error\" class=\"error\">"
	_html20 = " </div> <div class=\"field\"> <label for=\"team\">Team</label> "
	_html21 = "<select name=\"team\" required id=\"team\" class=\""
	_html22 = "</select>"
	_html23 = "<p id=\"team-error\" class=\"error\">"
	_html24 = " </div> <div class=\"field\"> <label for=\"languages\">Languages</label> "
	_html25 = "<select name=\"languages\" multiple id=\"languages\" class=\""
	_html26 = "<p id=\"languages-error\" class=\"error\">"
	_html27 = " </div> <div class=\"field\"> <span>Works</span> <label>"
	_html28 = "<input name=\"remote\" type=\"checkbox\" value=\"false\""
	_html29 = " checked"
	_html30 = " id=\"on-site\">"
	_html31 = " on site</label> <label>"
	_html32 = "<input name=\"remote\" type=\"checkbox\" value=\"true\""
	_html33 = " id=\"remote\">"
	_html34 = " remotely</label> "
	_html35 = "<p id=\"remote-error\" class=\"error\">"
	_html36 = " </div> <div class=\"field\"> <span>Shift</span> <label>"
	_html37 = "<input name=\"shift\" type=\"radio\" value=\"1\""
	_html38 = " required id=\"day\">"
	_html39 = " day</label> <label>"
	_html40 = "<input name=\"shift\" type=\"radio\" value=\"2\""
	_html41 = " required id=\"night\">"
	_html42 = " night</label> "
	_html43 = "<p id=\"shift-error\" class=\"error\">"
	_html44 = " </div> <div class=\"field\"> <label for=\"bio\">About them</label> "
	_html45 = "<textarea name=\"bio\" required maxlength=\"2000\" rows=\"5\" id=\"bio\" class=\""
	_html46 = "</textarea>"
	_html47 = "<p id=\"bio-error\" class=\"error\">"
	_html48 = " </div> <div class=\"field\"> <label for=\"photo\">Photo</label> "
	_html49 = "<input name=\"photo\" type=\"file\" required accept=\"image/*\" id=\"photo\">"
	_html50 = "<p id=\"photo-error\" class=\"error\">"
	_html51 = " </div> <div class=\"field\"> <label for=\"photos\">More photos, up to 4</label> "
	_html52 = "<input name=\"photos\" type=\"file\" multiple accept=\"image/*\" id=\"photos\">"
	_html53 = "<p id=\"photos-error\" class=\"error\">"
	_html54 = " </div> <button type=\"submit\">Add</button> </form>"
)
