// Code generated by aicoded. DO NOT EDIT.

package settings

import (
	"context"
	"io"
	"net/http"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/form"
	"aicoded.dev/framework/web/render"
)

const routeKey = "f6245d45"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct{}

// FormSaveValues holds the fields of the form save.
type FormSaveValues struct {
	form.BaseFormValues
	Motto form.Input[string]
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	InitSave(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormSaveValues) error
	ProcessSave(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormSaveValues) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/admin/settings")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	s.FormSave.SetElements([]form.Element{&s.FormSave.Motto})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
	FormSave  FormSaveValues
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	s.FormSave.Prepare(routeKey+".save", r.CSRFToken())
	if err := s.dp.InitSave(ctx, r, w, &s.FormSave); err != nil {
		return err
	}
	return nil
}

func (s *state) SubmitForm(ctx context.Context, r *web.Request, w web.ResponseWriter, id string) (bool, error) {
	switch id {
	case routeKey + ".save":
		if form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormSave.Motto.Process(r.Request, "motto", false, false)
		s.FormSave.MarkValidated()
		if s.FormSave.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessSave(ctx, r, w, &s.FormSave)
	}
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
	{
		form := s.FormSave
		_ = form
		if _, err := io.WriteString(w, _html0); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html1); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
		{
//line index.html:2
			input := form.Motto
			_ = input
			if _, err := io.WriteString(w, _html3); err != nil {
				return err
			}
			if input.IsNotNull() {
				if _, err := io.WriteString(w, _html4); err != nil {
					return err
				}
				v := any(input.GetValue())
				if input.HasError() {
					v = input.GetFormValue()
				}
				if err := render.Attr(w, v); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html5); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html6); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html7); err != nil {
			return err
		}
	}
	return nil
}

const (
	_html0 = "<form method=\"post\" enctype=\"application/x-www-form-urlencoded\"><input type=\"hidden\" name=\"_aicoded_form\" value=\""
	_html1 = "\"><input type=\"hidden\" name=\"_aicoded_csrf\" value=\""
	_html2 = "\"> "
	_html3 = "<input name=\"motto\" type=\"text\""
	_html4 = " value=\""
	_html5 = "\""
	_html6 = ">"
	_html7 = " <button type=\"submit\">Save</button> </form>"
)
