// Code generated by aicoded. DO NOT EDIT.

package info

import (
	"context"
	"io"
	"sync"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/reactive"
	"aicoded.dev/framework/web/render"
)

const routeKey = "1135843f"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	LastSeen string
	User     User
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	// Subscribe runs while the page is open and must return when ctx is done.
	Subscribe(ctx context.Context, r *web.Request, state *ReactiveState) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/users/s_login/info")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/aicoded/reactive-ZRZHG67R.css\">", "<script defer src=\"/_aicoded/assets/aicoded/reactive-MTQXR3MF.js\"></script>"})
	return s
}

type state struct {
	web.Frame
	mu        sync.Mutex
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) RouteKey() string { return routeKey }

func (s *state) Snapshot(ctx context.Context) map[string]reactive.Binding {
	s.mu.Lock()
	defer s.mu.Unlock()
	return map[string]reactive.Binding{
		routeKey + ".lastSeen": renderBlock_lastSeen(ctx, &s.RouteData),
	}
}

func (s *state) Subscribe(ctx context.Context, r *web.Request, conn *reactive.Conn) error {
	return s.dp.Subscribe(ctx, r, &ReactiveState{ctx: ctx, s: s, conn: conn})
}

func (s *state) HandleWrite(ctx context.Context, r *web.Request, conn *reactive.Conn, msg reactive.WriteMsg) {
	conn.Reject(ctx, msg, "unknown variable", reactive.CodeValidation)
}

// ReactiveState sends new values of the page's live variables to one open page. Its Set
// methods may be called from any goroutine.
type ReactiveState struct {
	ctx  context.Context
	s    *state
	conn *reactive.Conn
}

// SetLastSeen stores v as lastSeen and sends the parts of the page that show it.
func (rs *ReactiveState) SetLastSeen(v string) {
	rs.s.mu.Lock()
	defer rs.s.mu.Unlock()
	rs.s.RouteData.LastSeen = v
	rs.conn.Enqueue(routeKey+".lastSeen", renderBlock_lastSeen(rs.ctx, &rs.s.RouteData))
}

func (s *state) Write(w io.Writer) error {
//line index.html:2
	lastSeen := s.RouteData.LastSeen
	_ = lastSeen
//line index.html:1
	user := s.RouteData.User
	_ = user
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:4
	if user.Age <= 18 {
		if _, err := io.WriteString(w, _html1); err != nil {
			return err
		}
	} else {
//line index.html:5
		if user.Age <= 30 {
			if _, err := io.WriteString(w, _html2); err != nil {
				return err
			}
		} else {
//line index.html:7
			if user.Age <= 60 {
				if _, err := io.WriteString(w, _html3); err != nil {
					return err
				}
//line index.html:8
			} else {
				if _, err := io.WriteString(w, _html4); err != nil {
					return err
				}
			}
		}
	}
	if _, err := io.WriteString(w, _html5); err != nil {
		return err
	}
//line index.html:12
	if err := render.Text(w, user.Team); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html6); err != nil {
		return err
	}
//line index.html:14
	if err := render.Text(w, render.If(user.Languages == "", "none given", user.Languages)); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html7); err != nil {
		return err
	}
//line index.html:17
	if user.OnSite && user.Remote {
		if _, err := io.WriteString(w, _html8); err != nil {
			return err
		}
	} else {
//line index.html:18
		if user.Remote {
			if _, err := io.WriteString(w, _html9); err != nil {
				return err
			}
//line index.html:19
		} else {
			if _, err := io.WriteString(w, _html10); err != nil {
				return err
			}
		}
	}
	if _, err := io.WriteString(w, _html11); err != nil {
		return err
	}
//line index.html:22
	if err := render.Text(w, render.If(user.Shift == 2, "night", "day")); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html12); err != nil {
		return err
	}
//line index.html:24
	if err := render.Text(w, user.Bio); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html13); err != nil {
		return err
	}
//line index.html:25
	if _, err := io.WriteString(w, _html14); err != nil {
		return err
	}
	if err := render.Text(w, lastSeen); err != nil {
		return err
	}
//line route_gen.go:198
	if _, err := io.WriteString(w, _html15); err != nil {
		return err
	}
	return nil
}

func renderBlock_lastSeen(_ context.Context, data *RouteData) reactive.Binding {
	return reactive.TextBinding(render.Format(data.LastSeen))
}

const (
	_html0  = "<h2>Age group: "
	_html1  = "<span id=\"age-group\">0-18</span>"
	_html2  = "<span id=\"age-group\">19-30</span>"
	_html3  = "<span id=\"age-group\">31-60</span>"
	_html4  = "<span id=\"age-group\">60+</span>"
	_html5  = " </h2> <dl> <dt>Team</dt> <dd id=\"team\">"
	_html6  = "</dd> <dt>Languages</dt> <dd id=\"languages\">"
	_html7  = "</dd> <dt>Works</dt> <dd id=\"works\"> "
	_html8  = "<span>on site and remotely</span>"
	_html9  = "<span>remotely</span>"
	_html10 = "<span>on site</span>"
	_html11 = " </dd> <dt>Shift</dt> <dd id=\"shift\">"
	_html12 = "</dd> </dl> <p id=\"bio\">"
	_html13 = "</p> <p class=\"muted\">Last opened a page: <span id=\"last-seen\">"
	_html14 = "<span data-ssr-bind=\"1135843f.lastSeen\">"
	_html15 = "</span></span></p>"
)
