// Code generated by aicoded. DO NOT EDIT.

package rpc

import (
	"context"

	"google.golang.org/protobuf/encoding/protowire"

	frameworkrpc "aicoded.dev/framework/rpc"
	"aicoded.dev/framework/rpc/wire"
)

// Server returns the functions of this package as the app serves them to other apps.
func Server() *frameworkrpc.Server {
	return frameworkrpc.NewServer(
		frameworkrpc.Method{
			Name:    "Fail",
			Callers: []string{"shop"},
			Require: []string{"*"},
			Call: func(ctx context.Context, in []byte) ([]byte, error) {
				var x InvoiceID
				if err := wire.Decode(in, x.aicodedDecode); err != nil {
					return nil, frameworkrpc.DecodeError(err)
				}
				out, err := Fail(ctx, x)
				if err != nil {
					return nil, err
				}
				return out.aicodedAppend(nil), nil
			},
		},
		frameworkrpc.Method{
			Name:    "GetInvoice",
			Callers: []string{"shop"},
			Require: []string{"editor"},
			Call: func(ctx context.Context, in []byte) ([]byte, error) {
				var x InvoiceID
				if err := wire.Decode(in, x.aicodedDecode); err != nil {
					return nil, frameworkrpc.DecodeError(err)
				}
				out, err := GetInvoice(ctx, x)
				if err != nil {
					return nil, err
				}
				return out.aicodedAppend(nil), nil
			},
		},
		frameworkrpc.Method{
			Name:    "Missing",
			Callers: []string{"shop"},
			Require: []string{"*"},
			Call: func(ctx context.Context, in []byte) ([]byte, error) {
				var x InvoiceID
				if err := wire.Decode(in, x.aicodedDecode); err != nil {
					return nil, frameworkrpc.DecodeError(err)
				}
				out, err := Missing(ctx, x)
				if err != nil {
					return nil, err
				}
				return out.aicodedAppend(nil), nil
			},
		},
		frameworkrpc.Method{
			Name:    "Ping",
			Callers: []string{"shop"},
			Apps:    true,
			Call: func(ctx context.Context, in []byte) ([]byte, error) {
				var x PingIn
				if err := wire.Decode(in, x.aicodedDecode); err != nil {
					return nil, frameworkrpc.DecodeError(err)
				}
				out, err := Ping(ctx, x)
				if err != nil {
					return nil, err
				}
				return out.aicodedAppend(nil), nil
			},
		},
		frameworkrpc.Method{
			Name:    "Secret",
			Callers: []string{"shop"},
			Require: []string{"admin"},
			Call: func(ctx context.Context, in []byte) ([]byte, error) {
				var x PingIn
				if err := wire.Decode(in, x.aicodedDecode); err != nil {
					return nil, frameworkrpc.DecodeError(err)
				}
				out, err := Secret(ctx, x)
				if err != nil {
					return nil, err
				}
				return out.aicodedAppend(nil), nil
			},
		},
	)
}

func (x *Invoice) aicodedAppend(b []byte) []byte {
	if x.Customer != "" {
		b = wire.AppendString(b, 1, x.Customer)
	}
	if !x.Due.IsZero() {
		b = wire.AppendTime(b, 2, x.Due)
	}
	if x.ID != 0 {
		b = wire.AppendInt64(b, 3, x.ID)
	}
	for i := range x.Lines {
		b = wire.AppendMessage(b, 4, x.Lines[i].aicodedAppend)
	}
	if x.Paid != nil {
		b = wire.AppendBool(b, 5, *x.Paid)
	}
	if x.Viewer != "" {
		b = wire.AppendString(b, 6, x.Viewer)
	}
	return b
}

func (x *Invoice) aicodedDecode(n protowire.Number, v wire.Value) error {
	switch n {
	case 1:
		var err error
		x.Customer, err = v.String()
		return err
	case 2:
		var err error
		x.Due, err = v.Time()
		return err
	case 3:
		var err error
		x.ID, err = v.Int64()
		return err
	case 4:
		var e Line
		if err := v.Decode(e.aicodedDecode); err != nil {
			return err
		}
		x.Lines = append(x.Lines, e)
	case 5:
		e, err := v.Bool()
		if err != nil {
			return err
		}
		x.Paid = &e
	case 6:
		var err error
		x.Viewer, err = v.String()
		return err
	}
	return nil
}

func (x *InvoiceID) aicodedAppend(b []byte) []byte {
	if x.ID != 0 {
		b = wire.AppendInt64(b, 1, x.ID)
	}
	return b
}

func (x *InvoiceID) aicodedDecode(n protowire.Number, v wire.Value) error {
	switch n {
	case 1:
		var err error
		x.ID, err = v.Int64()
		return err
	}
	return nil
}

func (x *Line) aicodedAppend(b []byte) []byte {
	if x.Amount != 0 {
		b = wire.AppendInt64(b, 1, x.Amount)
	}
	if x.Item != "" {
		b = wire.AppendString(b, 2, x.Item)
	}
	return b
}

func (x *Line) aicodedDecode(n protowire.Number, v wire.Value) error {
	switch n {
	case 1:
		var err error
		x.Amount, err = v.Int64()
		return err
	case 2:
		var err error
		x.Item, err = v.String()
		return err
	}
	return nil
}

func (x *PingIn) aicodedAppend(b []byte) []byte {
	return b
}

func (x *PingIn) aicodedDecode(protowire.Number, wire.Value) error {
	return nil
}

func (x *PingOut) aicodedAppend(b []byte) []byte {
	if x.Caller != "" {
		b = wire.AppendString(b, 1, x.Caller)
	}
	if x.Viewer != "" {
		b = wire.AppendString(b, 2, x.Viewer)
	}
	return b
}

func (x *PingOut) aicodedDecode(n protowire.Number, v wire.Value) error {
	switch n {
	case 1:
		var err error
		x.Caller, err = v.String()
		return err
	case 2:
		var err error
		x.Viewer, err = v.String()
		return err
	}
	return nil
}
