// Code generated by aicoded. DO NOT EDIT.

package pages

import (
	"net/http"

	"aicoded.dev/framework/web"

	"site/deps"
	routeAdmin "site/pages/admin"
	routeAdminLive "site/pages/admin/live"
	routeAdminSettings "site/pages/admin/settings"
	routeHome "site/pages/home"
	routeNotes "site/pages/notes"
	routeNotesN_id "site/pages/notes/n_id"
)

// NewHandler returns the handler for the app's pages.
func NewHandler(d *deps.Deps) http.Handler {
	return web.New(map[string]web.Route{
		"/":               NewRoute(NewDP(d)),
		"/admin":          routeAdmin.NewRoute(routeAdmin.NewDP(d)),
		"/admin/live":     routeAdminLive.NewRoute(routeAdminLive.NewDP(d)),
		"/admin/settings": routeAdminSettings.NewRoute(routeAdminSettings.NewDP(d)),
		"/home":           routeHome.NewRoute(routeHome.NewDP(d)),
		"/notes":          routeNotes.NewRoute(routeNotes.NewDP(d)),
		"/notes/n_id":     routeNotesN_id.NewRoute(routeNotesN_id.NewDP(d)),
	}, web.Options{Assets: assets})
}
