// Code generated by aicoded. DO NOT EDIT.

package pages

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "8a5edab2"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Viewer string
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"*"}} }

func (rt *route) Layout() bool { return true }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/pages/index-PSHGIUE4.css\">"})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "/home", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:10
	viewer := s.RouteData.Viewer
	_ = viewer
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
	if err := s.WriteAssets(w); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:11
	if err := render.Text(w, viewer); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
	if err := s.WriteChild(w); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html3); err != nil {
		return err
	}
	return nil
}

const (
	_html0 = "<!doctype html> <html lang=\"en\"> <head> <meta charset=\"utf-8\"> <title>Site</title> "
	_html1 = " </head> <body> <p id=\"viewer\">"
	_html2 = "</p> "
	_html3 = " </body> </html>"
)
