// Code generated by aicoded. DO NOT EDIT.

package logs

import (
	"context"
	"io"
	"strings"
	"sync"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/reactive"
	"aicoded.dev/framework/web/render"
)

const routeKey = "c06682b7"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Logs  Logs
	Names []string
	Query Query
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	// Subscribe runs while the page is open and must return when ctx is done.
	Subscribe(ctx context.Context, r *web.Request, state *ReactiveState) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/logs")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/aicoded/reactive-ZRZHG67R.css\">", "<script defer src=\"/_aicoded/assets/aicoded/reactive-MTQXR3MF.js\"></script>", "<link rel=\"stylesheet\" href=\"/_aicoded/assets/pages/logs/index-FWPYPJ6D.css\">"})
	return s
}

type state struct {
	web.Frame
	mu        sync.Mutex
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) RouteKey() string { return routeKey }

func (s *state) Snapshot(ctx context.Context) map[string]reactive.Binding {
	s.mu.Lock()
	defer s.mu.Unlock()
	return map[string]reactive.Binding{
		routeKey + ".28dc75079adb2065": renderBlock_28dc75079adb2065(ctx, &s.RouteData),
		routeKey + ".2e41d7b8ba5f6dc1": renderBlock_2e41d7b8ba5f6dc1(ctx, &s.RouteData),
		routeKey + ".de4e69426c275cdb": renderBlock_de4e69426c275cdb(ctx, &s.RouteData),
	}
}

func (s *state) Subscribe(ctx context.Context, r *web.Request, conn *reactive.Conn) error {
	return s.dp.Subscribe(ctx, r, &ReactiveState{ctx: ctx, s: s, conn: conn})
}

func (s *state) HandleWrite(ctx context.Context, r *web.Request, conn *reactive.Conn, msg reactive.WriteMsg) {
	conn.Reject(ctx, msg, "unknown variable", reactive.CodeValidation)
}

// ReactiveState sends new values of the page's live variables to one open page. Its Set
// methods may be called from any goroutine.
type ReactiveState struct {
	ctx  context.Context
	s    *state
	conn *reactive.Conn
}

// SetLogs stores v as logs and sends the parts of the page that show it.
func (rs *ReactiveState) SetLogs(v Logs) {
	rs.s.mu.Lock()
	defer rs.s.mu.Unlock()
	rs.s.RouteData.Logs = v
	rs.conn.Enqueue(routeKey+".28dc75079adb2065", renderBlock_28dc75079adb2065(rs.ctx, &rs.s.RouteData))
	rs.conn.Enqueue(routeKey+".2e41d7b8ba5f6dc1", renderBlock_2e41d7b8ba5f6dc1(rs.ctx, &rs.s.RouteData))
	rs.conn.Enqueue(routeKey+".de4e69426c275cdb", renderBlock_de4e69426c275cdb(rs.ctx, &rs.s.RouteData))
}

func (s *state) Write(w io.Writer) error {
//line index.html:3
	logs := s.RouteData.Logs
	_ = logs
//line index.html:1
	names := s.RouteData.Names
	_ = names
//line index.html:2
	query := s.RouteData.Query
	_ = query
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:6
	if err := render.Attr(w, query.App); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:7
	for _, n := range names {
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
//line index.html:7
		if err := render.Attr(w, n); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
//line index.html:8
	if err := render.Attr(w, query.Level); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html5); err != nil {
		return err
	}
//line index.html:10
	if err := render.Attr(w, query.Contains); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html6); err != nil {
		return err
	}
//line index.html:11
	if err := render.Attr(w, query.TraceID); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html7); err != nil {
		return err
	}
//line index.html:14
	if _, err := io.WriteString(w, _html8); err != nil {
		return err
	}
	for _, a := range logs.Manual {
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
//line index.html:14
		if err := render.Text(w, a); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html10); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html11); err != nil {
		return err
	}
//line index.html:15
	if _, err := io.WriteString(w, _html12); err != nil {
		return err
	}
	if logs.Problem != "" {
		if _, err := io.WriteString(w, _html13); err != nil {
			return err
		}
//line index.html:15
		if err := render.Text(w, logs.Problem); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html14); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html15); err != nil {
		return err
	}
//line index.html:17
	if _, err := io.WriteString(w, _html16); err != nil {
		return err
	}
	if len(logs.Entries) > 0 {
		if _, err := io.WriteString(w, _html17); err != nil {
			return err
		}
//line index.html:20
		for _, e := range logs.Entries {
			if _, err := io.WriteString(w, _html18); err != nil {
				return err
			}
//line index.html:20
			if err := render.Attr(w, e.Class); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html19); err != nil {
				return err
			}
//line index.html:20
			if err := render.Attr(w, e.Stamp); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html20); err != nil {
				return err
			}
//line index.html:20
			if err := render.Text(w, e.Time); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html21); err != nil {
				return err
			}
//line index.html:20
			if err := render.Text(w, e.App); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html22); err != nil {
				return err
			}
//line index.html:20
			if err := render.Text(w, e.Source); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html22); err != nil {
				return err
			}
//line index.html:20
			if err := render.Text(w, e.Level); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html23); err != nil {
				return err
			}
//line index.html:20
			if err := render.Text(w, e.Message); err != nil {
				return err
			}
//line index.html:20
			if e.Attrs != "" {
				if _, err := io.WriteString(w, _html24); err != nil {
					return err
				}
//line index.html:20
				if err := render.Text(w, e.Attrs); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html25); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html22); err != nil {
				return err
			}
//line index.html:20
			if e.Trace != "" {
				if _, err := io.WriteString(w, _html26); err != nil {
					return err
				}
//line index.html:20
				if err := render.URLPart(w, e.Trace); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html27); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html28); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html29); err != nil {
			return err
		}
//line index.html:23
	} else {
		if _, err := io.WriteString(w, _html30); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html31); err != nil {
		return err
	}
	return nil
}

func renderBlock_28dc75079adb2065(ctx context.Context, data *RouteData) reactive.Binding {
	var b strings.Builder
	if err := func(w io.Writer) error {
//line index.html:3
		logs := data.Logs
//line index.html:17
		if len(logs.Entries) > 0 {
			if _, err := io.WriteString(w, _html17); err != nil {
				return err
			}
//line index.html:20
			for _, e := range logs.Entries {
				if _, err := io.WriteString(w, _html18); err != nil {
					return err
				}
//line index.html:20
				if err := render.Attr(w, e.Class); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html19); err != nil {
					return err
				}
//line index.html:20
				if err := render.Attr(w, e.Stamp); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html20); err != nil {
					return err
				}
//line index.html:20
				if err := render.Text(w, e.Time); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html21); err != nil {
					return err
				}
//line index.html:20
				if err := render.Text(w, e.App); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html22); err != nil {
					return err
				}
//line index.html:20
				if err := render.Text(w, e.Source); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html22); err != nil {
					return err
				}
//line index.html:20
				if err := render.Text(w, e.Level); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html23); err != nil {
					return err
				}
//line index.html:20
				if err := render.Text(w, e.Message); err != nil {
					return err
				}
//line index.html:20
				if e.Attrs != "" {
					if _, err := io.WriteString(w, _html24); err != nil {
						return err
					}
//line index.html:20
					if err := render.Text(w, e.Attrs); err != nil {
						return err
					}
					if _, err := io.WriteString(w, _html25); err != nil {
						return err
					}
				}
				if _, err := io.WriteString(w, _html22); err != nil {
					return err
				}
//line index.html:20
				if e.Trace != "" {
					if _, err := io.WriteString(w, _html26); err != nil {
						return err
					}
//line index.html:20
					if err := render.URLPart(w, e.Trace); err != nil {
						return err
					}
					if _, err := io.WriteString(w, _html27); err != nil {
						return err
					}
				}
				if _, err := io.WriteString(w, _html28); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html29); err != nil {
				return err
			}
//line index.html:23
		} else {
			if _, err := io.WriteString(w, _html30); err != nil {
				return err
			}
		}
		return nil
	}(&b); err != nil {
		web.LogError(ctx, "live block not rendered", err, "route", routeKey, "block", "28dc75079adb2065")
		return reactive.HTMLBinding("")
	}
	return reactive.HTMLBinding(b.String())
}

func renderBlock_2e41d7b8ba5f6dc1(ctx context.Context, data *RouteData) reactive.Binding {
	var b strings.Builder
	if err := func(w io.Writer) error {
//line index.html:3
		logs := data.Logs
//line index.html:14
		for _, a := range logs.Manual {
			if _, err := io.WriteString(w, _html9); err != nil {
				return err
			}
//line index.html:14
			if err := render.Text(w, a); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html10); err != nil {
				return err
			}
		}
		return nil
	}(&b); err != nil {
		web.LogError(ctx, "live block not rendered", err, "route", routeKey, "block", "2e41d7b8ba5f6dc1")
		return reactive.HTMLBinding("")
	}
	return reactive.HTMLBinding(b.String())
}

func renderBlock_de4e69426c275cdb(ctx context.Context, data *RouteData) reactive.Binding {
	var b strings.Builder
	if err := func(w io.Writer) error {
//line index.html:3
		logs := data.Logs
//line index.html:15
		if logs.Problem != "" {
			if _, err := io.WriteString(w, _html13); err != nil {
				return err
			}
//line index.html:15
			if err := render.Text(w, logs.Problem); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html14); err != nil {
				return err
			}
		}
		return nil
	}(&b); err != nil {
		web.LogError(ctx, "live block not rendered", err, "route", routeKey, "block", "de4e69426c275cdb")
		return reactive.HTMLBinding("")
	}
	return reactive.HTMLBinding(b.String())
}

const (
	_html0  = "<h1>Logs</h1> <form method=\"get\" action=\"/logs\" id=\"filter\"> <label>App <input name=\"app\" list=\"app-names\" value=\""
	_html1  = "\"></label> <datalist id=\"app-names\">"
	_html2  = "<option value=\""
	_html3  = "\"></option>"
	_html4  = "</datalist> <label>Lowest level <input name=\"level\" list=\"levels\" value=\""
	_html5  = "\"></label> <datalist id=\"levels\"><option value=\"DEBUG\"></option><option value=\"INFO\"></option><option value=\"WARN\"></option><option value=\"ERROR\"></option></datalist> <label>Text <input type=\"search\" name=\"q\" value=\""
	_html6  = "\"></label> <label>Trace <input name=\"trace\" value=\""
	_html7  = "\"></label> <button type=\"submit\">Show</button> </form> <div id=\"manual\">"
	_html8  = "<ssr-block data-ssr-bind=\"c06682b7.2e41d7b8ba5f6dc1\">"
	_html9  = "<p class=\"note\">"
	_html10 = " runs by hand: its log lines go to the terminal it runs in, not here.</p>"
	_html11 = "</ssr-block></div> <div id=\"problem\">"
	_html12 = "<ssr-block data-ssr-bind=\"c06682b7.de4e69426c275cdb\">"
	_html13 = "<pre class=\"error\">"
	_html14 = "</pre>"
	_html15 = "</ssr-block></div> <div id=\"entries\"> "
	_html16 = "<ssr-block data-ssr-bind=\"c06682b7.28dc75079adb2065\">"
	_html17 = "<table> <thead><tr><th>Time</th><th>App</th><th>Source</th><th>Level</th><th>Message</th><th>Trace</th></tr></thead> <tbody> "
	_html18 = "<tr class=\""
	_html19 = "\"><td><time datetime=\""
	_html20 = "\">"
	_html21 = "</time></td><td>"
	_html22 = "</td><td>"
	_html23 = "</td><td class=\"message\">"
	_html24 = "<span class=\"attrs\">"
	_html25 = "</span>"
	_html26 = "<a href=\"/traces/"
	_html27 = "\">trace</a>"
	_html28 = "</td></tr>"
	_html29 = " </tbody> </table>"
	_html30 = "<p>No log lines match.</p>"
	_html31 = "</ssr-block> </div>"
)
