// Code generated by aicoded. DO NOT EDIT.

package tickets

import (
	"context"
	"io"
	"strings"
	"sync"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/reactive"
	"aicoded.dev/framework/web/render"
)

const routeKey = "8377fbf0"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Everyone bool
	Tickets  []Ticket
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	// Subscribe runs while the page is open and must return when ctx is done.
	Subscribe(ctx context.Context, r *web.Request, state *ReactiveState) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/tickets")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/aicoded/reactive-ZRZHG67R.css\">", "<script defer src=\"/_aicoded/assets/aicoded/reactive-MTQXR3MF.js\"></script>"})
	return s
}

type state struct {
	web.Frame
	mu        sync.Mutex
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) RouteKey() string { return routeKey }

func (s *state) Snapshot(ctx context.Context) map[string]reactive.Binding {
	s.mu.Lock()
	defer s.mu.Unlock()
	return map[string]reactive.Binding{
		routeKey + ".2e99b33e8bf4bb86": renderBlock_2e99b33e8bf4bb86(ctx, &s.RouteData),
	}
}

func (s *state) Subscribe(ctx context.Context, r *web.Request, conn *reactive.Conn) error {
	return s.dp.Subscribe(ctx, r, &ReactiveState{ctx: ctx, s: s, conn: conn})
}

func (s *state) HandleWrite(ctx context.Context, r *web.Request, conn *reactive.Conn, msg reactive.WriteMsg) {
	conn.Reject(ctx, msg, "unknown variable", reactive.CodeValidation)
}

// ReactiveState sends new values of the page's live variables to one open page. Its Set
// methods may be called from any goroutine.
type ReactiveState struct {
	ctx  context.Context
	s    *state
	conn *reactive.Conn
}

// SetTickets stores v as tickets and sends the parts of the page that show it.
func (rs *ReactiveState) SetTickets(v []Ticket) {
	rs.s.mu.Lock()
	defer rs.s.mu.Unlock()
	rs.s.RouteData.Tickets = v
	rs.conn.Enqueue(routeKey+".2e99b33e8bf4bb86", renderBlock_2e99b33e8bf4bb86(rs.ctx, &rs.s.RouteData))
}

func (s *state) Write(w io.Writer) error {
//line index.html:1
	everyone := s.RouteData.Everyone
	_ = everyone
//line index.html:2
	tickets := s.RouteData.Tickets
	_ = tickets
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:3
	if err := render.Text(w, render.If(everyone, "All tickets", "Your tickets")); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:4
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
	if len(tickets) == 0 {
		if _, err := io.WriteString(w, _html3); err != nil {
			return err
		}
//line index.html:5
	} else {
		if _, err := io.WriteString(w, _html4); err != nil {
			return err
		}
//line index.html:7
		if everyone {
			if _, err := io.WriteString(w, _html5); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html6); err != nil {
			return err
		}
//line index.html:10
		for _, t := range tickets {
			if _, err := io.WriteString(w, _html7); err != nil {
				return err
			}
//line index.html:10
			if err := render.Attr(w, t.ID); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
//line index.html:11
			if err := render.Text(w, t.ID); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html9); err != nil {
				return err
			}
//line index.html:12
			if err := render.Text(w, t.Room); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html10); err != nil {
				return err
			}
//line index.html:13
			if err := render.URLPart(w, t.ID); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
//line index.html:13
			if err := render.Text(w, t.Title); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html12); err != nil {
				return err
			}
//line index.html:14
			if everyone {
				if _, err := io.WriteString(w, _html13); err != nil {
					return err
				}
//line index.html:14
				if err := render.Text(w, t.Author); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html14); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html15); err != nil {
				return err
			}
//line index.html:15
			if err := render.Attr(w, t.Status); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
//line index.html:15
			if err := render.Text(w, t.Status.Label()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html9); err != nil {
				return err
			}
//line index.html:16
			if err := render.Text(w, t.Updated.Format("2006-01-02 15:04 UTC")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html16); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html17); err != nil {
			return err
		}
	}
//line route_gen.go:226
	if _, err := io.WriteString(w, _html18); err != nil {
		return err
	}
	return nil
}

func renderBlock_2e99b33e8bf4bb86(ctx context.Context, data *RouteData) reactive.Binding {
	var b strings.Builder
	if err := func(w io.Writer) error {
//line index.html:1
		everyone := data.Everyone
//line index.html:2
		tickets := data.Tickets
//line index.html:4
		if len(tickets) == 0 {
			if _, err := io.WriteString(w, _html3); err != nil {
				return err
			}
//line index.html:5
		} else {
			if _, err := io.WriteString(w, _html4); err != nil {
				return err
			}
//line index.html:7
			if everyone {
				if _, err := io.WriteString(w, _html5); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html6); err != nil {
				return err
			}
//line index.html:10
			for _, t := range tickets {
				if _, err := io.WriteString(w, _html7); err != nil {
					return err
				}
//line index.html:10
				if err := render.Attr(w, t.ID); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html8); err != nil {
					return err
				}
//line index.html:11
				if err := render.Text(w, t.ID); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html9); err != nil {
					return err
				}
//line index.html:12
				if err := render.Text(w, t.Room); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html10); err != nil {
					return err
				}
//line index.html:13
				if err := render.URLPart(w, t.ID); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html11); err != nil {
					return err
				}
//line index.html:13
				if err := render.Text(w, t.Title); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html12); err != nil {
					return err
				}
//line index.html:14
				if everyone {
					if _, err := io.WriteString(w, _html13); err != nil {
						return err
					}
//line index.html:14
					if err := render.Text(w, t.Author); err != nil {
						return err
					}
					if _, err := io.WriteString(w, _html14); err != nil {
						return err
					}
				}
				if _, err := io.WriteString(w, _html15); err != nil {
					return err
				}
//line index.html:15
				if err := render.Attr(w, t.Status); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html11); err != nil {
					return err
				}
//line index.html:15
				if err := render.Text(w, t.Status.Label()); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html9); err != nil {
					return err
				}
//line index.html:16
				if err := render.Text(w, t.Updated.Format("2006-01-02 15:04 UTC")); err != nil {
					return err
				}
				if _, err := io.WriteString(w, _html16); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html17); err != nil {
				return err
			}
		}
//line route_gen.go:341
		return nil
	}(&b); err != nil {
		web.LogError(ctx, "live block not rendered", err, "route", routeKey, "block", "2e99b33e8bf4bb86")
		return reactive.HTMLBinding("")
	}
	return reactive.HTMLBinding(b.String())
}

const (
	_html0  = "<h1>"
	_html1  = "</h1> "
	_html2  = "<ssr-block data-ssr-bind=\"8377fbf0.2e99b33e8bf4bb86\">"
	_html3  = "<p id=\"no-tickets\">No tickets yet.</p>"
	_html4  = "<table id=\"tickets\"> <thead> <tr><th>Ticket</th><th>Room</th><th>Problem</th>"
	_html5  = "<th>Reported by</th>"
	_html6  = "<th>Status</th><th>Updated</th></tr> </thead> <tbody> "
	_html7  = "<tr id=\"ticket-"
	_html8  = "\"> <td>#"
	_html9  = "</td> <td>"
	_html10 = "</td> <td><a href=\"/tickets/"
	_html11 = "\">"
	_html12 = "</a></td> "
	_html13 = "<td>"
	_html14 = "</td>"
	_html15 = " <td class=\"status "
	_html16 = "</td> </tr>"
	_html17 = " </tbody> </table>"
	_html18 = "</ssr-block>"
)
