// Code generated by aicoded. DO NOT EDIT.

package s_id

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "1327ccb7"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	M Message
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Guard(ctx context.Context, r *web.Request) error
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route { return &route{dp: dp} }

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"developer"}} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{"<link rel=\"stylesheet\" href=\"/_aicoded/assets/pages/mail/s_app/s_id/index-3KLZNHKH.css\">"})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(ctx context.Context, r *web.Request) error { return s.dp.Guard(ctx, r) }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:2
	m := s.RouteData.M
	_ = m
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:3
	if err := render.URLPart(w, m.App); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:3
	if err := render.Text(w, m.App); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
//line index.html:4
	if err := render.Text(w, render.If(m.Subject != "", m.Subject, "(no subject)")); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html3); err != nil {
		return err
	}
//line index.html:6
	if err := render.Text(w, m.Folder); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html4); err != nil {
		return err
	}
//line index.html:7
	if err := render.Attr(w, m.Stamp); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html5); err != nil {
		return err
	}
//line index.html:7
	if err := render.Text(w, m.Time); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html6); err != nil {
		return err
	}
//line index.html:8
	if err := render.Text(w, m.From); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html7); err != nil {
		return err
	}
//line index.html:9
	if err := render.Text(w, m.To); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html8); err != nil {
		return err
	}
//line index.html:10
	if m.Cc != "" {
		if _, err := io.WriteString(w, _html9); err != nil {
			return err
		}
//line index.html:10
		if err := render.Text(w, m.Cc); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html10); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html11); err != nil {
		return err
	}
//line index.html:11
	if m.Bcc != "" {
		if _, err := io.WriteString(w, _html12); err != nil {
			return err
		}
//line index.html:11
		if err := render.Text(w, m.Bcc); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html10); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html11); err != nil {
		return err
	}
//line index.html:12
	if m.ReplyTo != "" {
		if _, err := io.WriteString(w, _html13); err != nil {
			return err
		}
//line index.html:12
		if err := render.Text(w, m.ReplyTo); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html10); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html14); err != nil {
		return err
	}
//line index.html:15
	if m.Text != "" {
		if _, err := io.WriteString(w, _html15); err != nil {
			return err
		}
//line index.html:15
		if err := render.Text(w, m.Text); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html16); err != nil {
			return err
		}
//line index.html:16
	} else {
		if _, err := io.WriteString(w, _html17); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html11); err != nil {
		return err
	}
//line index.html:17
	if m.HTML {
		if _, err := io.WriteString(w, _html18); err != nil {
			return err
		}
//line index.html:19
		if err := render.URLPart(w, m.App); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html19); err != nil {
			return err
		}
//line index.html:19
		if err := render.URLPart(w, m.ID); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html20); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html11); err != nil {
		return err
	}
//line index.html:21
	if len(m.Attachments) > 0 {
		if _, err := io.WriteString(w, _html21); err != nil {
			return err
		}
//line index.html:26
		for _, a := range m.Attachments {
			if _, err := io.WriteString(w, _html22); err != nil {
				return err
			}
//line index.html:26
			if err := render.Text(w, a.Name); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html23); err != nil {
				return err
			}
//line index.html:26
			if err := render.Text(w, a.Type); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html23); err != nil {
				return err
			}
//line index.html:26
			if err := render.Text(w, a.Size); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html24); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html25); err != nil {
			return err
		}
	}
//line route_gen.go:253
	return nil
}

const (
	_html0  = "<p><a href=\"/mail/"
	_html1  = "\">All mail of "
	_html2  = "</a></p> <h1>"
	_html3  = "</h1> <table id=\"headers\"> <tr><th>Folder</th><td>"
	_html4  = "</td></tr> <tr><th>Time</th><td><time datetime=\""
	_html5  = "\">"
	_html6  = "</time></td></tr> <tr><th>From</th><td>"
	_html7  = "</td></tr> <tr><th>To</th><td>"
	_html8  = "</td></tr> "
	_html9  = "<tr><th>Cc</th><td>"
	_html10 = "</td></tr>"
	_html11 = " "
	_html12 = "<tr><th>Bcc</th><td>"
	_html13 = "<tr><th>Reply-To</th><td>"
	_html14 = " </table> <h2>Text</h2> "
	_html15 = "<pre id=\"text\">"
	_html16 = "</pre>"
	_html17 = "<p>The message has no text part.</p>"
	_html18 = "<section> <h2>HTML</h2> <iframe sandbox src=\"/_aicoded/mail/"
	_html19 = "/"
	_html20 = "\" title=\"The HTML part of the message\"></iframe> </section>"
	_html21 = "<section> <h2>Attachments</h2> <table id=\"attachments\"> <thead><tr><th>Name</th><th>Type</th><th>Size</th></tr></thead> <tbody> "
	_html22 = "<tr><td>"
	_html23 = "</td><td>"
	_html24 = " bytes</td></tr>"
	_html25 = " </tbody> </table> </section>"
)
