// Package gobuf builds Go source for generated page code.
package gobuf

import (
	"bytes"
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"strconv"
	"strings"
)

// Header starts every generated Go file.
const Header = "// Code generated by aicoded. DO NOT EDIT.\n\n"

// GoBuf collects Go source. Literal output written with WritePrintString is gathered into
// string constants named _html0, _html1, … in order of first use; identical strings share one.
type GoBuf struct {
	out     bytes.Buffer
	pending strings.Builder
	names   map[string]string
	consts  []string
}

// New returns an empty buffer.
func New() *GoBuf {
	return &GoBuf{names: map[string]string{}}
}

// WriteString writes Go source.
func (b *GoBuf) WriteString(s string) {
	b.flush()
	b.out.WriteString(s)
}

// WriteStringLn writes Go source and a newline.
func (b *GoBuf) WriteStringLn(s string) {
	b.flush()
	b.out.WriteString(s)
	b.out.WriteByte('\n')
}

// WriteQuotedString writes s as a Go string literal, followed by the suffixes.
func (b *GoBuf) WriteQuotedString(s string, suffixes ...string) {
	b.flush()
	b.out.WriteString(strconv.Quote(s))
	for _, suffix := range suffixes {
		b.out.WriteString(suffix)
	}
}

// WritePrintString adds s to the literal output that the generated code writes to w.
func (b *GoBuf) WritePrintString(s string) {
	b.pending.WriteString(s)
}

// WriteConsts writes the string constants used so far as one const block. It writes
// nothing when there are none.
func (b *GoBuf) WriteConsts() {
	b.flush()
	if len(b.consts) == 0 {
		return
	}
	b.out.WriteString("const (\n")
	for i, v := range b.consts {
		b.out.WriteString(constName(i))
		b.out.WriteString(" = ")
		b.out.WriteString(strconv.Quote(v))
		b.out.WriteByte('\n')
	}
	b.out.WriteString(")\n")
}

// lineReset starts the comment that WriteLineReset writes, before the file name.
const lineReset = "//line aicoded-reset "

// WriteLineReset ends code that //line directives map to a template, on a line of its own: in
// the source Formatted returns, the lines that follow are those of the generated file name
// itself. Literal output not yet written comes after it.
func (b *GoBuf) WriteLineReset(name string) {
	b.out.WriteString(lineReset + name + "\n")
}

// Formatted returns the source formatted by go/format, with each comment of WriteLineReset made
// the //line directive that names the line after it.
func (b *GoBuf) Formatted() ([]byte, error) {
	b.flush()
	code, err := format.Source(b.out.Bytes())
	if err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", code, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		return nil, err
	}
	lines := bytes.SplitAfter(code, []byte("\n"))
	for _, g := range f.Comments {
		for _, c := range g.List {
			name, ok := strings.CutPrefix(c.Text, lineReset)
			if !ok {
				continue
			}
			p := fset.PositionFor(c.Pos(), false)
			if p.Column != 1 {
				return nil, fmt.Errorf("line %d: a line reset must start its line", p.Line)
			}
			lines[p.Line-1] = fmt.Appendf(nil, "//line %s:%d\n", name, p.Line+1)
		}
	}
	return bytes.Join(lines, nil), nil
}

func (b *GoBuf) String() string {
	b.flush()
	return b.out.String()
}

func (b *GoBuf) flush() {
	if b.pending.Len() == 0 {
		return
	}
	s := b.pending.String()
	b.pending.Reset()
	name, ok := b.names[s]
	if !ok {
		name = constName(len(b.consts))
		b.names[s] = name
		b.consts = append(b.consts, s)
	}
	b.out.WriteString("if _, err := io.WriteString(w, " + name + "); err != nil {\nreturn err\n}\n")
}

func constName(i int) string { return "_html" + strconv.Itoa(i) }
