// Code generated by aicoded. DO NOT EDIT.

package pages

import (
	"database/sql/driver"
	"io"
	"net/http"
	"time"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "4d2c"

var client = http.DefaultClient

// NewHandler returns the handler of the app's pages.
func NewHandler() http.Handler { return web.New(nil, web.Options{}) }

type state struct {
	store Store
	q     string
}

func (s *state) Write(w io.Writer) error {
//line index.html:6
	store := s.store
//line index.html:7
	q := s.q
	if _, err := io.WriteString(w, routeKey); err != nil {
		return err
	}
//line index.html:11
	if err := render.Text(w, store.DB.QueryRow("SELECT "+q).Err()); err != nil {
		return err
	}
//line index.html:12
	if err := render.Text(w, store.DB.QueryRow("DELETE FROM carts WHERE id = ?", q).Err()); err != nil {
		return err
	}
//line index.html:13
	if err := render.Text(w, store.DB.Driver()); err != nil {
		return err
	}
//line index.html:14
	if err := render.Text(w, http.Get); err != nil {
		return err
	}
//line index.html:15
	if err := render.Text(w, http.StatusText(http.StatusOK)); err != nil {
		return err
	}
//line index.html:16
	time.Local = time.UTC
//line index.html:17
	if err := render.Text(w, interface{ Driver() driver.Driver }(store.DB).Driver()); err != nil {
		return err
	}
	return nil
}

//line /elsewhere/index.html:1
var transport = http.DefaultTransport
