// Code generated by aicoded. DO NOT EDIT.

package inbox

import (
	"context"
	"io"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/render"
)

const routeKey = "83bb8523"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Mail []Summary
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/inbox")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"editor"}} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	return s
}

type state struct {
	web.Frame
	dp        RouteDataProvider
	RouteData RouteData
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(context.Context, *web.Request, web.ResponseWriter) error { return nil }

func (s *state) SubmitForm(context.Context, *web.Request, web.ResponseWriter, string) (bool, error) {
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:2
	mail := s.RouteData.Mail
	_ = mail
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:3
	for _, m := range mail {
		if _, err := io.WriteString(w, _html1); err != nil {
			return err
		}
//line index.html:3
		if err := render.Text(w, m.Subject); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html2); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, _html3); err != nil {
		return err
	}
	return nil
}

const (
	_html0 = "<ul id=\"inbox\">"
	_html1 = "<li>"
	_html2 = "</li>"
	_html3 = "</ul>"
)
