// Code generated by aicoded. DO NOT EDIT.

package pages

import (
	"net/http"

	"aicoded.dev/framework/web"
)

const routeKey = "4d2c"

type state struct{ conn string }

// NewHandler returns the handler of the app's pages.
func NewHandler() http.Handler { return web.New(nil, web.Options{}) }
