// Code generated by aicoded. DO NOT EDIT.

package pages

import (
	"net/http"

	"aicoded.dev/framework/web"

	"blocks/deps"
	routeInbox "blocks/pages/inbox"
	routeItems "blocks/pages/items"
	routeItemsN_id "blocks/pages/items/n_id"
)

// NewHandler returns the handler for the app's pages.
func NewHandler(d *deps.Deps) http.Handler {
	return web.New(map[string]web.Route{
		"/":           NewRoute(NewDP(d)),
		"/inbox":      routeInbox.NewRoute(routeInbox.NewDP(d)),
		"/items":      routeItems.NewRoute(routeItems.NewDP(d)),
		"/items/n_id": routeItemsN_id.NewRoute(routeItemsN_id.NewDP(d)),
	}, web.Options{Assets: assets})
}
