// Code generated by aicoded. DO NOT EDIT.

package status

import (
	"context"
	"io"
	"net/http"

	"aicoded.dev/framework/web"
	"aicoded.dev/framework/web/form"
	"aicoded.dev/framework/web/render"
)

const routeKey = "5714b057"

// RouteData holds the variables the template declares with <ssr:var>.
type RouteData struct {
	Ticket Ticket
}

// FormStatusValues holds the fields of the form status.
type FormStatusValues struct {
	form.BaseFormValues
	Status form.Select[string]
}

// RouteDataProvider is what this page's DP implements.
type RouteDataProvider interface {
	Data(ctx context.Context, r *web.Request, w web.ResponseWriter, data *RouteData) error
	InitStatus(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormStatusValues) error
	ProcessStatus(ctx context.Context, r *web.Request, w web.ResponseWriter, data *FormStatusValues) error
}

type route struct{ dp RouteDataProvider }

// NewRoute returns the page for this folder.
func NewRoute(dp RouteDataProvider) web.Route {
	web.CheckNoGuard(dp, "/tickets/n_id/status")
	return &route{dp: dp}
}

func (rt *route) Access() web.Access { return web.Access{Roles: []string{"hotel-ops"}} }

func (rt *route) Layout() bool { return false }

func (rt *route) NewState() web.RouteState {
	s := &state{dp: rt.dp}
	s.SetAssets([]string{})
	s.FormStatus.SetElements([]form.Element{&s.FormStatus.Status})
	return s
}

type state struct {
	web.Frame
	dp         RouteDataProvider
	RouteData  RouteData
	FormStatus FormStatusValues
}

func (s *state) Guard(context.Context, *web.Request) error { return nil }

func (s *state) InitForms(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	s.FormStatus.Prepare(routeKey+".status", r.CSRFToken())
	if err := s.dp.InitStatus(ctx, r, w, &s.FormStatus); err != nil {
		return err
	}
	return nil
}

func (s *state) SubmitForm(ctx context.Context, r *web.Request, w web.ResponseWriter, id string) (bool, error) {
	switch id {
	case routeKey + ".status":
		if form.IsMultipart(r.Request) {
			return true, web.Error(http.StatusBadRequest, "The form was sent in the wrong format.")
		}
		s.FormStatus.Status.Process(r.Request, "status", false, true)
		s.FormStatus.MarkValidated()
		if s.FormStatus.HasError() {
			return true, nil
		}
		return true, s.dp.ProcessStatus(ctx, r, w, &s.FormStatus)
	}
	return false, nil
}

func (s *state) Data(ctx context.Context, r *web.Request, w web.ResponseWriter) error {
	return s.dp.Data(ctx, r, w, &s.RouteData)
}

func (s *state) DefaultRoute(context.Context, *web.Request) (string, error) { return "", nil }

func (s *state) Write(w io.Writer) error {
//line index.html:2
	ticket := s.RouteData.Ticket
	_ = ticket
	if _, err := io.WriteString(w, _html0); err != nil {
		return err
	}
//line index.html:4
	if err := render.Text(w, ticket.ID); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html1); err != nil {
		return err
	}
//line index.html:4
	if err := render.Text(w, ticket.Room); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html2); err != nil {
		return err
	}
//line index.html:4
	if err := render.Text(w, ticket.Title); err != nil {
		return err
	}
	if _, err := io.WriteString(w, _html3); err != nil {
		return err
	}
	{
		form := s.FormStatus
		_ = form
		if _, err := io.WriteString(w, _html4); err != nil {
			return err
		}
		if err := render.Attr(w, form.ID()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html5); err != nil {
			return err
		}
		if err := render.Attr(w, form.Token()); err != nil {
			return err
		}
		if _, err := io.WriteString(w, _html6); err != nil {
			return err
		}
		{
//line index.html:8
			input := form.Status
			_ = input
			if _, err := io.WriteString(w, _html7); err != nil {
				return err
			}
//line index.html:8
			if err := render.Attr(w, render.If(form.IsValidated(), render.If(input.HasError(), "invalid", "valid"), "")); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html8); err != nil {
				return err
			}
			isSelected := func(v string) bool { return v == input.GetValue() }
			for _, o := range input.GetOptions() {
				if err := o.WriteHtml(w, isSelected); err != nil {
					return err
				}
			}
			if _, err := io.WriteString(w, _html9); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html10); err != nil {
			return err
		}
//line index.html:10
		if form.Status.HasError() {
			if _, err := io.WriteString(w, _html11); err != nil {
				return err
			}
//line index.html:10
			if err := render.Text(w, form.Status.GetError()); err != nil {
				return err
			}
			if _, err := io.WriteString(w, _html12); err != nil {
				return err
			}
		}
		if _, err := io.WriteString(w, _html13); err != nil {
			return err
		}
	}
	return nil
}

const (
	_html0  = "<h1>Change the status</h1> <p>#"
	_html1  = ", room "
	_html2  = ": "
	_html3  = "</p> "
	_html4  = "<form method=\"post\" enctype=\"application/x-www-form-urlencoded\"><input type=\"hidden\" name=\"_aicoded_form\" value=\""
	_html5  = "\"><input type=\"hidden\" name=\"_aicoded_csrf\" value=\""
	_html6  = "\"> <div class=\"field\"> <label for=\"status\">Status</label> "
	_html7  = "<select name=\"status\" required id=\"status\" class=\""
	_html8  = "\">"
	_html9  = "</select>"
	_html10 = " "
	_html11 = "<p id=\"status-error\" class=\"error\">"
	_html12 = "</p>"
	_html13 = " </div> <button type=\"submit\">Save</button> </form>"
)
